### ISSUE TITLE
Why not support UTF8

### ISSUE THREAD

**Issue by tfgzs** [federico-terzi/espanso#101]
Good tool
But I hope to support Chinese
Thanks

**Comment by federico-terzi** [comment]
Hi @tfgzs,

Thank you for your feedback. It's strange because espanso should already support UTF8, what kind of problems are you experiencing?
I need more information to help you, in particular:
* Which operating system are you using?
* Which version of espanso are you using? ( you can check the version by using the `espanso --version` command in the terminal )
* Could you post your configuration file with the problematic matches?

Thanks

**Comment by tfgzs** [comment]
- MacOS  10.15
- espanso 0.3.1    


- default.yml
```yml
  # Dates
  - trigger: ":日期"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
```
:日期

**Comment by federico-terzi** [comment]
Thanks for the help @tfgzs 
I'll take a look in the next few days and I'll get back to you.
By the way, I'm not very experienced with Chinese keyboards, could you link me with an image of the type of keyboard you are using?

Thanks

**Comment by tfgzs** [comment]
@federico-terzi 
I think you can copy the script above or replace it with other special characters.
the Chinese MAC keyboard is the same as the English keyboard.
Chinese like to use this input software: https://pingyin.sogou.com/mac/
Thank you very much for your help.
Welcome to China

Thanks

**Comment by federico-terzi** [comment]
Hi @tfgzs,
I'm sorry for the late reply, I've been very busy in the last few weeks. 
I looked into your problem but unfortunately, I couldn't find any satisfying solution.
I'll keep this issue open in case someone with some experience in MacOS Chinese input methods  finds a solution.

Cheers

**Comment by tylerlmz1** [comment]
- espanso 0.4.1
- Linux Mint 19.3
- default.yml

I've tested this out on Linux Mint 19.3, it doesn't work too

anyway, I love this software, I have been looking for a text expanding solution for Linux for quite long, and I'm amazed by the premium quality! Thank you so much for this!

**Comment by federico-terzi** [comment]
Thank you for the kind words @tylerlmz1!
Unfortunately, due to the very small amount of free time I have in this moment, it's hard to predict when this feature could be implemented... but stay tuned :)

**Comment by 2392711432** [comment]
> Good tool
> But I hope to support Chinese
> Thanks

**Comment by 2392711432** [comment]
ดีมาก​ครับ​

**Comment by TullyMonster** [comment]
```
espanso 2.1.3-alpha
Windows 10 (21H2)
```
Divine Tool, but Chinese triggers was also not supported on Windows. This is my Configuration:
```yaml
# ./match/base.yml
matches:

  - trigger: "日期"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"
```
Enter Chinese trigger `日期` based on the previous configuration information:
![presentation](https://s3.bmp.ovh/imgs/2022/02/ccf264acb9f04310.gif)

> How to enable Chinese input method: https://bing.com/search?q=enable+Chinese+input+method
@federico-terzi
