### ISSUE TITLE
Capture non-word characters when expanding word characters

### ISSUE THREAD

**Issue by es183923** [federico-terzi/espanso#1016]
**Is your feature request related to a problem? Please describe.**
Suppose i have a trigger:
```yaml
  - trigger: "dont"
    word: true
    replace: "don't"
```
If I were to type `dont` in a chat box, and press enter, it would result in sending:
```
dont
don't
```
Using a trigger that requires changing the whole text has the same issue:
```yaml
  - trigger: "hello"
    word: true
    replace: "espanso"
```

**Describe the solution you'd like**
Capture the non-word characters (newline in this case) to prevent this from happening.

**Describe alternatives you've considered**
I'm not sure how to have any alternatives.

**Additional context**
Here's a video: (using Discord)

https://user-images.githubusercontent.com/72744903/158024143-db4379ec-c284-491c-b466-23b1daedf4fc.mp4
