### ISSUE TITLE
Time zone specifier %Z is same as %:z

### ISSUE THREAD

**Issue by hegyre** [federico-terzi/espanso#1027]
**Describe the bug**
[Time zone specifiers](https://espanso.org/docs/matches/extensions/#time-zone-specifiers) are well documented.
However, when playing around with it, I found %Z returns the same as %:z

**To Reproduce**
```
  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S%Z"

```
**Current behavior with 2.1.4-beta**
21:48:36+01:00

**Expected behavior**
21:48:36CEST

**Setup information**
- OS: Windows 10 20H2
- Version: 2.1.4-beta
