### ISSUE TITLE
date variable with dashes no longer working in V 2-1-4-beta

### ISSUE THREAD

**Issue by Dujebai** [federico-terzi/espanso#1061]
`:date` produced YYYY-MM-DD in previous version   
after migration to 2-1-4-beta the dashes are omitted; result: YYYYMMDD  

```  - trigger: ":date"
    replace: "{{osmdate}}"
    label: "YYYY-MM-DD"
    vars:
      - name: osmdate
        type: date
        params:
          format: "%Y-%m-%d"
```
I tried to escape the dash with several combinations, but obviously didn't imagine the right one ;-)  
help wanted - tired of placing the dashes manually - I'm sure this is a small thing for the pros :-)  

**Setup information**
- ubuntu 20.04
- espanso 2.1.4-beta

**Comment by federico-terzi** [comment]
Hey @Dujebai,

I'm sorry you experienced this problem! Does it work if you use the `force_clipboard` option?

```
    replace: "{{osmdate}}"
    force_clipboard: true
    label: "YYYY-MM-DD"
    vars:
      - name: osmdate
        type: date
        params:
          format: "%Y-%m-%d"
```

Cheers :)
