### ISSUE TITLE
Matching is not deleting last char if it's there multiple times

### ISSUE THREAD

**Issue by timorunge** [federico-terzi/espanso#109]
If you have some matches in trigger in the following format:

```yaml
matches:
  - trigger: "ws.."
    replace: "What should we do?" 
```

The result will be: 

```
What should we do?.
```

(there will be a dot after the `replace` trigger)
