### ISSUE TITLE
Possibility for nested triggers

### ISSUE THREAD

**Issue by timorunge** [federico-terzi/espanso#110]
It would be great if `espanso` would have the possibility for nested triggers. As an example:

```yaml
matches:
  - trigger: "sigi.."
    replace: "My great internal E-Mail signature"
# Example 1:
  - trigger: "fwdi.."
    replace: "Hey $|$,\ncan you please have a look at the mail which I FWD to you?\nsigi.."
# Example 2:
  - trigger: "fwdi.."
    replace: "Hey $|$,\ncan you please have a look at the mail which I FWD to you?\n{{sigi..}}"
    vars:
      - name: "sigi.."
        type: reference
```
