### ISSUE TITLE
Espanso randomly removes or moves characters from shell output

### ISSUE THREAD

**Issue by jdoss** [federico-terzi/espanso#1104]
**Describe the bug**
I use this to grab the currently playing song URL on Spotify from dbus:

```yaml
matches:
  - trigger: ":su"
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n '/url/{n;p}' | cut -d '"' -f 2
          shell: bash
```

Which has worked well until recently. Now when I use it, it will randomly move characters in the URL which breaks loading the song when clicked. For example this creates the correct URL:

```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n '/url/{n;p}' | cut -d '"' -f 2
https://open.spotify.com/track/5FbOlz2sIjmCVkFMFH7O0e
```

when I did `:su` in a Signal flatpak window it produced this URL:

```
https://open.spotify.com/track/5FbOlz2sIjmVkCFMFH7O0e 
```

The `C` was shifted over to the right by 3. The position is random. Sometimes characters will be up in the `open.spotify.com` part of the URL for example.

**Setup information**
- OS: Fedora 36
- Version: espanso 2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @jdoss,

I'm sorry you experienced this problem! Are you on Wayland? You might want to try with the force_clipboard: true option

```
matches:
  - trigger: ":su"
    word: true
    force_clipboard: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n '/url/{n;p}' | cut -d '"' -f 2
          shell: bash
```

Cheers :)
