### ISSUE TITLE
Internal Patches ignore user config (at least for: Alacritty Linux X11)

### ISSUE THREAD

**Issue by AXGKl** [federico-terzi/espanso#1106]
**Describe the bug**

At least `alacritty_terminal_x11.rs` sets the `paste_shortcut` hard for Linux/X11 to `CTRL+SHIFT+V`, w/o checking back if user configured a different one via 

```yaml
~/.conf/e/config ❯ cat alacritty.yml
filter_class: Alacritty
paste_shortcut: CTRL+V
```

But the default CTRL+Shift+V for paste is often reconfigured in alacritty, i.e. colliding with vim block edit. 

**To Reproduce**

1. In alacritty, configure paste away from CTRL+Shift+V, e.g. like so:

```yaml
  - { key: V, mods: Control|Shift, action: ReceiveChar } # vim block edit
  - { key: V, mods: Control, action: Paste }
  
```

2. Try configure `paste_shortcut` in espanso, e.g. like shown above.

**Expected behavior**

User defined `paste_shortcut` should be honored.

**Setup information**
- OS: Linux
- Espanso: 2.1.5-beta

----

I suggest to check in the patches if user configs are set. 

right now there is no other way then self-compiling Espanso - in my case kicking out the patch from the sources first, then build.

Then all worked like a charm (thanks btw, the app rocks).

Ref: https://github.com/federico-terzi/espanso/issues/1088

**Comment by AXGKl** [comment]
Closing, stumbled over the apply_patch feature:

```yaml
~/.config/espanso/config ❯ cat alacritty.yml
filter_class: Alacritty
paste_shortcut: CTRL+V
backend: Clipboard
apply_patch: false
```

and all works perfectly :heart:
