### ISSUE TITLE
Replacement is not working with Cyrillic as a trigger.

### ISSUE THREAD

**Issue by slava-basko** [federico-terzi/espanso#1133]
**Describe the bug**
Replacement is not working with Cyrillic.

**To Reproduce**
1. Edit match/base.yml.
2. Add new config for "tomorrow" so the config file should be like:
```yml
matches:
  - triggers: [":tomorrow", ":завтра"] 
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y-%m-%d"
          offset: 86400
```
3. Save the file and make sure that Espanso reloads the config.
4. Try to type ":завтра" and nothing happens.

**Expected behavior**
Tomorrow date expected.

**Logs**
No error because of valid YML.

**Setup information**
- OS: macOS Big Sur 11.6.6 (20G624)
- Version: 2.1.5-beta
