### ISSUE TITLE
Espanso/Macos/Microsoft RDP

### ISSUE THREAD

**Issue by sciencetaco** [federico-terzi/espanso#123]
This is more of a feature request - the ability to use text expansion as configured on my desktop in RDP sessions would be amazing. I know it's possible, atext does it, but I much prefer espanso. Would it be possible to give espanso the ability to work with RDP sessions? Currently, if i type a trigger, the text will just disappear. Clipboard is shared between the client and the remote machine. I'm using the Microsoft client from the app store. Thank you.

**Comment by federico-terzi** [comment]
Hi @sciencetaco,

Thank you for your feedback. I will need a few details to get started:
* Where does espanso run? On the host machine or the client?
* Are you using Windows on both sides?

Thanks for your help

**Comment by sciencetaco** [comment]
@federico-terzi I'm running os x 10.15 on my desktop, espanso runs there, installed via your brew recipe. It only runs on the local machine, as I have extremely limited permissions on the remote end, which is a windows 10. I access it using the Microsoft RDP app from the app store. My config is super basic: 
```
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":end"
    replace: "thank you,\njames"
  - trigger: ":port"
    replace: "The AP did not return from a port/poe cycle. FS, please investigate."

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
```

Here is a link to a video clip of what happens when I attempt a trigger: 

[Demo](https://imgur.com/tv9eH7M)


thank you for taking a look at this.
