### ISSUE TITLE
Multiline strings are not working correctly on Thunderbird Ubuntu

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#130]

**Comment by federico-terzi** [comment]
espanso 0.4.0 will ship with **configurable paste shortcuts** that will enable the user to select the correct paste shortcut based on the application. 

In order to correctly expand multiline strings with Thunderbird, espanso needs to use the `CTRL+SHIFT+V` shortcut. After this update, the user will simply need to add the `thunderbird.yml` file in the `user` folder (inside the espanso config directory) with the following content:

```yaml
name: Thunderbird

filter_class: "Thunderbird"
paste_shortcut: CtrlShiftV
```
