### ISSUE TITLE
Warn about conflicting triggers

### ISSUE THREAD

**Issue by tiktuk** [federico-terzi/espanso#135]
It could be nice if Espanso detected and warned about conflicting triggers on startup. So if both `:ab` and `:abcd` was in the config it would warn about `:abcd` being "overwritten" by `:ab`.

**Comment by federico-terzi** [comment]
Hey @tiktuk,

This is a nice idea, I'll try to include it in the next version of espanso as I also had a similar problem.

Thanks for your help! :)

**Comment by jpmvferreira** [comment]
I don't think this is quite working, here's an example:
```yaml
matches:
  - triggers: [":Alpha:", ":a:"]
    replace: "Α"

  - triggers: [":alpha:", ":a:"]
    replace: "α"
```

Running `espanso restart` will output `Daemon started correctly` and now warn me about anything. 

When using the trigger `:a:` it replaces it to `A` which is the first trigger. 

Shouldn't it also warn me in situations like these?
