### ISSUE TITLE
Regex in trigger

### ISSUE THREAD

**Issue by Kwelity** [federico-terzi/espanso#146]
Hi,

It would be cool to use regular expression for trigger, something like this:

```
- trigger: "^[fF]oo"
  replace: "bar"
```

Thanks for an awesome project :)

**Comment by federico-terzi** [comment]
Hey @Kwelity 

Sorry for the late reply, it's been a super busy week! 
Thanks for the feedback, it would certainly be a good feature to have. Due to the way espanso works, implementing full regex support would be problematic though.

Besides the UPPER/lower case insensitivity, which use-cases would benefit from it in your opinion?
If we individuate a set of cases, we could think about implementing a subset of regex to solve them.

Thanks for your help :)

**Comment by Kwelity** [comment]
Hum, my most "pressing" feature request would be simplify multi trigger with regex, I think I saw another issue about multi trigger. This would solve it just fine.

What I could imagine doing if we had full regex support (I do understand that this is not a trivial feature and might be to demanding in term of performance) would be to capture pattern in a trigger that are then used in replace.

Something like:

```
- trigger: "^:foo(\w*):
  replace: "\1"
```

so that `:foobar:` would evaluate to `bar` and `:foostuff:` to `stuff`

even better with script where group could be used as parameters:

```
- trigger: ":xo(\d)"
  replace: "{{output}}"
  vars:
   - name: output
     type: shell
     params:
       cmd: printf 'xo%.s' {1..$1}
```
Ok, this one I improvised on the spot, I'm not really sure how it would work, maybe pass the captured group as arguments.
But it would give for example: `:xo5` -> `xoxoxoxoxo`

**Comment by federico-terzi** [comment]
Hey @Kwelity,

I agree that full regex support would be ideal. Unfortunately, due to the "realtime" nature of espanso, this is very difficult to achieve. That said, it seems like you want something along the lines of #118, which is one of the most requested features (hopefully coming soon).

I'll think about a way to implement regex support anyway, thank you for the help :)

**Comment by Kwelity** [comment]
@federico-terzi sure thing, I understand, I'll keep an eyes on the issue you mentioned.
If you'd like, you can close this issue.

**Comment by khaveesh** [comment]
This would be a really cool feature. I use regex in Typinator app to correct double capitalized words. Example - DAsh to Dash. This is something that I regularly encounter when I hold the Shift key for slightly too long. Wish you would reopen this issue.

**Comment by federico-terzi** [comment]
@khaveesh Unfortunately, as I said, it's very unlikely that full regex support will make its way into espanso due to performance reasons (some users run up to 50k matches, can you imagine checking every one of them after each character is pressed? that would either be a performance disaster or require implementing a full parallel regex engine such as [hyperscan](https://github.com/intel/hyperscan) which is out of scope at the moment).

That said, if your goal is to correct double capitalized words, you can open an issue specifically for that :)

**Comment by chrisgrieser** [comment]
> This would be a really cool feature. I use regex in Typinator app to correct double capitalized words. Example - DAsh to Dash. This is something that I regularly encounter when I hold the Shift key for slightly too long. Wish you would reopen this issue.

In case anyone finds this via Google like me, [Espanso by now has Regex triggers](https://espanso.org/docs/matches/regex-triggers/) and the double capitalization fixing can be implemented with this:

```yaml
matches:
  - regex: "\\b(?P<one>[A-Z])(?P<two>[A-Z])(?P<three>[a-z])"
    replace: "{{CapitalCased}}"
    vars:
      - name: CapitalCased
        type: shell
        params:
          cmd: "echo $ESPANSO_ONE$(echo $ESPANSO_TWO | tr [A-Z] [a-z])$ESPANSO_THREE"
          shell: bash
```
