### ISSUE TITLE
word: true doesn't work with vars

### ISSUE THREAD

**Issue by muhlinux** [federico-terzi/espanso#147]
Using `word: true` doesn't work with expansions using vars like the date, random, shell, etc.
I like to use triggers without any prefixes. This is hard to do without being able to mark as a word...

**Comment by federico-terzi** [comment]
Hey @muhlinux,

Sorry for the late reply, I've been super busy this week. I tried setting up a word match with a date and is working as expected:

I tried:

```yaml
  - trigger: "test"
    replace: "{{output}}"
    word: true
    vars:
      - name: output
        type: date
        params:
          format: "%m"
```

and it is working as expected. Could you please post the match in which you have problems?

Thanks for your help

**Comment by muhlinux** [comment]
Hi @federico-terzi,
Don't stress mate, you doing good.


This doesn't expand for me, it does without the word match though.
```
  - trigger: "dd"
    replace: "{{output}}"
    word: true
    vars:
      - name: output
        type: date
        params:
          format: "%Y.%m.%d"
```
Another example:
```
  - trigger: "hi"
    replace: "{{output}}"
    word: true
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Greetings."
            - "Hi!"
            - "Hello :)"
            - "Hi there!"
```
espanso 0.4.1
Linux 5.4.3-arch1-1
