### ISSUE TITLE
local date formats

### ISSUE THREAD

**Issue by tiborepcek** [federico-terzi/espanso#156]
Hi and thank you alot for espanso.

I am using espanso under Windows 10 and i would like to locale name of the day stored in %A variable into slovak language.

Is it possible?

**Comment by federico-terzi** [comment]
Hey @tiborepcek,
Thanks for the kind words. At the moment, the Date Extension is based on the [chrono](https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html) Rust crate, which doesn't seem to support localized names.
That said, it should be relatively easy to build a workaround using the [Script Extension](https://espanso.org/docs/matches/#script-extension). For example, if you have python installed you could add the match:

```yaml
  - trigger: ":sdate"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - /home/freddy/Documents/dayoftheweek.py
```
Which will execute the `dayoftheweek.py` script, with the following content:

```python
import datetime
days = {
    0: "Pondelok",
    1: "Utorok",
    2: "Streda",
    3: "Štvrtok",
    4: "Piatok",
    5: "Sobota",
    6: "Nedeľa",
}
weekday = datetime.datetime.today().weekday()
print(days[weekday])
```
