### ISSUE TITLE
Espanso Shell expansion recently missing environment

### ISSUE THREAD

**Issue by xeruf** [federico-terzi/espanso#1710]
**Describe the bug**
I am using espanso to autofill values from the `pass` password manager, which is decrypted with a password-protected GPG key and requires the environment variable PASSWORD_STORE_DIR to be set.
Until a few weeks ago, I would always get a password prompt to decrypt my wallet and then it would autofill just fine, but now neither of these works:
Through running `env` with debug set as a shell command in espanso I found out that the environment variables set in the login shell are not passed on anymore.
Am I missing a setting here?

**To Reproduce**

1. Export an environment variable in your login shell
2. Print it from Expanso Shell extension

**Expected behavior**
Value is printed, instead nothing is printed

**Setup information**
- OS: Manjaro Sway
- Version: 2.1.8

**Comment by xeruf** [comment]
this is quite a gamebreaker for me :/

**Comment by leegenes** [comment]
Similar issue. Also on Manjaro.  Built espanso from AUR.

Setting variable on startup, and confirmed available in the current session. Doesn't expand variable when using what's below. Given that, not so surprisingly output of below example is "foo ".

From `base.yml`

```
  - trigger: ":somevar"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo  foo $SOME_VAR"
```
