### ISSUE TITLE
Shell Commands fail on macos Sonoma 14.0

### ISSUE THREAD

**Issue by dannym-arx** [federico-terzi/espanso#1714]
**Describe the bug**
Any shell completion fails on macos Sonoma (14.0) 

**To Reproduce**

```
  - trigger: ":anything"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'anything'"
```

**Expected behavior**
autocompletion to work properly

**Screenshots**
not relevant

**Logs**
```
15:07:05 [worker(30598)] [WARN] extension 'shell' on var: 'output' reported an error: could not execute command: '`echo 'test'`', error: '`No such file or directory (os error 2)`'
15:07:05 [worker(30598)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute command: '`echo 'test'`', error: '`No such file or directory (os error 2)`'
15:07:08 [worker(30598)] [WARN] extension 'shell' on var: 'output' reported an error: could not execute command: '`echo 'test'`', error: '`No such file or directory (os error 2)`'
15:07:08 [worker(30598)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute command: '`echo 'test'`', error: '`No such file or directory (os error 2)`'
```

**Setup information**
- OS: macOS 14.0
- Version: espanso 2.1.8

**Comment by CharlesButcher** [comment]
I don't seem to have this problem with espanso 2.1.8 and macOS 14.1 on my M1 Mac mini. Does the error persist for you in 14.1?

**Comment by quangnguyen** [comment]
I have same issue on macOS 14.4.1 and espanso 14.4.1 on M1

**Comment by CharlesButcher** [comment]
Interesting. espanso 2.2.1 is working fine on my Intel MacBook (macOS 14.4.1).

I've just realised that the default `base.yml` contains a demo command `:shell` which can be used to test this.

**Comment by adambair** [comment]
Same issue, unable to use shell replacement.

macOS: 15.2
Version: Espanso 2.2.1

```
could not execute command: '`pwd`', error: '`No such file or directory (os error 2)`'
```

**Comment by smeech** [comment]
I've seen this before, and I think it comes down to Espanso not finding the shell's path.

Here in Linux, I would attempt to fix this by initially finding the path using `which zsh` or `type zsh` and then put it in full in a short _script_ trigger, e.g.:
```yml
  - trigger: :test
    replace: '{{Output}}'  
    vars:
      - name: Output
        type: script
        params:
          args:
            - /usr/bin/zsh
            - -c
            - echo 'something'
```
If that works, experiment with replacing the first line of the script with `- zsh` only, and see if that triggers the same error you're seeing. If so, it may be a case of persuading Espanso to find the shell directly, without specifying its path. Bear in mind that the environment variables Espanso gets are not necessarily the same as your user ones. You could try `echo $PATH` outside and within an Espanso trigger.

If you're still stuck, bring the problem to the Discord server, where we have a few regular macOS contributors.


*The above applies if `zsh` is your default shell. Espanso [`shell`](https://espanso.org/docs/matches/extensions/#choosing-the-shell) extension may be expecting `sh` unless you add the line `shell: zsh` to your `params:` once you get things working and can try the `shell` extension again.*

**Comment by adambair** [comment]
Thanks @smeech -- your suggestion worked! Most appreciated.

```yaml
matches:
  - trigger: ",derp"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - "/bin/zsh"
            - "-c"
            - "echo 'something'"

```
