### ISSUE TITLE
How to use forms and shell at the same time?

### ISSUE THREAD

**Issue by moshpirit** [federico-terzi/espanso#1802]
It would be cool if we could write down something like ";command", and then if showed up a form where we entered something and then get a replacement with the output of the bash command.

**Comment by smeech** [comment]
It's not too difficult. Here's a script I wrote in response to a user's query on Discord recently, which builds on the examples in the [docs](https://espanso.org/docs/matches/forms/#using-forms-with-script-and-shell-extensions):
```
  - trigger: :atest
    replace: "{{output}}"
    vars:
      - name: form1
        type: form
        params:
          layout: "[[choices]]"
          fields:
            choices:
              type: choice
              values: |
                one
                two
                three
      - name: output
        type: shell
        params:
          cmd: echo $"{{form1.choices}}" | sed 's/one/four/;s/two/five/;s/three/six/'
```

By making the form a named variable, it takes its output and makes it available for a script to change the output for the `replace:`. If you want to try it, the last line may need altering to suit your OS and shell, but it illustrates the principle.
