### ISSUE TITLE
Incorrect case propagation for the eszett character (ß)

### ISSUE THREAD

**Issue by pyxelr** [federico-terzi/espanso#1805]
**Describe the bug**
The `propagate_case: true` option for `ß` produces a different output than its capital version: `ẞ`.

**To Reproduce**

1. Define the following section in your espanso config:
  ```yaml
    - trigger: "==ss"
      replace: "ß"
      propagate_case: true
  ```
2. Type `==SS`.
3. You will get `SS` instead of the desired `ẞ`.

**Temporary solution**
Meanwhile, the bug is present, I can use:

```yaml
  - trigger: "==ss"
    replace: "ß"
  - trigger: "==SS"
    replace: "ẞ"
```

**Setup information**
- OS: Windows and macOS
- Version: 2.2.1
