### ISSUE TITLE
Problem with bad encoding on MacOS using markdown with polish characters

### ISSUE THREAD

**Issue by DemonicalHunter** [federico-terzi/espanso#1810]
**Describe the bug**
Using markdown with polish characters on MacOS doesn't work it outputs garbage instead of correct text.
Problem does not occure on Windows.

**To Reproduce**
1.Create markdown with polish characters
2.use trigger in any text editor

**Expected behavior**
after using trigger it should create formatted text with polish characters

**Screenshots**
should look like this
![image](https://github.com/espanso/espanso/assets/72436495/78292564-3524-43dc-9ceb-aedeb7795f05)
but it looks like this
![1000013569](https://github.com/espanso/espanso/assets/72436495/56cf53e9-6ca9-4c80-9ce3-552e4da9b9ca)

**Setup information**
- OS: MacOS Monterey
- Version: Espanso 2.2.1

**Comment by smeech** [comment]
I find the clipboard backend works better in text editors.

Try adding:
````
    force_mode: clipboard
````
to your `trigger:`/`markdown:` code.

There are UTF-8 issues (and solutions) with foreign characters, but they tend to apply to Script and Shell extensions, so I don't think this is the problem here.

If the above doesn't fix things would you kindly post the whole expansion code, and information about your editor?

**Comment by DemonicalHunter** [comment]
Hi,

so I tested this clipboard solution on a few MacBooks.
Unfortunately it didn't work.
BUT I found that espanso doesn't have  problem with encoding polish characters on High Sierra on Virtual Machine, not sure why. Maybe this information will help someone to solve this specific problem.

Here is my whole expansion code.
[base.zip](https://github.com/espanso/espanso/files/14010827/base.zip)
I use Notepad ++ on Windows to edit my code for espanso.

**Comment by berot3** [comment]
hi!

for me it doesnt work with german characters on macos sonoma.

as a workaround I have to convert the markdown to html and add a meta at the beginning of each

```
html: |
      <meta charset="UTF-8">
```

***

maybe this info should be added here? https://espanso.org/docs/matches/extensions/#utf-8-characters

**Comment by papageno** [comment]
macOS Version: 15.0.1 (24A348)

espanso Version: 2.2.1

espanso match.yml example:

```yaml
matches:
  - trigger: ":example"
    search_terms:
      - reserve
    label: "にほんご"
    markdown: |
      日本語のテキスト

      {{form.text}}
    vars:
      - name: form
        type: form
        params:
          layout: |
            ...

            [[text]]

            ...
          fields:
            text:
              multiline: true
              trim_string_values: false
```

The same match.yml works flawlessly on Windows 11.

`force_mode: clipboard` has also been added to 'config/default.yml'.
