### ISSUE TITLE
Espanso shell default selection

### ISSUE THREAD

**Issue by aimslut** [federico-terzi/espanso#1816]
So currently I have a regex match which executes a powershell command, however when triggering the replacement, it shows a selection box. Is there any way to default it to outputting the result instead of showing a selection box?
Example: https://streamable.com/lckbyv
Current code:
```
  - regex: "=zapmel\\((?P<value1>.*?),(?P<value2>.*?)\\)"
    replace: "{{result}}"
    vars:
      - name: result
        type: shell
        params:
          shell: powershell
          cmd: "[ redacted ]"
```

**Comment by smeech** [comment]
That's odd.
```
  - regex: =zapmel\((?P<value1>.*?),(?P<value2>.*?)\)
    replace: "{{result}}"
    vars:
      - name: result
        type: shell
        params:
          shell: powershell
          cmd: echo {{value1}}+{{value2}}
```
works fine here (Windows 10 VM). Is there something going on in your script which is interfering?
