### ISSUE TITLE
Rust `as_` methods are probably misinterpreted

### ISSUE THREAD

**Issue by AucaCoyan** [federico-terzi/espanso#1827]
**Describe the bug**
In the [discord chat](https://discord.com/channels/884163483409731584/1013916990760554608/1200031670691172372) a user posted this config is not raised properly

```yaml
matches:
    - trigger: ":checkdiff"
      replace: "vimdiff {{form.day}}/localhost{{form.chemin}} {{form.chemin}}"
      vars:
          - name: days
            type: shell
            params:
                cmd: "echo '1\n2\n3\n4\n5\n6\n7'"
          - name: form
            type: form
            params:
                layout: |
                    Jour : [[day]]
                    Chemin : [[chemin]]
                fields:
                    day:
                        type: choice
                        default: 1
                        values: |
                            {{days}}
```

and Eric Gubler pointed out that there are some methods that are throwing values away if they are not `String`s. 
The is a difference among `as_`, `to_` and `into_`. This is well documented in [the API guidelines book](https://rust-lang.github.io/api-guidelines/naming.html#c-conv)

We should checkout the entire code base for this verbs, so we are using them correctly 👌🏼
