### ISSUE TITLE
xdotool commands require extra key commands

### ISSUE THREAD

**Issue by traptw1thin** [federico-terzi/espanso#1828]
**Describe the bug**
I am using espanso version 2.2.1 on Ubuntu 22.04.3 and when I write commands that use xdotool I find that in order for them to work I need to put in leading BackSpace keys equal to the number of characters in the trigger and also trailing dummy characters/keys equal to the number of characters in the trigger

**To Reproduce**
1. Install xdotool: `sudo apt install xdotool`
2. Create a trigger: 
```
- trigger: ";atme"
    replace: "{{output}}\n"
    vars:
      - name: output
        type: shell
        params:
          cmd: xdotool key --delay 400 at type 'Your Name'
``` 
3. See that when you type `;atme` you end up with nothing `;atme@Your` followed by a newline
4. Modify the trigger to:
```
- trigger: ";atme"
    replace: "{{output}}\n"
    vars:
      - name: output
        type: shell
        params:
          cmd: xdotool key --repeat 5 BackSpace key --delay 400 at type 'Your Nameddddd'
``` 
5. Now you end up with: `@Your Name` followed by a newline

**Expected behavior**
The trigger in step 2 about should provide the output described in step 5 above.

**Additional Info**
Notice that the number of BackSpace key commands that xdotool must send is equal to the length of the trigger. i.e. `;atme` is 5 characters long so 5 BackSpace key commands are needed.
Also similar at the end of the desired output, the number of extra characters in the type command  that xdotool must send is equal to the length of the trigger (you can see the 5 `d`s after `Your Name`).

**Logs**
Nothing changes in the log after saving the trigger in step 2 and then running that trigger in a text editor. However I know sometimes there was a restart of espanso but I cannot reproduce that part so it may have been related to something else.

**Setup information**
- OS: Linux Ubuntu 22.04.3
- Version: 2.2.1
