### ISSUE TITLE
bug: espanso presses Alt when entering/exiting choice dialogs

### ISSUE THREAD

**Issue by phorcys420** [federico-terzi/espanso#1880]
**Describe the bug**
Whenever espanso enters and/or exits a choice dialog, espanso seems to press the Alt key.
I suppose maybe espanso uses alt-tab in some way, or since it's the default trigger key it presses that for some reason.
From what I can tell, this doesn't happen with regular triggers nor forms, only with choices

This behavior causes under-deletion over some RDP sessions.
I know RDP isn't supported but espanso still isn't supposed to press alt and it can work without alt as demonstrated in my video by remapping the keys.

**To Reproduce**
```yaml
matches:
  - trigger: ":hello"
    replace: "Hello World"

  - trigger: ":form"
    form: "[[placeholder]]"

  - trigger: ":choice"
    replace: "{{placeholder}}"
    vars:
      - name: placeholder
        type: choice
        params:
          values: "Hello World"
```

1. Use the `:choice` trigger
(see screen recording for an explanation)

**Expected behavior**

**Screenshots**
[screen recording](https://youtu.be/pKjLkVmdVO4)
I wanted to do a voiceover but couldn't so I had to do this with text.
Sorry if the pace is a bit slow, also sorry if the video isn't very clear as I did it just before leaving work.

**Logs**
N/A

**Setup information**
- OS: Windows 10 22H2 (19045.4046)
- Version: espanso 2.2.1
