### ISSUE TITLE
easier way to transform text input content

### ISSUE THREAD

**Issue by RebelliousSmile** [federico-terzi/espanso#1898]
Hi, 

I'm pretty proud of achieving my mutation of a multiline text into lists, but it's still buggy (wrecks if the user types a quote for example)
Besides, sed use is not very... easy :)
I'm looking for a easier way to create code blocks with espanso forms. Maybe with search replace i would do the same. 

```
  - trigger: ":danger"
    replace: |
      <div class='danger {{form.class}}'>
        <h3>{{form.title}} {{form.stars}}</h3>
        <p>{{form.description}}</p>
        <h4>{{form.subtitle}}</h4>
        <ul>
          {{flist1}}
        </ul>
        <hr>
        <ul>
          {{flist2}}
        </ul>
        <hr>
        <ul>
          {{flist3}}
        </ul>
      </div>
    vars:
      - name: "form"
        type: form
        params:
          layout: |
            Classe : [[class]]
            Nom : [[title]]
            Menace : [[stars]]
            Description: [[description]]
            Seuils : [[subtitle]]
            Actions spéciales : [[list1]]
            Actions majeures : [[list2]]
            Actions mineures : [[list3]]
          fields:
            class:
              value: "bg3"
            title: {}
            stars:
              type: list
              values:
                - " "
                - "★"
                - "★★"
                - "★★★"
                - "★★★★"
                - "★★★★★"
            description:
              multiline: true
            subtitle: {}
            list1:
              multiline: true
            list2:
              multiline: true
            list3:
              multiline: true
      - name: flist1
        type: shell
        params:
          cmd: "echo '{{form.list1}}' | sed -e 's/^/<li>/' -e 's/$/<\\/li>/' -e 's/^<li>$/<li>/' -e 's/<\\/li>$/<\\/li>/'"
      - name: flist2
        type: shell
        params:
          cmd: "echo '{{form.list2}}' | sed -e 's/^/<li>/' -e 's/$/<\\/li>/' -e 's/^<li>$/<li>/' -e 's/<\\/li>$/<\\/li>/'"
      - name: flist3
        type: shell
        params:
          cmd: "echo '{{form.list3}}' | sed -e 's/^/<li>/' -e 's/$/<\\/li>/' -e 's/^<li>$/<li>/' -e 's/<\\/li>$/<\\/li>/'"

```

**Comment by smeech** [comment]
What exactly do your `sed` lines do? I'm struggling with several `unknown option to s'`, which are making it difficult for me to work out.
They take the list and wrap each item in `<li></li>`?

**Comment by RebelliousSmile** [comment]
![Capture d’écran du 2024-03-12 10-49-21](https://github.com/espanso/espanso/assets/40766799/10368780-3c8a-44dc-8824-1b2c9176c296)
yes, the idea is to make a < li> for each line of the multiline text.

**Comment by smeech** [comment]
You could set a global variable to save repeating the command, and `awk` may be simpler:
```yml
global_vars:
  - name: pattern
    type: echo
    params:
      echo: awk '{print "<li>" $0 "</li>"}'
```
then each item is:
```yml
      - name: flist1
        type: shell
        params:
          cmd: echo "{{form.list1}}" | {{pattern}}
```
However, whatever I do I get alignment problems with the output.
