### ISSUE TITLE
espanso will only use system-installed interpreters

### ISSUE THREAD

**Issue by Rustplicant** [federico-terzi/espanso#1950]
### Description

Hi there, is there a way to make espanso use a different Python version installed in the system?
I'm using pyenv in both macOS and Linux to set latest Python version globally, and espanso stubbornly keeps using system-installed version.
In my use case, setting absolute path in the script extension is really not preferred, as I'm syncing the match folder and its content between Windows, macOS, and Linux systems.

EDIT:
It seems that this also affects shell extension, as I have PowerShell 7.4 installed in my Windows machine.
In Windows, possible values for the `shell` parameter are `cmd`, `powershell`, `wsl`. Defining `powershell` will simply use the out-of-the-box PowerShell version 5.1.
Defining `pwsh` as value will simply output this error:
```
[WARN] extension 'shell' on var: 'varPwsh' reported an error: invalid shell: `pwsh` is not a valid one
```
Is there a way to define absolute path of the interpreter as variables, perhaps in `default.yml`, so one can maintain consistent matches files across different platforms?

**Comment by smeech** [comment]
I think `Pwsh` as a shell is coming to Windows. I have it working on Linux, and it appears in the dev branch code alongside the other Windows alternatives.

A workaround for Python for now may be to define a global variable for the interpreter path, depending on the OS. E.g.:
```yml
global_vars:
  - name: python # Linux
    type: echo
    params:
      echo: /usr/bin/python
```
for use in expansions:
```yml
  - trigger: :test
    replace: "{{output}}"          
    vars:
      - name: output
        type: script
        params:
          args: ["{{python}}", -c, print("something")]
```
or
```yml
          args: ["{{python}}", /path/to/your/script.py]
```
for example. But, I can see, one still has to use the absolute path, so that may not help.
Do you need multiple versions of Python on your system?
I suppose you could add pyenv to Windows too, and read it into a global_var using a script on all OSs, with something like:
```py
import os; print(os.path.join(os.getenv("PYENV_ROOT"), "shims", "python"))
```
?
