### ISSUE TITLE
replace multi clipboards

### ISSUE THREAD

**Issue by abappl** [federico-terzi/espanso#1977]
### Description

I wish there is a feature to replace from recently copied clipboards.
(windows)

For example.

```
matches:
  - trigger: ":select"
    replace: "select {{clipboard1}} from {{clipboard2}} where rownum <= 100;"
    vars:
      - name: "clipboard1"
        type: "clipboard"
      - name: "clipboard2"
        type: "clipboard"  
```

1) Copies a few words from source text.
source text: output column **COL1** from table **TBL1**. and limit 100 rows.
1st copy : **COL1**
2st copy: **TBL1**
Now, COL1, TBL1 are on clipboard.

2) type trigger word
:select

3) expect result
select **COL1** from **TBL1** where rownum <= 100;
