### ISSUE TITLE
Using the multiline feature will delete all whitespace infront of scond row

### ISSUE THREAD

**Issue by JKutscha** [federico-terzi/espanso#1990]
### Description

If you have this:

`- trigger: ":trig"`
`    form: |`
`      - trigger: ":[[trigger]]"`
`        replace: "[[replace]]"`

it will lead to

`- trigger: ":test"`
`replace: "test123"`

and this leads to a malformed yaml. 

### Expected behavior

The white space in front of the second row should be kept that the indentation matches the prior line.

### Your environment

- Espanso version (e.g., 2.1.4-beta): v2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
It will depend on your editor - many support automatic indentation, which will affect how the trigger expands.
```yml
- trigger: ":trigb"
  form: >2
      - trigger: ":[[trigger]]"
        replace: "[[replace]]"
```
works fine here if started at the baseline in Xed, Geany, and VSCodium, but not in Micro, for which I need:
```yml
- trigger: ":trigm"
  form: >2
      - trigger: ":[[trigger]]"
      replace: "[[replace]]"
```
Espanso can't predict how the editor will interpret the input.
