### ISSUE TITLE
Shell Extension adding new line at the end

### ISSUE THREAD

**Issue by 0x3333** [federico-terzi/espanso#201]
I'm trying to create a `:ip` expansion, but it keeps adding a new line at the end. I'm on a Mac.

```
- trigger: ":ip"
  replace: "{{output}}"
  vars:
    - name: output
      type: shell
      params:
        cmd: "ipconfig getifaddr en0"
```

The `ipconfig` command gives me a new line at the end, so it is expected, but if I remove it, I don't get the output, like:

```
- trigger: ":ip"
  replace: "{{output}}"
  vars:
    - name: output
      type: shell
      params:
        cmd: "ipconfig getifaddr en0 | head -c -1"
```

`ipconfig getifaddr en0 | head -c -1` running in a terminal gives me:

```
192.168.1.122
```
Without a new line at the end...

```
ipconfig getifaddr en0 | head -c -1 | hexdump -C
00000000  31 30 2e 32 30 2e 30 2e  31 34 39                 |10.20.0.149|
0000000b
```

**Comment by 0x3333** [comment]
I made it work using:

```
cmd: "printf \"%s\" \"$(ipconfig getifaddr en0)\""
```

But it is odd why the `head` command didn't work.

**Comment by federico-terzi** [comment]
Hey @0x3333 ,

To trim the output of a shell script you can use the `trim` option:

```yaml
- trigger: ":ip"
  replace: "{{output}}"
  vars:
    - name: output
      type: shell
      params:
        cmd: "ipconfig getifaddr en0"
        trim: true
```

I've just realized I didn't mention it anywhere in the docs! I'll definitely add it as soon as I work on it.

Let me know if you have other doubts :)

Cheers
