### ISSUE TITLE
Can't create snippet to add $|$ (the actual set of characters)

### ISSUE THREAD

**Issue by alltiagocom** [federico-terzi/espanso#2019]
### Description

When I try to create a snippet that adds `$|$`, it always replaces with the cursor position

### Steps to reproduce

I tried this:
```yaml
  #Espanso cursor
  - trigger: "4\\4"
    replace: "\$\|\$"
```
This:
```yaml
  #Espanso cursor
  - trigger: "4\\4"
    replace: "{{cursor}}"
    vars:
      - name: cursor
        type: echo
        params:
          echo: $|$
```

And some other variations, but I always end up with an empty space (it deletes the key sequence `4\4` and nothing shows up). On Discord 2 other users thought the same thing about it and that this is probably a bug.

### Your environment

- Operating system and version (e.g., macOS 10.15.7):
- Espanso version: 2.2.1

**Comment by alltiagocom** [comment]
Update:
I was able to achieve the desired result by using
```yaml
  #Espanso cursor
  - trigger: "4\\4"
    html: "&#36;|&#36;"
   ```
   
   This seems to be a workaround, but is this the only option? Or should it work with escaped symbols as well?
