### ISSUE TITLE
Unlimited regex pattern length

### ISSUE THREAD

**Issue by yaz008** [federico-terzi/espanso#2021]
# Description

## Current limitations

Patterns are limited to 30 symbols in length. Patterns exceeding this limit will not be detected. Documentation states that this limitation was implemented for the sake of performance, as longer patterns can significantly slow down processing.

## Proposal

Let the default value remain 30 and add an option for individual patterns to exceed the limit

# Motivation

## Special patterns

This is significantly limiting capturing patterns like
[starting-symbol] (?P<pattern>[what-ever-symbol-set]*) [ending-symbol]

Which turned out to be very useful as the captured pattern is accessible through the ESPANSO_PATTERN variable for later processing

## Performance

Such patterns are easy-to-capture and won't hurt the performance much

# Alternatives

## Form variables

Add a special form field that saves it's content to a temporary file (ESPANSO_TEMP), so something like that would be possible:

```yaml
matches:
  - trigger: ":pyscript"
    form: |
      [[pyscript]]
    form_fields:
      script:
        type: variable
        multiline: true
        on_submit:
          - action: run
            params:
              - python
              - "$ESPANSO_TEMP"
```
