### ISSUE TITLE
:date 2024'08'02

### ISSUE THREAD

**Issue by witopea** [federico-terzi/espanso#2033]
### Description

Hello, on Arch Linux, when I type **:date** it outputs **2024'08'02** instead of **2024-08-02**.
It uses single quotes ' instead of hyphens -.

If I save the file `$CONFIG/espanso/match/base.yml` it fixes the issue. However, every time I boot the system, the same thing happens: it puts single quotes around the dates.

Thanks

### Your environment

- Operating system and version (Archlinux):
- Espanso version (Appimage 2.2.1):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
What's the code of your `:date` trigger in `base.yml`?
What are the outputs of `locale` and `date +%x` at the command-line?

**Comment by witopea** [comment]
Hello.
- I've tried this:

```
# Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          locale: "en_US"
          format: "%Y-%m-%d"
```
- And I've tried this:

```
# Print the current date
  - trigger: ":ddate"
    replace: "{{myddate}}"
    vars:
      - name: myddate
        type: shell
        params:
          cmd: "date '+%Y-%m-%d'"
```
- The output of the locale command is:
```
locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

- The output of the date +%x command is:
```
date +%x
08/02/2024
```

- I've a spanish keyboard
 Thanks.

**Comment by smeech** [comment]
And do all those have the same problem, i.e. outputting `2024'08'02` on each reboot until you resave `base.yml`?
Also `format: "+x%"`?
Is it any better if you move the trigger to a different `espanso/match/whatever.yml`?

**Comment by witopea** [comment]
I've created whatever.yml.
```
# espanso aditional file by me
matches:
# Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

# Print the current date
  - trigger: ":ddate"
    replace: "{{myddate}}"
    vars:
      - name: myddate
        type: shell
        params:
          cmd: "date '+%Y-%m-%d'"
```
I got the same output.
The issue now is that resaving the whatever.yml or base.yml file doesn't resolve the problem, the date is still being output incorrectly.
Thanks

**Comment by smeech** [comment]
Very odd. I haven't encountered this before.

**Comment by stewcam** [comment]
@witopea What happens if you replace %Y-%m-%d with the ISO 8601 equivalent %F - as in:
```
  - trigger: 'ymd'
    replace: '{{myddate}}'
    vars:
      - name: myddate
        type: date
        params:
          format: '%F'
```
