### ISSUE TITLE
Delay when sending key strokes

### ISSUE THREAD

**Issue by stebberg** [federico-terzi/espanso#2038]
### Description

If I have a windows form with 3 textfields, you can usually fill it out by pressing TAB between the values.
But if I try this in Espanso eg `A\tB\tC` it will all end up in the first (focused) textbox.
In the text expander tool I've been using so far I can insert delays in the snippet, like `A\t(delay 50 ms)B\t(delay 50 ms)C`. Not sure what is going on here but that seems to make Windows to have the time and be able to handle it and actually move focus to the next textbox.

### Motivation

If this wont work you need to have 3 snippets for 1 form.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
Some forms will process the data fast enough for `\t` to move between fields, but others won't, which means you need a separate trigger for each field.

Espanso has no facility to introduce individual delays in the way you have suggested as `replace:` takes place as a single event (believe me, I've tried all sorts of things!), but if the form will work using the `inject` backend, you could try increasing [`inject_delay`](https://espanso.org/docs/configuration/options/) a little.

**Comment by stewcam** [comment]
I have tested the following solution in Windows 11 on MS Forms and it works (but does require PowerShell). I had to add a terminal tab for the C to register in the third edit field.
```
  - trigger: ':fm'
    replace: '{{output}}'
    vars:
      - name: output
        type: script
        params:
          args:
            - C:\Program Files\PowerShell\7\pwsh.exe
            - -Command
            - |
              Add-Type -AssemblyName System.Windows.Forms
              [System.Windows.Forms.SendKeys]::SendWait("{BACKSPACE}{BACKSPACE}{BACKSPACE}A")
              Start-Sleep -Milliseconds 50     
              [System.Windows.Forms.SendKeys]::SendWait("{TAB}")
              Start-Sleep -Milliseconds 50    
              [System.Windows.Forms.SendKeys]::SendWait("B")
              Start-Sleep -Milliseconds 50     
              [System.Windows.Forms.SendKeys]::SendWait("{TAB}")
              Start-Sleep -Milliseconds 50 
              [System.Windows.Forms.SendKeys]::SendWait("C")
              Start-Sleep -Milliseconds 50     
              [System.Windows.Forms.SendKeys]::SendWait("{TAB}")
```

**Comment by smeech** [comment]
I've done similar things with `xdotool` (Linux).
One is abandoning Espanso's text injection and just using it to set off a different key injection process.
My testing is usually in editors, which means such a script has to know the length of the trigger, delete it at the beginning, and supply it at the end for Espanso to remove. E.g.:
```yml
#  Snippet to inject text using xdotool
  - trigger: ":xd"
    replace: "{{output}}" # Redundant placeholder
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            # Remove trigger characters
            xdotool key BackSpace BackSpace BackSpace 
            xdotool type "Some text"
            xdotool key KP_Enter
            sleep 1.5
            xdotool type "Some more text"
            # Supply dummy characters for Espanso to remove
            xdotool key Return type ":xd" 
``` 
and a Python method: https://pastebin.com/AA4Vmx0G

It may be your final `{TAB}` is moving the Espanso delete away from your text input.
#1828
