### ISSUE TITLE
Espanso not working in RStudio

### ISSUE THREAD

**Issue by danielvartan** [federico-terzi/espanso#2049]
### Description

Hi,

I'm trying to get Espanso to work in RStudio, but I'm having no luck.

I've already read all the documentation, including the [App Specific Configurations](https://espanso.org/docs/configuration/app-specific-configurations/) section.

I've also tried all the solutions mentioned in issues #743 and #544.

I experimented with different filter configurations in an `rstudio.yml` file located in the same directory as `default.yml`. You can see the code below. I tried each commented line one step at a time, saving the file and then going to Espanso `Reload config` option.

```yaml
name: "RStudio"
filter_title: "RStudio$"
# filter_exec: "C:/Program Files/RStudio/rstudio.exe"
# filter_exec: 'C:\\Program Files\\RStudio\\rstudio.exe'
# filter_exec: "rstudio.exe$"
# filter_class: "RStudio$"
backend: "Clipboard"
backspace_delay: 12
```

I can't figure out how to make this work. Could someone give me a hand?

### Screenshots

You can see me trying different solutions in the video below.

https://www.loom.com/share/049c7849627643de8598b00028c11010?sid=2313d88b-0e34-4af7-9f4a-95ba4238dce1

### Your environment

- Operating system and version: Windows 11 Home Single Language 23H2
- Espanso version: v2.2.1
- RStudio version: 2024.04.2 Build 764 ("Chocolate Cosmos" Release (e4392fc9, 2024-06-05) for windows)

### Self-service

- [ ] I'd be willing to fix this bug myself.
