### ISSUE TITLE
Add actual placeholders to imports for user and/or home directory similar to %config%

### ISSUE THREAD

**Issue by woerndl** [federico-terzi/espanso#2076]
### Description

If you use Espanso as part of a team with shared expansions it is convenient to import the configs from a shared Dropbox/iCloud etc. folder.

Currently the import has to look like this relative
```
imports:
  - "../../../../Dropbox/
```
or like this absolute
```
imports:
  - "/Users/username/Dropbox/
```

There is already a placeholder for `%CONFIG%` it would be great if there also was one for `%USER%` or `%HOME%`. The [documented examples](https://espanso.org/docs/configuration/basics/) `/Users/$USER` or `$HOME/` both don't work. Using macOS 14.6.1 and Espanso 2.2.1.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
Yes, it would be helpful not to have to use workarounds like:
```yml
global_vars:
  - name: home
    type: script
    params:
      args: [python, -c, print(__import__('os').path.expanduser('~'))]
  - name: home1      
    type: shell
    params:
      cmd: echo $HOME
  - name: user
    type: shell
    params:
      cmd: echo $USER
```
to use in such paths.

**Comment by woerndl** [comment]
Thank you for your response. These workarounds would be a great temporary fix, but it seems variables don’t get replaced in imports.

directly following
```
global_vars:
  - name: home
    type: shell
    params:
      cmd: echo $HOME
  - name: user
    type: shell
    params:
      cmd: echo $USER
```

both
```
imports:
  - "/Users/{{user}}/Dropbox/
```
and
```
imports:
  - "{{home}}/Dropbox/
```
lead to an error message `[ERROR] unable to canonicalize import path: "/Users/{{user}}/` or `"{{home}}/`. Where as 

```
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there! {{user}} and {{home}}"
```

expand as expected. Escaping like `/Users/'{{user}}'/Dropbox/` didn't work either. Am I doing it wrong or was the workaround meant for other cases other than `import`?
