### ISSUE TITLE
Allow to keep the sort order for choice values instead of forcing alphabetical order

### ISSUE THREAD

**Issue by woerndl** [federico-terzi/espanso#2078]
### Description

Currently your own order for choices will be ignored and the results are shown alphabetically:

Example trigger
```
  - trigger: ",me"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - "{{fullname}}"
            - "{{nickname}} {{lastname}}"
            - "{{firstname}}"
            - "{{nickname}}"
```

You can opt to use the label/id syntax and prefix the entries, but this adds unnecessary complexity in cases where users have a preference what the most used option is to them.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.
