### ISSUE TITLE
Add native support for sending keystrokes/keypress (e.g., Tab, Enter, ESC)

### ISSUE THREAD

**Issue by woerndl** [federico-terzi/espanso#2079]
### Description

This might be Espansos most requested feature as it is mentioned in #286 and #637 and briefly touched in #383 and #2038. As well as in [various](https://www.reddit.com/r/espanso/comments/t9eczg/how_to_emulate_a_tab_keypress_so_espanso_can_fill/) [posts](https://www.reddit.com/r/espanso/comments/119ch2x/sending_keystrokes_like_tab_enter/) [on](https://www.reddit.com/r/espanso/comments/10o8g79/can_espanso_convert_a_text_trigger_into_running_a/) [Reddit](https://www.reddit.com/r/espanso/comments/13ut74j/how_to_assign_a_shortcut_key/).

### Motivation

I believe this feature is highly desired because it serves as a crucial core functionality for text replacement tools. Whether it’s an email template with a subject and body, a support form you send 100 times a day (that needs tab + enter), or using a spreadsheet, basic automation is key. While text replacement cannot and should not completely substitute for a full desktop automation tool, it should handle the most basic tasks, such as filling out forms (see example below).

Issues in the past have been closed (recently) because they lost track of the core topic. So I want to raise this again with a clear use case and stress why I think this is so often asked for.

### Alternatives

Super simple use case

https://github.com/user-attachments/assets/3cbb2106-45ba-4cfc-8a2f-62b32cc4170c

What you end up with using Espanso

https://github.com/user-attachments/assets/bed2cd25-99d9-494d-aa18-099ce32d6c8a

Despite options like

```
backend: inject
inject_delay: 100
key_delay: 20
```
(Which would be a subpar option anyway, because you wouldn't want to affect all your snippets)

How the settings look in aText
<img width="887" alt="atext-setting" src="https://github.com/user-attachments/assets/76b659c9-c770-4199-8bdb-e8970cea6f30">

How it could (just a random idea) look in Espanso

```
  - trigger: :plc
    replace: 1010{{tab}}Vienna
    vars:
      - name: tab
        type: key
        params:
          key: TAB
          modifiers: ""
          count: 1
          delay_before: 0
          delay_after: 0
```
In my basic example you wouldn't need modifiers, counts or delays (just to show the possible options). But I'd argue these options would cover +95% of the most common use cases. This way you can send key combinations, wait, type something and send another combination. I don't think it should be a var, I just wanted to show what I meant, maybe a own syntax like ((key)) would make more sense.

```
  - trigger: :plc
    replace: 1010((tab))Vienna((shift_enter))
    keys:
      - name: tab
        type: key
        params:
          key: TAB
          delay_before: 20
     - name: shift_enter
        type: keyseq
        params:
          key: ENTER
          modifiers: SHIFT
          delay_before: 50
```

The differentiation into key and keyseq might even be unnecessary as you could repeat keys and key combinations already very flexible this way. Snippets that use keys would always use the Inject backend. So in this example '1010' and 'Vienna' are also sent as keystrokes. For a version 2.0 of this feature a combination with the clipboard backend could be thought of as this might get unstable for long injections (e.g. whole email templates).

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
Tabs `\t` and enter `\n` or `\r` can be injected, but many forms require a momentary delay. I agree, this is a much requested feature.

**Comment by grepinsight** [comment]
Thank you for thread. If we can send the combination of keystrokes such as 'Cmd + Enter', that'd be very nice

**Comment by berot3** [comment]
@smeech would this python script also allow adding delays? #286 

do you have examples?

thanks a lot!

**Comment by smeech** [comment]
> @smeech would this python script also allow adding delays? https://github.com/espanso/espanso/issues/286

I'm not sure to which script you're referring.

I would point you to https://pastebin.com/c4QHdnc8 and https://pastebin.com/KKX8GPzD, which implement delays and injection of other keyboard events. If you want to use `xdotool` there's https://pastebin.com/AA4Vmx0G, but I haven't worked it to the same level of detail.

Let me know if you need help with any of them.

**Comment by smeech** [comment]
Just remembered - I put the first two into a [package](https://github.com/espanso/hub/tree/main/packages/delays-characters/0.1.0), although I can't find it in the [Hub](https://hub.espanso.org/). `espanso package install delays-characters` should load it.

**Comment by rnoennig** [comment]
> Just remembered - I put the first two into a [package](https://github.com/espanso/hub/tree/main/packages/delays-characters/0.1.0), although I can't find it in the [Hub](https://hub.espanso.org/). `espanso package install delays-characters` should load it.

Thanks for this hint, I got it working! I had to update my espanso to be able to install this package. I also had to install the pynput library via
`/Library/Developer/CommandLineTools/usr/bin/pip3 install pynput`

I added the following to my `/Users/rnoennig/Library/Application Support/espanso/match/base.yml`:

```yaml
    - trigger: ":lg"
    replace: "{{Output}}"
    vars:
      - name: Trig
        type: echo
        params:
          echo: :lg
      - name: Input
        type: echo
        params:
          echo: |
            sleep 1
            type Liebe Grüße
            press shift
            tap enter
            release shift
            type Robert
      - name: Output
        type: script
        params:
          args:
            - python3
            - '%CONFIG%/packages/delays-characters/parse_pynput.py' 
            - '{{Trig}}'
            - '{{Input}}'
```

Note that I had to add the "sleep 1" otherwise the backspace key triggers to remove the typed trigger text would be executed later than the automatically typed text. Also I had to change the path to the parse_pynput.py as it wasn't installed in the match directory as the example in the hub indicates.
