### ISSUE TITLE
Investigate why `script` launches commands faster than `shell` on macOS and Windows

### ISSUE THREAD

**Issue by woerndl** [federico-terzi/espanso#2086]
### Description

As discovered through https://github.com/espanso/espanso/issues/1612#issuecomment-2380593095, it is evident that commands run via `script` execute considerably faster than `shell` on macOS, and possibly on Windows as well. As @kpym who made the comment is on Windows, and I was able to replicate the situation on macOS.

### Steps to reproduce

Define the following:

```yaml
global_vars:
  - name: "clipboard"
  type: "clipboard"

  - name: "shellcb"
    type: shell
    params:
      cmd: pbpaste # Replace with gclip on Windows

  - name: "scriptcb"
    type: script
    params:
      args:
        - pbpaste # Replace with gclip on Windows
        
matches:
  - trigger: ":cb"
    replace: "{{clipboard}}"

  - trigger: ":shell"
    replace: "{{shellcb}}"

  - trigger: ":script"
    replace: "{{scriptcb}}"
```

### Expected behavior

On Windows and macOS you should see `script` performing considerably faster. If this is expected behavior it would make sense to document that behavior. But possibly there are also performance improvements for Windows and macOS users to be made. @smeech tried to replicate the situation on Linux, but was not able to reproduce this, but found the opposite effect with `script` being roughly 5% slower on his system.

### Screenshots

Result: It feels even more noticeable live because the `script` variant almost happens immediately.

https://github.com/user-attachments/assets/22927eea-0053-4406-9416-4fcc95815514

### Your environment

- MacBook Air M2
- macOS 14.6.1
- Espanso version v2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.
