### ISSUE TITLE
backend: Clipboard makes replacing `doesnt ` with `doesn't ` (notice the last space) to open a new tab on Firefox 

### ISSUE THREAD

**Issue by moshpirit** [federico-terzi/espanso#2109]
### Description

I have this replacement:
```yaml
  - trigger: "doesnt"
    replace: "doesn't"
    propagate_case: true
```
But when I type `doesnt ` (fast typing with a space at the end), it replaces the word, but also opens a new tab. I noticed that this is due to the `backend: Clipboard` setting; and disabling it makes it go away (since <C-t> opens a new tab on Firefox); but we can't have that functionality.

I'm using the latest version on Arch Linux.

### Self-service

- [ ] I'd be willing to fix this bug myself.
