### ISSUE TITLE
Injections don't work consistently on Roblox macOS

### ISSUE THREAD

**Issue by MoltenMonster** [federico-terzi/espanso#2112]
### Description

My trigger "Hit ready to skip the timer" doesn't work consistently in Roblox, it either adds an r before it (rHit), or stops at "th". I found clipboard to work better but still has errors sometimes.

### Steps to reproduce

Add this trigger
```yml
  - trigger: "tdsr"
    replace: "Hit ready to skip the timer"
    force_mode: clipboard
```

- Open a Roblox game and press `/` to open the chat box
- type the trigger (`tdsr`) 5-10 times to test it
- Change `force_mode` to `keys` and do it again

### Your environment

- Operating system and version (e.g., Ubuntu 20.04.2 LTS): macOS 15.1 (non-beta)
- Espanso version (e.g., 2.1.4-beta): espanso 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.
