### ISSUE TITLE
Additons to https://github.com/espanso/espanso/blob/dev/schemas/match.schema.json

### ISSUE THREAD

**Issue by smeech** [federico-terzi/espanso#2122]
### Description

Would you kindly add:

- [x] `imports:`
- [x] `anchors:`
- [x] `trim:`
- [x] `anchor:`
- [x] `search_terms:`

To https://github.com/espanso/espanso/blob/dev/schemas/match.schema.json

Additionally: 
![image](https://github.com/user-attachments/assets/f12e482c-f004-4f8c-9453-cb808edfe052)

```
      - name: output
        type: choice
        params:
          values:
            - one    `Incorrect type. Expected "object."`
```            
### Screenshots

![image](https://github.com/user-attachments/assets/25356f83-9072-47fb-a078-2b9dbdde3caf)

Examples picked from the documentation.

`anchors:` and `anchor:` are arbitrary names but worth including as such. `anchors:` need not be unique if you have any control over that.

**Comment by AucaCoyan** [comment]
Yup! I'll do it after the rework of the CI (making the workflow of SignPath work)

**Comment by smeech** [comment]
Not sure where to post this now you've closed this Issue.

Can you allow arbitrary keys following the `form_fields:` heading, as in:
```yml
  - trigger: \ao3ip
    form: "Currently @ Chapter [[chapnum]] (In Progress)"
    form_fields:
      chapnum:            # "Property chapnum is not allowed"
        default: "1"
```
?

Also allow:
```yml
    replace: null         # "Incorrect type. Expected "string".
```
