### ISSUE TITLE
Add Rich Text matches

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#214]
Many users requested this feature, which would make espanso capable of expanding rich text (text with formatting, such as bold, center, italic, images).

A typical use case would be in email signatures.

**Comment by lyonsinbeta** [comment]
I don't know if you're interested in ideas around this, but if you are... I was thinking a "markdown" type might be a way to do this with plaintext YAML. Essentially, strings of type "markdown" could be processed before being inserted. Making markdown a type prevents every string from being needlessly processed too.

Mocked up example:

![espanso-markdown](https://user-images.githubusercontent.com/1192380/95249506-05678c00-07d6-11eb-873a-022da43ced6e.png)

**Comment by pseudomichael** [comment]
I second a request for Markdown processing support for rich text!

**Comment by federico-terzi** [comment]
@lyonsinbeta @pseudomichael I was thinking about HTML, but indeed markdown would be better for the user. We'll probably end up supporting both, as we need to copy HTML content in the clipboard, so we need a markdown to HTML compiler for Rust (which luckily, seems to exist: https://github.com/johannhof/markdown.rs)

Given the interest, I'll move this issue up in priority, so that hopefully we get a POC in the next release :)

**Comment by federico-terzi** [comment]
Experimental support coming in the next release!

![richtext2](https://user-images.githubusercontent.com/20475953/96773832-69e53680-13e5-11eb-9e0b-47b7bc3b287e.gif)

You'll be able to specify the rich text both as markdown and HTML as you suggested:

```yaml
  - trigger: ":rich"
    markdown: "This *text* is **very rich**!"
  
  - trigger: ":ric2"
    html: '<p>But <span style="color: #ce181e;"><span style="font-size: x-large;">this</span></span> one is <span style="color: #81d41a;"><span style="font-family: Arial, sans-serif;">even richer</span></span>!</p>'
```

Cheers :)
