### ISSUE TITLE
In `Commet` only the last character of the trigger is removed when typing fast

### ISSUE THREAD

**Issue by sphh** [federico-terzi/espanso#2160]
### Description

In the [Commet chat application](https://github.com/commetchat/commet) (v0.3.0) the trigger is sometimes removed and sometimes only the last character of the trigger is removed.

(In other applications espanso works as expected.)

### Steps to reproduce

1. In the text input field type your trigger _slowly_:
    - The complete trigger is removed and the replacement term inserted.
2. Type the trigger _fast_ (it is enough to type the last two characters of the trigger fast):
    - Only the last character of the trigger is removed.
3. Add the following configuration to espanso:
    ```yaml
    filter_class: "Commet"
    key_delay: 100
    ```
4. Still only the last character of the trigger gets removed, if the last two characters are typed _fast_.

### Expected behavior

The whole trigger term should get removed, even if the two last characters are typed fast.

### Your environment

- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Linux Mint 22 Cinnamon
- Espanso version (e.g., 2.1.4-beta): 2.2.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
I'm not familiar with Commet (or any of the other Matrix clients, frankly), but as I'm using Linux Mint 21.2 I'll attach my general configuration, which works in most situations, so you can compare. Unfortunately, GitHub won't allow a YML-suffixed file upload, so you may wish to rename it to benefit from syntax highlighting. 
[general_acfg.txt](https://github.com/user-attachments/files/17961036/general_acfg.txt)

Normally I'd download the problematic application to try it here, but I think compiling Commet is probably a step too far. If necessary, I could install Element or Cinny in case that helps.

I agree, increasing `key_delay:` is the first thing to try so it's disappointing that hasn't helped. It may be worth experimenting with higher figures, but eventually you'll be irritated by the delay! Online applications, like browsers, and chat programs are often problematic as there's so much going on behind the scenes, compared with local text editors and terminals.

Let me know how you get on.

Linux Mint Linux Mint 21.2 x86_64, Xfce.

**Comment by sphh** [comment]
There are some pre-compiled options available in [Comment's release page](https://github.com/commetchat/commet/releases), but I have no idea, if any of that suits you.

I had a look through your configuration. IMHO these are the only changes from the default values (I added the default values as comments):
```yaml
paste_shortcut: None              # Ctrl-V, but many built-in patches change this behaviour
inject_delay: None                # Between 0 and 1, depending on the platform and application.
key_delay: None                   # Between 0 and 1, depending on the platform and application.
pre_paste_delay: 100              # 300
toggle_key: Some(Alt)             # OFF
search_trigger: Some("#search#")  # off
search_shortcut: Some("ALT+SHIFT+SPACE")  # ALT+Space
keyboard_layout: None             # { layout: us }, only for Wayland
secure_input_notification: true   # ?

x11_use_xclip_backend: true       # false
```

I thus added
```yaml
pre_paste_delay: 100
x11_use_xclip_backend: true
```
to my app-specific configuration file. Still no luck.

I also increased `key_delay` to `300` and `1000`, which did nothing to improve the situation.

**Comment by smeech** [comment]
There's a Flatpak v0.2.1, which should be easy enough to remove afterwards.

Is that likely to be recent enough to help you with?

**Comment by sphh** [comment]
In https://github.com/commetchat/commet/releases/tag/v0.3.0, there is a Flatpak v0.3.0, a linux portable and two Debian packages for Ubuntu to chose from. I have the Ubuntu package installed.

**Comment by smeech** [comment]
I've installed the latter, and the results are quite variable, perhaps depending on network traffic - if you start typing with `@`, `:`, `/` etc., the display at the bottom changes with suggestions, for example, so there's probably an ongoing dialogue with the server for each character. Even typing slowly, I'm often left with a character or two from the beginning of the trigger, so the deletion process isn't working reliably all the time.

I find `backend: clipboard` largely prevents the jumbling up of the replacement text, but other options I've tried don't make much difference (apart from slowing the process), so I'm left with:

```yml
filter_class: Commet
backend: clipboard
# key_delay: 10
# inject_delay: 10
# pre_paste_delay: 600
# disable_x11_fast_inject: true
# x11_use_xclip_backend: false
# x11_use_xdotool_backend: true
```
I think you may have to make further delay tweaks to suit your own setup and connection speeds, but the above are the obvious ones to try. We see similar issues with browser URL bars trying to be helpful! I couldn't find anything useful in Commet's own settings, unfortunately.

It's unlikely that Espanso is going to be modified specifically for this problem, I'm afraid, but I'll leave the Issue up for others to comment.
