### ISSUE TITLE
Open match file with default editor from sys tray icon

### ISSUE THREAD

**Issue by Zaldor** [federico-terzi/espanso#2167]
### Description

I believe it would be nice if the sys tray icon menu had an option for opening the config file with default editor

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
One of the advantages of Linux _not_ having an icon is that I have set one up with any items I like! To be honest, I rarely touch my `config` file, although a facility to open various `match` files etc. could be useful.

**Comment by Zaldor** [comment]
sorry I wrote config but I actually meant Match, on windows the system tray menu was the first thought but could also be an option from the search window

**Comment by smeech** [comment]
Ah, thanks. Mind you, I currently have five active `match` files!

I've renamed the Issue.

**Comment by smeech** [comment]
It's easy to add an item to the search window, fortunately, e.g.:
```yml
  - trigger: '#edit#'
    replace: '{{output}}'
    label: espanso edit
    vars:
      - name: output
        type: shell
        params:
          cmd: xfce4-terminal -e 'espanso edit'
```
although it's very system-specific, and you'll have to type something into the search bar (e.g. "edit"). I've not found a way of adding to the Espanso ">" search bar command list.

Sorry - with the pace of development of Espanso and the priorities such as fixing bugs, I'm accustomed to finding workarounds for user problems. I'm not denigrating your suggested enhancement!
