### ISSUE TITLE
filter_title not filtering

### ISSUE THREAD

**Issue by joemurphy3902** [federico-terzi/espanso#2178]
### Description

filter_title is not filtering on MacOS 15.0.1, espanso 2.2.1. it still replaces in every window/application

### Steps to reproduce

1. create config file called /Users/joe/Library/Application Support/espanso/match/p.yml
add this. every application i open it replaces 'test' with 'testing'

```yaml
filter_title: "py"
matches:
  - trigger: "test"
    replace: "testing"
```

### Expected behavior

i expect it only to change with py in the title

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
Have another look at https://espanso.org/docs/configuration/include-and-exclude/

A filter of this sort needs _two_ files. 

In espanso/config:
```yml
filter_title: "py"
extra_includes:
  - "../match/_py.yml"
  ```
and in espanso/match, a file, `_py.yml`, containing:
```yml
matches:
  - trigger: "test"
    replace: "testing"
``` 
If you're still having problems, use [`filter_class:`](https://espanso.org/docs/configuration/app-specific-configurations/#filters) preferably, or `filter_exec:`. Check [`#detect#`](https://espanso.org/docs/configuration/app-specific-configurations/#finding-the-right-filters) in your `py` program.
