### ISSUE TITLE
`espanso match list` duplicates info if a `label` is used in a match

### ISSUE THREAD

**Issue by AucaCoyan** [federico-terzi/espanso#2181]
### Description

I found if you do this:
```yaml
  - trigger: "sometrigger."
    label: somelabel
    replace: "result1"
  - trigger: "another-trigger"
    label: qwerty
    replace: "some result"
```

and you do
```bash
espanso match list
```

it returns
```
sometrigger. - somelabel - somelabel
another-trigger - qwerty - qwerty
... (your other matches)
```

(dobles the tag, instead of the replacement)

is caused by [this function here](https://github.com/espanso/espanso/blob/78c1be643ba6169e01c0995b8fec3ce6f583037e/espanso/src/cli/match_cli/list.rs#L52) that calls [this method](https://github.com/espanso/espanso/blob/78c1be643ba6169e01c0995b8fec3ce6f583037e/espanso-config/src/matches/mod.rs#L55) and raises this bug

### Your environment

- dev branch, regardless of the OS

### Self-service

- [X] I'd be willing to fix this bug myself.
