### ISSUE TITLE
Default options for matches

### ISSUE THREAD

**Issue by AlbatorLaho** [federico-terzi/espanso#2185]
### Description

There could/should be a way to have shared options (per-file or globally maybe) that are shared across all matches. e.g.
```yaml
matches:
  - trigger: "a"
    replace: "something"
    propagate_case: true
    word: true
  - trigger: "b"
    replace: "something else"
    propagate_case: true
    word: true
```
could be simplified to:
```yaml
global_options:
  propagate_case: true
  word: true
matches:
  - trigger: "a"
    replace: "something"
  - trigger: "b"
    replace: "something else"
```

Possible other names I can think of instead of `global_options` are `global_match_options` and `shared_match_options`.
Or maybe do something like this?
```yaml
matches:
  defaults:
    propagate_case: true
    word: true
```
But I don't think that would really work? I'm not super familiar with how Yaml is parsed...

### Motivation

Writing a bunch of matches with a lot of the same options can get really messy/verbose/complex.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.
