### ISSUE TITLE
Add "time zone" parameter to date extension

### ISSUE THREAD

**Issue by flypenguin** [federico-terzi/espanso#2225]
### Description

I am migrating from my proprietary and non-cross-platform text expander, and the _one_ thing espanso is missing is this: A timezone setting for the `date` extension. 

I imagine sth like this:

```yaml
# "utc timestamp" 
- trigger: :utc-ts
  replace: "{{date}}"
  vars:
    - name: date
      type: date
      params:
        format: "%Y-%m-%dT%H:%M:%SZ"
        tz: UTC   # <-- this is the new thing ...
```

### Motivation

Use case: I sometimes want/need to create UTC time stamps, and this seems, as of now, not possible with espanso.

### Alternatives

as far as I can see ... writing a script which does that, and executing it.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.
