### ISSUE TITLE
Form height not expandable

### ISSUE THREAD

**Issue by srmippili** [federico-terzi/espanso#2234]
### Description

I find lot of problem with form height. I see that the form height is something we are not able to set from code. Could you please add this too. Width is Auto adjusted, which is good. But the height is too small and we need to scroll a lot. Not able to see large area in single view.

This is very much needed .please

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
The repo includes a commit, https://github.com/espanso/espanso/pull/1991, which introduces a couple of keywords to constrain the width and height of forms, but doesn't facilitate increasing the height, AFAICS.

One day it'll make its way into a Release.

**Comment by srmippili** [comment]
> The repo includes a commit, [#1991](https://github.com/espanso/espanso/pull/1991), which introduces a couple of keywords to constrain the width and height of forms, but doesn't facilitate increasing the height, AFAICS.
> 
> One day it'll make its way into a Release.

This doesn't allow increasing the height. This is only for limiting the height. Can you see some way out. I am trying to display a list of files, it just shows me only 5 to 6 files in small view, and I have to scroll a lot

Probably adding min_form_height needed to the existing max options

**Comment by smeech** [comment]
I agree, it doesn't. 

There are ways of showing as many of your items as your screen will allow - see this [Reddit](https://www.reddit.com/r/espanso/comments/1i2tqtr/can_the_expansion_dropdown_box_be_stretched_to/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) discussion.

**Comment by srmippili** [comment]
> I agree, it doesn't.
> 
> There are ways of showing as many of your items as your screen will allow - see this [Reddit](https://www.reddit.com/r/espanso/comments/1i2tqtr/can_the_expansion_dropdown_box_be_stretched_to/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) discussion.

@smeech thanks for your quick reply.
I am trying below, it's not displaying anything beyond 9 lines under the array variable, unless i scroll to it. Can you please help. Your suggestion from reddit also has the same problem. It will show only 9 items at a time under the array. Need to scroll down

```yml
  - trigger: ":tstfrm"  
    replace: "{{select}}"
    vars:
      - name: form1
        type: form
        params:
          layout: |
            Select ref:
            [[ref]]
            "0000"
          fields:
            ref:
              type: list
              multiline: true 
              values: |
                "1000"
                "2000"
                "3000"
                "4000"
                "5000"
                "6000"
                "7000"
                "8000"
                "9000"
                "9100"
                "9200"
                "9300"
                "9400"
              default: "9400"
      - name: select
        type: shell
        params:
          cmd: echo {{form1.ref}}
```
