### ISSUE TITLE
Choice labels and IDs don't work when using controls with the verbose syntax

### ISSUE THREAD

**Issue by ghost** [federico-terzi/espanso#2264]
### Description

Choice extension with labels and IDs renders an empty control in the dialog box (see screenshots below). However, using regular list items works as expected.

### Steps to reproduce

```yml
matches:
  - trigger: ;test
    replace: "{{output}}"
    vars:
      - name: input
        type: form
        params:
          layout: |
            Param 1: [[param_1]]
            Param 2: [[param_2]]
          fields:
            param_1:
              type: text
            param_2:
              type: choice
              values:
                # Doesn't work
                - label: Value A
                  id: value-a
                - label: Value B
                  id: value-b
                # Works
                # - value-a
                # - value-b
      - name: output
        type: script
        params:
          args:
            - node
            - -e
            - 'console.log("Param 1: {{input.param_1}}; Param 2: {{input.param_2}}")'
```

### Expected behavior

The `fields` parameter content to follow the same format as the `form_fields` parameter.

### Screenshots

With labels and IDs

![Image](https://github.com/user-attachments/assets/a887186c-56cd-48f5-9662-87ca3a9eee11)

With regular list items

![Image](https://github.com/user-attachments/assets/b0ccb4b8-3363-4646-9baf-f5659f6136d2)

### Your environment

- Operating system and version: **macOS 15.3.2**
- Espanso version: **2.2.1**

### Self-service

- [ ] I'd be willing to fix this bug myself.
