### ISSUE TITLE
Apply trigger to highlighted text

### ISSUE THREAD

**Issue by charityreed** [federico-terzi/espanso#2315]
### Description

I would like to be able to highlight text and then bring up the search bar and apply a trigger to it. This would be particularly useful for regex matches with named groups (and possibly other things).

Trigger example (this trigger replaces letters on either side of equals signs with the letters and a non-breaking space on either side of the equals sign): 

```
- regex: (?i)(?P<pre>[A-z]+[\s|\xA0]?)=(?P<post>[\s|\xA0]?[A-z]+)
  replace: "{{pre}}\u00A0=\u00A0{{post}}"
```
Basic process would look like:

1. copy and paste the text you want to apply the trigger to
2. highlight the text
3. bring up the espanso search bar
4. find the trigger you want to use
5. hit ALT+# for the trigger you want to use 
6. it would apply the trigger to the text that you have currently highlighted

Let me know if more detail is needed. I honestly don't know enough to know if this possible

### Motivation

This would be useful if you had to copy and paste something and want to apply the trigger to what you copied and pasted. 

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by AucaCoyan** [comment]
Mmmmmm...
I think it really really difficult to do without reworking espanso entirely. The problem I see is that espanso is based on keystrokes, so applying a trigger over highligted text is difficult. I have no idea how can we recover selected text from the screen, and I assume it's going to be program-dependent, but imagine if we can... What if multiple selections in different windows happen?

The end goal would be something like:
1. see a text you want to apply a transformation
2. copy the text to clipboard
3. ...
4. run a trigger over the text (possibly directly from the clipboard)
5. and then paste the text

I think there is no need to concentrate on the highligting. If we can achieve modifying the clipboard with a trigger and then paste it, we would solve the issue and there is no need to go and search what is selected on screen (which requires a whole lot of protocol analysis if it's even possible).

If I'm not mistaken, this numbered process could be done with a python script in the current version of espanso 🤔 .

**Comment by smeech** [comment]
It's fairly simple to script the process for this particular use-case. The example in this [Gist](https://gist.github.com/smeech/40d1624aeece330bb268040d6cdd45cc#file-clipman-yml) uses the `shell` extension to demonstrate various transformations to copied text, and could easily be converted to another scripting language like Python. Importantly, this also gets around Espanso's limitation on the length of Regex triggers.

In your case:
```yml
  - trigger: :test
    replace: '{{output}}'
    vars:
      - name: clipb
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python
            - -c
            - print("\u00A0=\u00A0".join("{{clipb}}".split("=")))
```
If you're in Linux, `sed` in a Bash `shell` command 
`cmd: echo "{{clipb}}" | sed 's/=/ = /'`
where each space around the = is actually a non-breaking space, would probably be faster, as would a Bash `printf` command: 
`cmd: eval 'str="{{clipb}}"; printf "%s\u00A0=\u00A0%s\n" "${str%%=*}" "${str#*=}"'`.
Windows PowerShell has equivalents:
```yml
      - name: output
        type: shell
        params:
          shell: pwsh
          cmd: |
            $parts = "{{clipb}}" -split '='
            "$($parts[0])$([char]0x00A0)=$([char]0x00A0)$($parts[1])"
```

**Comment by AucaCoyan** [comment]
Thank you smeech!

**Comment by charityreed** [comment]
Thanks so much for this. I tried the one you posted for powershell and got an error. The trigger i made is:
```
  - trigger: :test
    replace: '{{output}}'
    vars: 
      - name: clipb
        type: clipboard
      - name: output
        type: shell
        params:
            shell: pwsh
            cmd: |
                $parts = "{{clipb}}" -split '='
                "$($parts[0])$([char]0x00A0)=$([char]0x00A0)$($parts[1])"
```
and the log says:
```
09:59:50 [worker(22384)] [WARN] extension 'shell' on var: 'output' reported an error: could not execute command: '`$parts = "ddkfsdkl =sjflksd" -split '='
"$($parts[0])$([char]0x00A0)=$([char]0x00A0)$($parts[1])"
`', error: '`program not found`'
09:59:50 [worker(22384)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute command: '`$parts = "ddkfsdkl =sjflksd" -split '='
    "$($parts[0])$([char]0x00A0)=$([char]0x00A0)$($parts[1])"
    `', error: '`program not found`'
```
I copied the following into my clipboard: `ddkfsdkl =sjflksd` and then typed `:test` and that's when the error occurred.
