### ISSUE TITLE
IDs Doesn't Work With Forms

### ISSUE THREAD

**Issue by CemCanplt** [federico-terzi/espanso#2320]
### Description

Hello, I am kinda a newbie about reporting bugs and Espanso, so I am sorry if I do something wrong. 
I am gonna keep it simple, when I use the expamle on the website about ids, it works.

```
matches:
  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - label: "Every moment is a fresh beginning."
              id: "bar"
            - label: "Everything you can imagine is real."
              id: "foo"
            - label: "Whatever you do, do it well."
              id: "foobar"
```

but if I combine ids with forms, it does not...
(this is my personal script)

```
# Join Column Temelli
  - triggers: [":@joinc", ":@JoinC", ":@joinC", ":@Joinc"]
    replace: |
      @{{form.akis_yonu}}(cascade = {{form.cascade_type}}{{form.mapped_by}})
      @JoinColumn(name = "")
    vars:
      - name: form
        type: form
        params:
          layout: |
            Akış yönü nedir?
            [[akis_yonu]]

            Cascade tipi nedir?
            [[cascade_type]]

            Mapped By (isteğe bağlı) nedir?
            [[mapped_by]]
          fields:
            akis_yonu:
              type: choice
              default: "[AKIS_YONU]"
              values:
                - "[AKIS_YONU]"
                - "OneToMany"
                - "ManyToOne"
                - "OneToOne"
                - "ManyToMany"
            cascade_type:
              type: choice
              default: "[CASCADE_TYPE]"
              values:
                - "[CASCADE_TYPE]"
                - "CascadeType.ALL"
                - "CascadeType.PERSIST"
                - "CascadeType.MERGE"
                - "CascadeType.REFRESH"
                - "CascadeType.REMOVE"
                - "CascadeType.DETACH"
            mapped_by:
              type: choice
              default: ""
              values:
                - label: "Hayır"
                  Id: ""
                - label: "Evet"
                  Id: ', mappedBy = `""'
```

I should have seen Evet and Hayır options (Yes and No in Turkish) and in theory I should have been able to use this Yes or No to decide weather I'd like to inject mappedBy = "" or not.

But I see no options when it comes to mapped by.
![Image](https://github.com/user-attachments/assets/d58dc9d0-3d04-4cac-b24f-b150adfcdff2)

In addition, I would like to say that a "checkbox" mechanic would suit the Espanso application very well as a type alternative.

Also, for example, if I specify a type as choice in an expression and none of the choices work for me, it would be much better if I could enter the input myself. I wanted to say this in case a developer sees it.

### Steps to reproduce

- Done it inside the Description section 

### Expected behavior

- Being able to see Yes and No and by selecting them adding some code to my "replace" section.

### Screenshots

- Added

### Logs

- No logs

### Your environment

- Public source code:
- Environment name and version (In Every Environment):
- Operating system and version (Windows 11):
- Espanso version (2.2.3):

### Self-service

- [ ] I'd be willing to fix this bug myself.
