### ISSUE TITLE
Python script with regex variable not working

### ISSUE THREAD

**Issue by deefrawley** [federico-terzi/espanso#2329]
### Description

I'm not sure if this is a regex variable issue or python argument issue. I have a python script that works on the command line like so
`python C:\scripts\ticket.py -s --project "my project" --issue_id 1234`
This creates a single line of output using print statements to the console. I want to include this output in emails and messages so I have created in Espanso

```
- regex ":ticket(?P<issue>\\d{4})"
  replace: "{{output}}"
  vars:
    - name: output
      type: script
      params:
        args:
          - python
          - C:\scripts\ticket.py
          - -s
          - --project
          - 'my project'
          - --issue_id
          - '{{issue}}'
```
but I cannot get this to work, the script doesn't seem to accept the last argument and exists with status 2. I have tried removing the single quotes from {{issue}} and have also tried using $ESPANSO_ISSUE with no luck
Is this an issue or something Espanso isn't able to handle yet?
Thanks

### Your environment

- Operating system and version: WIndows 11 latest updates as at May 2025
- Espanso version: 2.2.3

### Self-service

- [ ] I'd be willing to fix this bug myself.
