### ISSUE TITLE
Two wrong text expansions in wayland

### ISSUE THREAD

**Issue by Masacroso** [federico-terzi/espanso#2347]
### Description

The following expansions doesn't work as expected under wayland with a spanish keyboard layout:

```
  - trigger: Sgg
    replace: "\\Sigma "
  - trigger: "sup{"
    replace: \sup\{ $|$ \}
```

The first expansion does `\SIGMA ` when done the first time, and it does the correct expansion `\Sigma ` doing it a second time. Third time is as the first, and so on. It seems that, for some reason, `Sgg` activates caplocks and deactivate it. This is related to the letter `S` as I have another expansions as `Ogg` to expand to `\Omega ` that works correctly, and `Bgg` that expands correctly to `\Beta `.

The second expansion is very weird, it does `\ß↓þ\{  \}` every time I press `sup{` (the correct expansion must be `\sup\{ \}`). These expansions work correctly in X11. In the default config file I have the following options:

```
undo_backspace: false
search_trigger: off
search_shortcut: off
toggle_key: ALT
keyboard_layout:
  layout: "es"
  variant: "nodeadkeys"
```

I don't know if this is fixable right now or its a known bug on wayland.
