### ISSUE TITLE
Feature Request: Repeat Last Expansion

### ISSUE THREAD

**Issue by praxder** [federico-terzi/espanso#2350]
### Description

I recently started using this utility and absolutely love it! Thanks for the amazing app.

I would love a feature to repeat the last expansion. Most of my matches start with ":" and so I would love a feature where typing something like "::" would repeat pasting the last match.

### Motivation

I have multiple matches that use Forms, and oftentimes after pasting the value once, I end up needing to paste the exact same thing again (for me it's mostly complicated/long bash commands). To repeat it currently, from my understanding, the options are:
- Change the espanso backend to be Clipboard, and then also turn-off the `preserve_clipboard` config option. That makes it so that after expanding once, you can simply hit CTRL-V again. But this approach has some drawbacks, including:
   - It overrides your clipboard history
   - You _have_ to use the Clipboard backend, when some apps / use cases need the Inject backend
- Select the text with your mouse, CTRL-C, CTRL-V
- Trigger match again, and again fill out the form fields with the same values as before

I'm currently doing option 1, but it does have some significant drawbacks as mentioned above. 

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
It's an interesting suggestion. However, it's a narrow use-case and, I fear, unlikely to be implemented given the small number of devs and their current workload.

There's a reasonably simple, scripted workaround:
```yml
  - trigger: "::"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat /tmp/espanso_last"

  - trigger: :test
    replace: "{{output}}"
    vars:
    - name: output1
      type: form
      params:
        layout: |
          Form field1: [[form1]]
          Form field2: [[form2]]
    - name: output
      type: shell
      params:
        cmd: printf 'Form field1 = %s\nForm field2 = %s\n' "{{output1.form1}}" "{{output1.form2}}" | tee /tmp/espanso_last
```
It does require setting the output format in the shell `cmd: printf...` line, and adding a version of the last four lines to every trigger, though. If the format is the same between triggers, it works as a global variable.

Let me know if you need it in another language. The above will work on Linux, probably macOS, and Windows with WSL (add a `shell: wsl` line), but you might prefer PowerShell for the latter, or Python for cross-OS compatibility.

I'll mark the issue as "Low Priority" for now, and you may find one of the devs closes it, I'm afraid.
