### ISSUE TITLE
Nested match not working on regex triggers

### ISSUE THREAD

**Issue by srmippili** [federico-terzi/espanso#2351]
### Description

@smeech - last time you helped me one one solution. Hoping for this. 

Need some help here. Please . Since it's regex one, I have many other ways to use it with much more smaller shortcuts created for other matches. 

So trying to see if any solution here.

Thanks 

### Steps to reproduce

I have a regex triggers like this
```yml
  - regex: :op/(?P<input>.*)/
    replace: Xxxxx{{input}} # (I run some cmd based on regex input and get this output)
```

Some of my sample trigger for above which I use frequently :op/dsm_vik,dsm_gl/
I am trying to create a short trigger for this frequently used trigger.

Trying to trigger it from nested match
```yml
  - trigger: :ld 
    replace: "{{output}}"
    vars:
      - name: output
        type: match
        params: 
          trigger: :op/dsm_vik,dsm_gl/
```

It's giving error and says 
Error: unable to find sub-match: output
Caused by missing sub-match

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
I have taken the liberty of formatting your code above so that we can all see how it should appear. If you click the three dots to the top right, and select "edit" you'll be able to see what I added.

I'm afraid, however, the [nested match](https://espanso.org/docs/matches/basics/#nested-matches) facility only invokes named plain triggers, and can't be used with regex triggers where the input will vary with each call. This is partly because plain triggers are all indexed at Espanso restart, but regexes are not, but matched individually during typing (which probably explains why they can perform less well). This is probably why the command `espanso match exec` also doesn't work with regex triggers. I've double-checked with [DeepWiki](https://deepwiki.com/search/is-it-possible-invoke-a-regex_1bbc401c-57e0-4a18-93ff-8f5b2f5d3a38), which initially disagreed with me, but eventually comes up with a logical explanation confirming my supposition.

You've not specified your OS, but to try and work around the problem, I've done some experimentation using `xdotool` to type the `regex:` trigger phrase. Although the command works at the command-line, and successfully invokes the `:op/.../` trigger, it won't work from an Espanso `shell` or `script` trigger, presumably because, apart from nested matches, Espanso will only handle one trigger at a time.

As this is a frequently used trigger of yours, you'll have to set it out in full, and not rely on the regex pathway, although you could use a global variable instead of the latter if you'll be using it for several triggers.

```yml
global_vars:
  - name: glob_output1
    type: echo
    params:
      echo: Xxxxx{{input}}

matches:
  - regex: :op/(?P<input>.*)/
    replace: "{{glob_output1}}"

  - trigger: :ld 
    replace: "{{glob_output1}}"
    vars:
      - name: input
        type: echo
        params: 
          echo: dsm_vik,dsm_gl
```

I'll mark this as an enhancement, but as there's a simple alternative, and unless it gains some traction, it's not likely to be a high priority, I'm afraid, so you might choose to close the Issue.
