### ISSUE TITLE
Expansion does not match applicable font size in Microsoft Word

### ISSUE THREAD

**Issue by flimofly** [federico-terzi/espanso#2355]
### Description

When expanding a Markdown or HTML form in Microsoft Word, the font size of the resulting snippet is too large (12pt instead of the 11pt paragraph style). I also noticed that the font is not exactly the same (applicable font is Times New Roman, expansion is set to Times-Bold). 

I would expect font and font size of the expansion to follow the paragraph style set in MS Word. Changing the MS Word settings to Match Destination Formatting doesn't help either.

As a workaround,  I tried using the below HTML tag to decrease the font size (as suggested in #1926) but this makes no difference at all. 

```
trigger: ";ex"
html: (<font size="-num"><b>EXHIBIT {{exhibit.number}}</b></font>)
vars:
  - name: "exhibit"
     type: form
     params:
          layout: "Number: [[number]]"
```

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.
