### ISSUE TITLE
Implement multiple possible returns from a `choice` form variable.

### ISSUE THREAD

**Issue by GillesMINOT** [federico-terzi/espanso#2360]
### Description

Hello,

I am experiencing a persistent issue where form variables cannot be resolved, even on a completely fresh installation of Espanso.

**System Information:**
* **Espanso Version:** 2.2.1
* **OS:** Windows 11 (Build 22621)

**Problem Description:**
Even with a clean configuration folder, a minimal form using `multichoice` or a basic `text` field fails with the error `[ERROR] could not resolve variable...`.

**Minimal Reproducible Example (in `match/test.yml`):**
```yaml
matches:
  - trigger: ":projet"
    form: |
      layout:
        - fonctionnalites
      fields:
        fonctionnalites:
          type: multichoice
          label: "Choose features:"
          choices:
            - "SSO"
            - "Dashboard"
          params:
            multiline_sep: "\n- "
    replace: "Features chosen:\n\n- {{fonctionnalites}}"
```

### Logs

[ERROR] could not resolve variable "fonctionnalites"
[ERROR] error during rendering: rendering error
Caused by:
    missing variable: `fonctionnalites`

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
There are several errors in your code. Did you use an AI to generate it? 

- variables in forms need to have square brackets around them 
- you've included a non-existent key - `multiline_sep`
- and non-existent value - `multi choice`

Go back to https://espanso.org/docs/matches/forms/, start with one of the examples, making changes until it breaks, then reverting a step.

I'm happy to help further later, when I have more time.

**Comment by GillesMINOT** [comment]
hello Stephen

Yes, I used an AI (Gemini) because I wanted a form with the ability to select multiple values. I corrected it with your advice.

matches:
- trigger: ":project"
form: |
# Fix 1: The field name in the layout MUST be enclosed in double brackets.
layout: "[[fonctionnalites]]"
fields:
features:
# Fix 2: The type for multiple checkboxes is 'checkbox'.
type: checkbox
label: "Choose features:"
# The name 'choices' for the options list is correct.
choices:
- "SSO Authentication"
- "Dashboard"
- "Payment Module"
params:
# Fix 3: The separator parameter is 'sep'.
sep: "\n- "
replace: "Features chosen:\n\n- {{fonctionnalites}}"


but the defect remains the same

Thank you for your support and have a nice day.

Gilles

**Comment by smeech** [comment]
There is no `checkbox` type, and I'm not sure what you're trying to do with `sep: "\n- "`.

Basing the code on the example in [Controls with the Verbose syntax](https://espanso.org/docs/matches/forms/#controls-with-the-verbose-syntax) we can use:
```yml
  - trigger: :projet
    replace: "Features chosen:\n\n- {{form1.fonctionnalites}}"
    vars:
    - name: form1
      type: form
      params:
        layout: "Choose features: [[fonctionnalites]]"
        fields:
          fonctionnalites:
            type: choice
            values:
              - SSO
              - Dashboard
```
If it's not exactly what you were wanting, do come back to me!

**Comment by GillesMINOT** [comment]
Hello Stephen, 

Thank you for your patience. This code works but doesn't meet my expectations. I want to select multiple values ​​in the form.

I modified type: list and multiline:trues, but I can only select one value (SSO, for example), whereas I would like SSO and Dashboard.

- trigger: :project
replace: "Features selected: \n\n- {{form1.features}}"
vars:
- name: form1
type: form
params:
layout: "Selection made: [[features]]"
fields:
name:
multiline: true
features:
type: list
values:
- SSO
- Dashboard

Have a nice day

Gilles

**Comment by stewcam** [comment]
As a workaround, you could use an Espanso choice box or list box to show all the possible combinations (with 3 items there would be 7 combinations).

**Comment by GillesMINOT** [comment]
I didn't understand the expanso choice box workaround.

I added the checkbox style, but espanso doesn't support it (neither does label).

- trigger: ":form2"
replace: "Features chosen:\n\n- {{form1.features}}"
vars:
- name: form1
type: form
params:
layout: "[[features]]"
fields:
features:
type: choice
values:
- SSO authentication
- Dashboard
- Payment module
label: "Choose features (multiple possible):"
multiple: true
style: checkbox
sep: "\n- "

Have a nice day

**Comment by stewcam** [comment]
> I didn't understand the expanso choice box workaround.

You have 3 options - let's refer to them as A, B and C. The 7 possible combinations are {A}, {B}, {C}, {A, B}, {A, C}, {B, C} and {A, B, C}. You use an Espanso choice box or list box to allow you to select your preferred combination.

**Comment by GillesMINOT** [comment]
Thank you for your feedback. OK, I understand your suggestion, but it's not suitable because it's for entering a technical report, and the possible options are too numerous. The user would need to be able to select different lines.

I therefore understand that this isn't possible with espanso.

Thank you.

**Comment by smeech** [comment]
You're right - this isn't something that vanilla Espanso can handle - it won't deal with an indeterminate number of responses to a form variable except for the ability to return a blank entry as an option.

If you're happy to use a `script` extension, you can do something like:
```yml
  - trigger: ":checklist"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - -c
            - |
              import tkinter as tk
              from tkinter import ttk

              items = [
                "One",
                "Two",
                "Three",
                "Four",
              ]
              selected = []

              def on_submit():
                selected.extend(item for var, item in zip(vars, items) if var.get())
                root.quit()

              root = tk.Tk()
              root.title("Select Items")
              root.geometry("200x200")
              vars = []

              for item in items:
                var = tk.BooleanVar()
                cb = ttk.Checkbutton(root, text=item, variable=var)
                cb.pack(anchor='w')
                vars.append(var)

              ttk.Button(root, text="Submit", command=on_submit).pack(pady=10)
              root.mainloop()
              root.destroy()

              print(", ".join(selected))


```

**Comment by GillesMINOT** [comment]
Thank you for the code, but I don't want to use a Python script.
The real solution, as is currently the case, would be to open the search form with the options to select, as it allows searching but with a multi-line selection.

But sniff...the product may not be designed for that.

A huge thank you for your support.

Gilles

**Comment by smeech** [comment]
Thank you. I'll mark your request as an enhancement, perhaps rename it a little, and leave the Issue open.

**Comment by GillesMINOT** [comment]
Hello Stephen,
Do you know if this point is likely to be retained by the developer?

Thanks.

Gilles

**Comment by GillesMINOT** [comment]
what could be great is to have a preparatory zone of the text which is fed with each line selection then ok to transmit to the zone

![Image](https://github.com/user-attachments/assets/d931440a-d0a7-435a-844c-fe6c1e194f18)

Thanks

Gilles

**Comment by smeech** [comment]
> Hello Stephen, Do you know if this point is likely to be retained by the developer?
> 
> Thanks.
> 
> Gilles

Yours is a good suggestion, and one we'll keep in mind. However, we have many Issues to deal with, so unless it garners a lot of support, or someone specifically takes it on and contributes some code that might implement it, it's likely to remain as a relatively low priority (although I'm not marking it as such). Given my knowledge of the way Espanso works, it would require a significant rewrite. [DeepWiiki](https://deepwiki.com/espanso/espanso) seems to agree.

**Comment by lumetrium** [comment]
Hi! The Python example shared by @smeech inspired me to create a small app for this called [Espanso Dynamic Forms](https://github.com/lumetrium/espanso-dynamic-forms).

You'll first create a form config using the [JSON Forms](https://jsonforms.io) schema (you can write it in YAML). It's quite flexible - you can add validation, conditional fields, date pickers, and other advanced controls.

Then, in the same config file, you create a [Liquid](https://liquidjs.com) template. This template determines how the info you enter in the form will be formatted in the final output.

When you type your Espanso trigger, this app pops up with your form. After you submit it, the app uses your Liquid template to create the final text and sends it back to Espanso, which pastes it for you.

Here's a very basic example that addresses your specific need for multiple choices:

```yml
schema:  
  type: object  
  properties:  
    selections:  
      type: array  
      items:  
        type: string  
        enum:  
          - First choice  
          - Second choice  
          - Third choice  
          - Fourth choice  
      uniqueItems: true  
  
uischema:  
  type: VerticalLayout  
  elements:  
    - type: Control  
      scope: "#/properties/selections"  
      label: Select Your Options  
      options:  
        format: checkbox  
        vuetify:  
          v-input:  
            class: vertical  
  
data:  
  selections: []  
  
template: |  
  {% if selections.size > 0 %}  
  You selected:  
  - {{ selections | join: "\n- " }}  
  {% else %}  
  No items selected  
  {% endif %}
```

https://github.com/user-attachments/assets/357235f9-0686-44ca-8d04-260c435d9c1a

More details in the repository: https://github.com/lumetrium/espanso-dynamic-forms
