### ISSUE TITLE
Espanso Freezes the entire desktop when expanding a match

### ISSUE THREAD

**Issue by Luctins** [federico-terzi/espanso#237]
Every time espanso finds a matching expansion I cannot interact with the desktop for 5-10 seconds, but the mouse cursor still moves.
Most of the time this happens the trigger text is not completely erased. 
Espanso's own logs and `journalctl` were of not much use debugging this.
Tried using clipboard, auto and inject for the backend; same result.

Info:
pt-br keyboard layout
```
sb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

gnome-shell --version
GNOME Shell 3.28.4

echo $XDG_SESSION_TYPE 
x11

```

`espanso dump`
[config.txt](https://github.com/federico-terzi/espanso/files/4476495/config.txt)

**Comment by federico-terzi** [comment]
Hey @Luctins,

That is pretty strange indeed, thanks for pointing it out! Some questions for you:

* How many matches/packages have you installed?
* Could you please try the following procedure and see if that helps?
Switch to a US keyboard layout, restart espanso, type any match.

Let me know if you experience problems in that case as well.

Cheers :)

**Comment by Luctins** [comment]
examples:
On gedit:
![espanso-bug](https://user-images.githubusercontent.com/4743486/79249514-bdcdfc00-7e53-11ea-991b-afbbc303e910.gif)
on firefox:
![espanso-bug2 gif](https://user-images.githubusercontent.com/4743486/79249657-fb328980-7e53-11ea-880c-fcbf2e66c748.gif)

**Comment by Luctins** [comment]
I use:
```
espanso package list
basic-emojis - 0.1.0
shruggie - 0.1.0
```

**Comment by Luctins** [comment]
Uninstalled all packages and tested again, same result

**Comment by Luctins** [comment]
tested with US keyboard: could not interact with the desktop, and the "shell error tone" was played in quick sucession, could not recover desktop.

**Comment by federico-terzi** [comment]
> tested with US keyboard: could not interact with the desktop, and the "shell error tone" was played in quick sucession, could not recover desktop.

That is very strange @Luctins, I'm sorry you experienced these issues. Are you using a stock Ubuntu installation?

**Comment by Luctins** [comment]
thanks for taking the time to help :smile:.
The only major modification that I recall was uninstalling the nouveau driver (It's a hybrid graphics laptop).

**Comment by federico-terzi** [comment]
All right, thank you. I'll try to reproduce this myself and get back to you if I find something :)

**Comment by federico-terzi** [comment]
Hey @Luctins,

I was able to reproduce the issue, and after a lot of digging it seems to be a problem related to Gnome with some keyboard layouts, including the pt-br that you are using. (See [https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1777708](https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1777708))

In the above post, it explains a workaround:

With admin rights, edit the `/usr/share/X11/xkb/symbols/br` and comment out this line:
```
modifier_map Mod3 { Scroll_Lock };
```
so that it becomes:

```
//modifier_map Mod3 { Scroll_Lock };
```

Then reboot the system. Espanso should be a lot more responsive by then.

Let me know if that helps!

Cheers :)

**Comment by Luctins** [comment]
Wow, that's a not very obvious issue to track down.
As you have suggested I do have 2 keyboards (It's a laptop with a USB keyboard plugged in).
Applied the suggested modification and it seems to do it, Thanks :smile:. 

as a bonus, probably will make my desktop more stable overall (I was having mini freezes from time to time for a while now).
Close the issue?

**Comment by federico-terzi** [comment]
You're welcome :)
I'm going to close the issue now, let me know if you have other doubts

Cheers

**Comment by xnhp** [comment]
Hi, 

I am having a similar issue. However, I am on windows and use the default (german) keyboard layout.

After entering a trigger pattern, all inputs arrive extremely slowly and the trigger pattern is removed and the replacement inserted sluggishly over the next ~6 seconds.

I did not make any real customisations; this is my config:

```
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Change the key used to toggle espanso active mode
toggle_key: "OFF"

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ".ra"
    replace: "→"

  - trigger: ".dra"
    replace: "⇒"

  - trigger: ".cf"
    replace: "↝"

  - trigger: ".--"
    replace: "—"

  - trigger: ";b"
    replace: " •"

  - trigger: ".phi"
    replace: "ϕ"

  - trigger: ".ck"
    replace: "✓"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd:  "echo Hello from your shell"
```
