### ISSUE TITLE
Generate random strings of text?

### ISSUE THREAD

**Issue by JacobDB** [federico-terzi/espanso#247]
I'd love an option to generate "lorem ipsum" strings of text (randomly) – I often use https://lipsum.com/ to create dummy text while I'm building websites, so having a shortcode like `:lipsum` that just generates a sentence or a paragraph would be immensely useful to me.

**Comment by federico-terzi** [comment]
Hey @JacobDB,
Thank should be pretty easy to accomplish with the Shell or Script extension. Which Operating system are you using?

Cheers :)

**Comment by JacobDB** [comment]
Oh, I guess I misunderstood how those work! I'm on Windows.

**Comment by federico-terzi** [comment]
Here is how I would do:
* Make sure you have python installed and can call it from the terminal with "python"
* Save the following python script somewhere in your machine, in a path such as `C:\Users\Jacob\Documents\generator.py`

```python
import urllib
import urllib.request
import json
out = urllib.request.urlopen("https://baconipsum.com/api/?type=meat-and-filler").read()
j = json.loads(out)
print(j[0])
```

Which leverage on the [BeaconIpsum](https://baconipsum.com/json-api/) API. Varying the parameters of the URL you can also change the structure of the Ipsum.

* Add the following match:

```yml
  - trigger: ":ipsum"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "C:\\Users\\Jacob\\Documents\\generator.py"
```

Restart espanso and you should be good to go!
Make sure you type all the paths correctly :)
