### ISSUE TITLE
Shell type replacement may fail after restart the OS

### ISSUE THREAD

**Issue by tan-wei** [federico-terzi/espanso#261]
## Description
    In the config file, I create a shell type replacement:
```yaml
matches:
  - trigger: ":vpn"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat C:\\Users\\Winterreise\\AppData\\Roaming\\Lantern\\settings.yaml | grep addr | awk '{print $2}'"
          trim: true
```
   In a word, `:vpn` is replaced by the IPin the file `C:\Users\Winterreise\AppData\Roaming\Lantern\settings.yaml` . It works quite well just after I create the match trigger. However, after restart the OS, the replacement becomes an empty string:
![espanso_bug](https://user-images.githubusercontent.com/28227509/80930761-1c99ec00-8de8-11ea-8e6c-9ebd6b0f65ce.gif)
   We can confirm the result of the cmd is right:
![espanso_shell](https://user-images.githubusercontent.com/28227509/80930767-2d4a6200-8de8-11ea-83c9-195bd60ab163.gif)
  And then, I find that after `espanso edit` and just make the file updated without modifying any contents (e.g., adding a space and then deleting it), `espanso` will detect the `default.yml` is modified and restart automatically. Now, it works well:
![espanso_edit](https://user-images.githubusercontent.com/28227509/80930827-89ad8180-8de8-11ea-8dc9-344207040c64.gif)

## Other information
- Version: espanso 0.5.5
- OS: Windows 10 x64
- Teriminal: `Cmder` with `Microsoft Terminal` 
- An example just like `C:\Users\Winterreise\AppData\Roaming\Lantern\settings.yaml`:
```yaml
addr: 127.0.0.1:24205
autoLaunch: false
autoReport: true
lang: zh-CN
```

**Comment by tan-wei** [comment]
Just like #249 , I can see cmd windows popup after `:vpn` is typed. So the shell is run, but the output is not correctly fetched in espanso.

**Comment by federico-terzi** [comment]
Hey @tan-wei,

Thanks for reporting this problem. My first guess is that this doesn't depend on espanso but rather on something about your installation. Could you please try to use the complete paths for `cat`, `grep` and `awk`?
My guess is that espanso, at startup, can't find them in the PATH and therefore the match fails. Then, when you restart espanso with `espanso edit`, the current env variables (of the terminal) are passed to espanso and therefore it can find all those commands.

Let me know if that helps

Cheers :)

**Comment by tan-wei** [comment]
Thanks for your kind reply.
These UNIX tools locate in "C:\gnuwin32\bin", so I use the complete paths for `cat`, `grep` and `awk` like this:
```yaml
matches:
  - trigger: ":vpn"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "C:\\gnuwin32\\bin\\cat.exe C:\\Users\\Winterreise\\AppData\\Roaming\\Lantern\\settings.yaml | C:\\gnuwin32\\bin\\grep.exe addr | C:\\gnuwin32\\bin\\awk.exe \"{print $2}\""
          trim: true
```
However, the issue remainds the same. And I can confirm that the `cmd` is corrected ran in CMD (which is the actually cmd env instead of Cmder). Something wrong with escapes? Feel confused. BTW, thanks very much for your verbose reply.

**Comment by federico-terzi** [comment]
@tan-wei interesting, this rules out the missing PATH explanation. I have some questions for you:
* After an `espanso restart` it starts working, right?
* Could you please try to check whether it works by just placing the `cat` command without the grep and awk?

Cheers

**Comment by tan-wei** [comment]
Sorry, I didn't emphasize that `espanso restart` do not work, either. So I wonder if the escapes are wrong.
And I've tested the following replacement whose cmd contains only `cat`, it works correctly:
```yaml
matches:
  - trigger: ":test"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "C:\\gnuwin32\\bin\\cat.exe C:\\example.txt"
          trim: true
```
Does it mean there's something wrong with `grep` or `awk` command? I can't see any problem with them.

**Comment by federico-terzi** [comment]
@tan-wei  That is pretty strange indeed. I'm starting to suspect that pipes are somewhat broken on Windows.
I'll make a few tests and let you know.

Thanks for your help :)

**Comment by federico-terzi** [comment]
After some tests, I think the culprit might be the escaping of quotes in the awk command.
I haven't tested it, but can you please try this version:

```yaml
matches:
  - trigger: ":vpn"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "C:\\gnuwin32\\bin\\cat.exe C:\\Users\\Winterreise\\AppData\\Roaming\\Lantern\\settings.yaml | C:\\gnuwin32\\bin\\grep.exe addr | C:\\gnuwin32\\bin\\awk.exe {print $2}"
          trim: true
```
