### ISSUE TITLE
add "alias" triggers for one command

### ISSUE THREAD

**Issue by trolologuy** [federico-terzi/espanso#268]
It would be a nice feature to be able to use several triggers for the same command in the config file.

It's especially helpful when you use a lot of triggers and you don't really remember the exact semantic for the specific item you wish to expand.

This could be made with a list:
``` yml
  - trigger: 
      - ":portfolio"
      - ":site"
    replace: "https://trolologuy.github.io/"
```

Currently doing so triggers the error:
> Error parsing YAML file '/Users/XXX/Library/Preferences/espanso/default.yml', invalid syntax: matches[11].trigger: invalid type: sequence, expected a string at line 51 column 7
