### ISSUE TITLE
Shell command execution is broken

### ISSUE THREAD

**Issue by graphixillusion** [federico-terzi/espanso#269]
Hi there. The execution of a shell command using espanso seems to be broken under Windows 10. Using the default.yml file, with the default setting:

```
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
```
 when you type **":shell"** this error will appear:

**"Hello" is not recognized as an internal or external command, operable program or batch file.**
