### ISSUE TITLE
All global variables are triggered

### ISSUE THREAD

**Issue by atika** [federico-terzi/espanso#270]
Hi,
I tried to use **Global Variables** to display an input field with [Pashua](https://www.bluem.net/en/projects/pashua/) on macOS and it worked great.
The problem I encountered is that any expander I try, even if the global variable is not used in it, all shell script variables are executed.
**Example:**
```yml
global_vars:
  - name: "hello"
    type: "shell"
    params:
      cmd: "say Hello"
  - name: "textfield"
    type: "shell"
    params:
      cmd: "textfield.sh"

matches:
  - trigger: ":espanso"
    replace: "Hi there!"
```
In this example If you write ":espanso", you will hear "Hello", a text field will appear and the text is replaced. It's a problem as if the script used is a long-running script or just does something that would not have to be triggered each time.
