### ISSUE TITLE
Accept input prior to expansion

### ISSUE THREAD

**Issue by pard68** [federico-terzi/espanso#296]
I was thinking it would be really handy to be able to have an input that is used in the expansion, for example:
`:fliptable text to flip:`

would result in:
`(┛◉Д◉)┛彡 ʇǝxʇ ʇo ɟlᴉd`

Syntax could be something like:
```
- trugger: ":fliptable{input}:"
  replace: "`(┛◉Д◉)┛彡{{output}}"
  vars:
    - name: output
      type: script
      params:
        args:
          - python
          - /path/to/flip_text.py
          - {{input}}
```
