### ISSUE TITLE
How to insert tomorow and yesterday dates?

### ISSUE THREAD

**Issue by jrcacd** [federico-terzi/espanso#311]

**Comment by federico-terzi** [comment]
Hey,

This could be a very useful feature indeed, I'll add it to the roadmap!

Cheers :)

**Comment by femtocept** [comment]
You can do it with shell integration if your system has the `date` program.
```
  - trigger: ";tomorrow"
    replace: "Tomorrow is {{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date -v+1d +%D"
```
- The +1d is the time adjustment and can also take - for past times.
- The +%D controls the formatting and allows you to do other things like make it say "Monday" with %A (look up the strftime codes for more options). As of writing this, tomorrow is Monday.

I don't think this is helpful for windows users, though.

**Comment by mrjackphil** [comment]
For those who uses Windows10 with Linux Subsystem 

```yaml
  - trigger: ":1date"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "bash -c 'date +%Y-%m-%d -d +1day'"

```

**Comment by federico-terzi** [comment]
Hey @mrjackphil,
Thank you for pointing this out. To complement your answer, I'd like to say that since espanso 0.6.0 you can use WSL directly with the "wsl" parameter:

```yaml
  - trigger: ":1date"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date +%Y-%m-%d -d +1day"
          shell: wsl
```

Cheers :)

**Comment by mrjackphil** [comment]
@federico-terzi Just tried it and it works not as I expected. Maybe because of Cyrillic symbols or different format. While my configuration returns:
```
2020-06-15
```
when tried your I receive:
```
������� �������⨬�� ���.
������ ����� ���� (��-��-��): 
```

**Comment by federico-terzi** [comment]
Thank you for pointing that out @mrjackphil, this seems like a bug! Could you please tell me which language are you using? If I manage to reproduce it I might be able to get a solution :)

**Comment by mrjackphil** [comment]
I'm using a Windows 10 Home Edition. Russian language.

**Comment by federico-terzi** [comment]
All right, thank you @mrjackphil

**Comment by mrrcollins** [comment]
Just a heads up, `date` under macOS needs the -v argument, but that will cause `date` under Linux to give an error. If you use Espanso under both OSes, you'll probably need a script to use the correct version of `date`.

**Comment by federico-terzi** [comment]
@mrrcollins thanks for your feedback, I've opened an issue to make this handling more convenient #353

**Comment by federico-terzi** [comment]
Just wanted to let you know that the next release (0.7.0) will support this out of the box. In particular, you will be able to specify an `offset` parameter that takes the number of seconds of offset.
For example:

```yaml
  - trigger: ":yesterday"
    replace: "{{mytime}}"
    vars:
    - name: mytime
      type: date
      params:
        format: "%c"
        offset: -86400
  - trigger: ":tomorrow"
    replace: "{{mytime}}"
    vars:
    - name: mytime
      type: date
      params:
        format: "%c"
        offset: 86400
```

**Comment by jrcacd** [comment]
Very good!!!

**Comment by jczanfona** [comment]
PLS @mrjackphil 
What is wrong here?... 
```
  - trigger: ":fecha"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date /t"
```

It does nothing! (W10)

**Comment by federico-terzi** [comment]
@jczanfona You should be able to get it working by specifying the `cmd` shell:

```yaml
  - trigger: ":fecha"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date /t"
          shell: cmd
```

Cheers :)

**Comment by jczanfona** [comment]
TX a lot
Great sw !!!

**Comment by mhofherr** [comment]
Hi,

is there a good possibility to make this dynamic? On MAC OS I am using Keyboard Maestro to create a popup-box, enter a number X, and the output is the future date (today + X days). I would like to do something similar on Windows with espanso as well. Any ideas for that?

Thanks,
Matthias

> Just wanted to let you know that the next release (0.7.0) will support this out of the box. In particular, you will be able to specify an `offset` parameter that takes the number of seconds of offset.
> For example:
> 
> ```yaml
>   - trigger: ":yesterday"
>     replace: "{{mytime}}"
>     vars:
>     - name: mytime
>       type: date
>       params:
>         format: "%c"
>         offset: -86400
>   - trigger: ":tomorrow"
>     replace: "{{mytime}}"
>     vars:
>     - name: mytime
>       type: date
>       params:
>         format: "%c"
>         offset: 86400
> ```

**Comment by federico-terzi** [comment]
Hey @mhofherr,

> is there a good possibility to make this dynamic?

Not out of the box, but you should be able to do so with a custom script :)

Here's something to get started: 

* An example of Python script that works with dates: https://github.com/federico-terzi/espanso/issues/442#issuecomment-687097808
* Using a Form to send a parameter to a script: https://espanso.org/docs/forms/#using-with-script-and-shell-extension

Cheers :)

**Comment by mhofherr** [comment]
Thanks a lot for fast reply! Will have a look at the indicated examples.

**Comment by mhofherr** [comment]
Followup-question: I copled together the following:
```
# Test
  - trigger: ".mydate"
    replace: "{{mydate}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Add days {{name}}
    - name: newdate
      type: shell
      params:
       cmd: "(Get-Date).AddDays($ESPANSO_FORM1_NAME).ToString('yyyy-MM-dd')"
       shell: powershell
```
I know that "(Get-Date).AddDays(1).ToString('yyyy-MM-dd')" delivers today's date +1 on powershell. With the variable it does not work. Do you have any insights what I am doing wrong here (Windows 10; Powershell)?

Thanks,
Matthias

**Comment by federico-terzi** [comment]
Hey @mhofherr ,

I'm not a PowerShell expert, but according to [this post](https://stackoverflow.com/questions/49899603/reading-environment-variable-via-powershell) you might want to use `${ESPANSO_FORM1_NAME}` to access the variable, such as:

```yaml
  - trigger: ".mydate"
    replace: "{{mydate}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Add days {{name}}
    - name: newdate
      type: shell
      params:
       cmd: "(Get-Date).AddDays(${ESPANSO_FORM1_NAME}).ToString('yyyy-MM-dd')"
       shell: powershell
```

Let me know if that helps!

Cheers :)

**Comment by mhofherr** [comment]
Almost, but your link did the trick  => the following works for me:
`cmd: "(Get-Date).AddDays(${env:ESPANSO_FORM1_NAME}).ToString('yyyy-MM-dd')"`

Thanks again,
Matthias

**Comment by andrej1919** [comment]
Hey,

This code does not work. Maybe I am too optimistic when it comes to injecting variables?

```yml
    # calc days
  - trigger: "ddc"
    replace: "{{result_day}}"
    vars:
    - name: frm_day                       # get user input (number of days)
      type: form
      params:
        layout: |
         Enter number of days: [[days]]
    - name: calc_offset                   # calculate offset in seconds
      type: shell
      params:
       cmd: "echo '86400 * {{frm_day.days}}' | bc" 
    - name: result_day
      type: date
      params:
        offset: "{{calc_offset}}"         # this variable is not injected
        format: "%Y-%m-%d"
```

Thanks,
Andrej

**Comment by andrej1919** [comment]
Hey,

I found a solution:

``` yaml
    # calc days
  - trigger: "ddc"
    replace: "{{result_day}}"
    vars:
    - name: frm_day                       # get user input (number of days)
      type: form
      params:
        layout: |
          Enter number of days: [[days]]
    - name: result_day                   # calculate offset in shell
      type: shell
      params:
       cmd: "date -d \"{{frm_day.days}} days\" -u +%Y-%m-%d" 
```

But I am still curious to know whether offset parameter can receive an injected variable.

Cheers,
Andrej
