### ISSUE TITLE
Unstable substitution

### ISSUE THREAD

**Issue by Masacroso** [federico-terzi/espanso#331]
After a while using espanso with the following replacement:

`````
  - trigger: "++"
    replace: "^{$|$}"
`````
sometimes it doesn't work as expected, it just write `{}` instead of `^{}`, but this behavior seems to be random, almost all the time it works correctly. This happens in kubuntu 19.10 and in windows 10.

**Comment by federico-terzi** [comment]
Hey @Masacroso,

Maybe try to use the `force_clipboard` option and see if that helps:

```yaml
  - trigger: "++"
    replace: "^{$|$}"
    force_clipboard: true
```

Cheers :)
