### ISSUE TITLE
Underscore breaks passive mode?

### ISSUE THREAD

**Issue by michalsieron** [federico-terzi/espanso#332]
Windows 10, espanso 0.6.2

I am having an issue with passive mode and trigger with underscore
Example:
``` yml
  - trigger: ":ab"
    replace: "Hello there!"
    passive_only: true
```
works just fine, but
``` yml
  - trigger: ":a_b"
    replace: "Hello there!"
    passive_only: true
```
doesn't work at all
