### ISSUE TITLE
Trigger is removed but no replacement (Thunderbird?)

### ISSUE THREAD

**Issue by 73** [federico-terzi/espanso#351]
Hi,

first of all: thanks for espanso.
I am running Ubuntu 20.04 (X11) and often, not always, the trigger is removed but the replacement (an emoji) is not inserted. This happens most often for me in Lightning (the calendar extension). Then I open gedit, insert the emoji there and copy & paste it to the input field I want it in. Is there an option to get debug infos I could provide?

Edit: Now it happens in gedit, too. But not in the terminal.

Thanks,
--73

**Comment by federico-terzi** [comment]
Hey,

I'm sorry you experienced this issue. Could you please try to follow these steps and see if it helps on Thunderbird: https://github.com/federico-terzi/espanso/issues/285#issuecomment-629849295

Cheers :)

**Comment by 73** [comment]
Hey,

that did not change anything. :/

**Comment by federico-terzi** [comment]
That's unfortunate... Could you please post the output of `espanso log` here?

**Comment by 73** [comment]
Sure. However, there seems not much to go on:
```
🠶  espanso log
12:07:20 [ INFO] espanso version 0.6.2
12:07:20 [ INFO] using config path: /home/user/.config/espanso
12:07:20 [ INFO] using package path: /home/user/.local/share/espanso/packages
12:07:20 [ INFO] spawning worker process...
12:07:20 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/espanso.sock
12:07:20 [ INFO] initializing worker process...
12:07:20 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/worker.sock
12:07:20 [ INFO] worker is running!
12:07:20 [ INFO] watching for changes in path: /home/user/.config/espanso
```

**Comment by 73** [comment]
Okay. This is my `~/.config/espanso/user/thunderbird.yml`:
```yml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
# paste_shortcut: CtrlShiftV
```
And now it seem to work. Slow, but it works. #130 mislead me.

**Comment by federico-terzi** [comment]
Glad you sorted it out :) Thanks for the update

**Comment by 73** [comment]
This came back for me.

**Comment by federico-terzi** [comment]
@73 Could you please try with a patch file like:

```yaml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
paste_shortcut: CtrlShiftV
```

**Comment by 73** [comment]
That did not change the behavior. I also tried these two, but to no avail:
```yml
fast_inject: false
backspace_delay: 10
```

**Comment by 73** [comment]
This works currently pretty well:
```yml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
backspace_delay: 10
inject_delay: 5
```

**Comment by federico-terzi** [comment]
@73 Glad you sorted that out, thanks for sharing. Might I close the issue?

**Comment by 73** [comment]
I will close it soon if I am convinced it will hold up.

**Comment by ziotom78** [comment]
For the record, this trick worked for me with Thunderbird 78.8.1 on Linux Mint 20.1 Xfce, but I had to increase both the `backspace_delay` and the `inject_delay`:

```yaml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
backspace_delay: 10
inject_delay: 5
```

Keeping the values `10` and `5` as in the [comment above](https://github.com/federico-terzi/espanso/issues/351#issuecomment-671363097) worked only on ~1/2 of the cases.
