### ISSUE TITLE
clipboard contents getting overwritten during passive match (xclip)

### ISSUE THREAD

**Issue by AndydeCleyre** [federico-terzi/espanso#365]
Arch Linux, espanso 0.6.3, GNU `sed`

The goal is to indent the clipboard contents, line by line, with a given number of spaces. I have a similar active match that always does 4 spaces, but want to add one that prepends an arbitrary number of spaces, and the best I could think of so far was cramming a looped `printf` in there.

```yaml
backend: Clipboard
fast_inject: false
enable_passive: true
passive_key: CTRL

matches:

  - trigger: :in
    replace: "{{indented}}"
    passive_only: true
    vars:
      - name: indented
        type: shell
        params:
          cmd: sed "s/^/$(for i in {1..$0}; do printf "%s" " "; done)/g" <<<"$(xclip -sel clip -o)"
          trim: false
```

```console
$ printf '%s\n' line1 line2 | xclip -sel clip
$ xclip -sel clip -o
line1
line2
```

Before and after:
```
:in/2/

  :in/2/

```

```console
$ xclip -sel clip -o
  :in/2/
```

I don't have any syncing going on between `XA_PRIMARY` and `XA_CLIPBOARD`; without running espanso, I can select text after text, but the output of `xclip -sel clip -o` will not change. It seems during a passive replacement, espanso writes over the contents of `XA_CLIPBOARD`.
