### ISSUE TITLE
Set expansion property for all matches

### ISSUE THREAD

**Issue by muhlinux** [federico-terzi/espanso#371]
If you have a user config `/user/spelling.yml`, it would be very convenient to be able to specify global options for that file  making the configuration less repetitive.

```yml
name: spelling
parent: default
propagate_case: true
word: true

matches:
  - trigger: foo  
    replace: bar

  - trigger: baz  
    replace: qux
    propagate_case: false # local overwrite
```
