### ISSUE TITLE
Cross-platform paths in ScriptExtension (Part II)

### ISSUE THREAD

**Issue by viruscmd** [federico-terzi/espanso#380]
Maybe I missed this somewhere but i could not find it while digging though the code. It would be great to get %CONFIG%  and %PACKAGES% macro (or whatever we are calling this) like in the %HOME% macro in issue #265 

I think this would make script execution easier for packages. Like this:

```yml
name: "My awesome package"
parent: default

matches:
  - trigger: ":map"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - sh
            - "%PACKAGES%/my-awesome-package/script.sh"
```
