### ISSUE TITLE
Config files don't support `.yaml`?

### ISSUE THREAD

**Issue by 4lch4** [federico-terzi/espanso#385]
This is more of a question than an actual issue. I tried creating some new "packages" under the user config folder and they had the `.yaml` extension as opposed to `.yml`. They don't seem to be getting picked up by espanso though.

When I created a new `social.yaml` and gave it a simple match, it wasn't being picked up by espanso, which leads me to believe the `.yaml` extension isn't supported. I'm not too in touch with YAML but after some Google searches, `.yaml` is the "recommended"[\[0\]][0][\[1\]][1] version and `.yml` is the more popular but equally as valid version.

Here's the content of the mentioned `social.yaml` file:

```yaml
name: 'social'
parent: 'default'

matches:
  - trigger: ":tst"
    replace: "Thisis just a test."
```

Is this intentional or am I just missing something?

[0]: https://en.wikipedia.org/wiki/YAML
[1]: https://yaml.org/faq.html
