### ISSUE TITLE
no pasting in xterm (neither Shift-Insert nor Ctrl-Shift-V)

### ISSUE THREAD

**Issue by Konfekt** [federico-terzi/espanso#389]
Espanso's pasting in `xterm` does not work, even though `Shift-Insert` pastes fine and `espanso detect` shows `XTerm`.

While `espanso` pastes fine  in `urxvt` after adding a file `~/.config/espanso/user/urxvt.yml` with content

```
name: URxvt

filter_class: "URxvt"
paste_shortcut: CtrlShiftV
```

the analog procedure for `xterm` does not let `espanso` paste, even after setting up in `~/.Xresources` the binding

```
XTerm*VT100.translations:    #override \n\
  Ctrl Shift <Key>V: insert-selection(CLIPBOARD)
```

Perhaps `espanso` does not detect `xterm` correctly?

**Comment by federico-terzi** [comment]
Hey,

Could you please try to add another `xterm.yml` file inside your `user/` directory with this content:

```yaml
name: XTerm

filter_class: "XTerm"
backend: Clipboard
```

Let me know it that helps

Cheers :)

**Comment by Konfekt** [comment]
Thank you, this helps! Only backspace is not working, that is, the replaced text is appended and the kept. For example, typing `:espanso` gives `:espansoHi there!`.

**Comment by federico-terzi** [comment]
That's strange! Could you please try with this modification:

```yaml
name: XTerm

filter_class: "XTerm"
fast_inject: false
backend: Clipboard
```

Let me know it that helps :)
