### ISSUE TITLE
Accents act as word separators

### ISSUE THREAD

**Issue by kfeine** [federico-terzi/espanso#409]
Hi,

I just started using espanso 0.6.3 on OS X 10.15.6, installed with hombrew cast.

It seems that accents doesn't act as part of words, but as word separators. So, with this config:
```
matches:
  - trigger: "e"
    replace: "espanso"
    word: true
```
When I type ```liée<space>```, I get ```liéespanso ```, wich is not what I would expect, as I'm still typing a word.

Thanks for your job,
Kind regards,
