### ISSUE TITLE
Negate filter_class

### ISSUE THREAD

**Issue by sphh** [federico-terzi/espanso#423]
Let's assume, that I want to insert the greek character α in all programs, but not in `TeXstudio`, my LaTeX editor. Let us also assume, that I want to write the greek character with `\alpha` (because that's what I am used to do). I have all my greek characters in one configuration file:

`$HOME/.config/espanso/user/greek-letters.yml`:
```yaml
name: greek-letters
# parent: default

# filter_class: !TeXstudio

matches:
  - trigger: "\\alpha"
    replace: "α"
```

1. Using this as shown, `\alpha` is not replaced in any program.
2. If I uncomment the line `parent: default`, `\alpha` is replaced in `TeXstudio` (which I don't want it to be) and in all other programs.
3. If I uncomment the line `filter_class: !TeXstudio`, `\alpha` is not replaced in any program.

Is there a way to get `\alpha` replaced in **all** programs, **but not** in `TeXstudio`?

If this is not implemented yet, I would suggest to add the `!` operator to the `filter_class` directive…

The workaround would be to use `:alpha` as a trigger, but then I always have to remember in which program I am in the moment.

PS: I use espanso v0.7.0
