### ISSUE TITLE
Forms are not focusing the first field on Mac

### ISSUE THREAD

**Issue by macintacos** [federico-terzi/espanso#430]
Sorry, opened an issue by accident before finishing the whole thing.

I'm running into an issue with forms that I'm hoping could either be fixed or clarified. Take the following straightforward example:

```yaml
matches:
  - trigger: ":link"
    form: |
      https://example.com/{{query}}
```

When I type out `:link`, I'm presented with a form (as expected) however the form doesn't highlight the first input field so that I can begin typing. The only way that I can tell to "focus" the first field is to click the field with my mouse.

Is this intentional? And if it's not, can this be fixed? In my head I'm thinking that the field should have focus when the form is opened, so this feels like unexpected behavior.
