### ISSUE TITLE
Simple matches: condensed way to write static matches

### ISSUE THREAD

**Issue by mrgnw** [federico-terzi/espanso#435]
[Static matches](https://espanso.org/docs/matches/#static-matches) are simple enough we could potentially define `trigger` and `replace` as simple `key`: `value` pairs.

### Current syntax

```yaml
  - trigger: ":espanso"
    replace: "Hi there!"
```

### Proposed syntax

```yaml
  - ":espanso": 'Hi there!'
```

### Implementing
I've primarily considered two potential implementations:

####  `matches` also accepts trigger:replace as key: value pairs

As long as the trigger is valid yaml & not an espanso key word, each `key: value` it could still go under `matches:`

```yaml
matches:
  - ":espanso": 'Hi there!'
```

####  `simple_matches`

A separate `simple_matches:` section might make it easier to organize, understand, and implement.

```yaml
simple_matches:
  - ":espanso": 'Hey there!'
```
I assume simple_matches could be formatted with trigger+replace and extend `matches`.

### Or both?

It could be possible to do both and leave organization up to the user.

If I had to pick one way I'd go with  `simple_matches`  - it's probably easier to implement & explain.

## bonus: word matches?
This could be especially useful to implement for word matches too.
Each word match adds 1 line for `word: true`, and I imagine most if not all word matches are also static matches.

```yaml
matches:
  - trigger: "hey"
    replace: 'Hey there!'
    word: true
  - trigger: "hello"
    replace: 'Hello there!'
    word: true
  - trigger: "hej"
    replace: 'Hallå där!'
    word: true
```
vs
```yaml
word_matches:
  - hey: 'Hey there!'
  - hello: 'Hello there!'
  - hej: 'Hallå där!'
```
Organizationally, this could also make it easy for users to sort lines alphabetically.

**Comment by federico-terzi** [comment]
Hey  @mrgnw,

Thank you for the feedback! Indeed, a shorthand to declare simple matches would be useful. Given this problem, we have 3 constraints:
1. The new syntax has to be concise
2. The new syntax should not break the previous one
3. The new syntax should be reasonably easy to implement given the current parser implementation

Possibly, we would also like something elegant. While I like your proposed approach, I don't like the fact of having two additional `word_matches` or `simple_matches` keys. I feel matches should reside in the `matches` key, otherwise that might become confusing to the user. On the other hand, including the map-like syntax in the `matches` clauses could be problematic, as it could conflict with existing reserved keys.

Another possibility would be to use an array-like syntax:

```yaml
matches:
  - [:espanso, Hi there!]
  - [hey, Hey there!, w]
  - trigger: "hej"
    replace: 'Hallå där!'
    word: true
``` 

The rationale would be to mix the standard syntax with an *array-like* one, in which the first argument is the trigger, the second one the replacement and, optionally, the third one for modifiers (word, propagate_case, ecc).
The upside of this one is that it's easier to implement, as the above is valid YAML and an array is easy to discriminate from an object. I don't think it's very elegant though.

We'll need to think carefully about this feature, hopefully getting some feedback from the community.

Let me know what you think :)

**Comment by mrgnw** [comment]
I like it!

Array-like syntax seems like the best combination of concise, easy to implement, and flexible with more options than just static matches.

As you said this all depends on community's use, so I'm trying to feel out the most concise way to write the most common use case (or two). I assume static matching is most common, followed by word matches. Word matches & other modifiers also seems more compressible, since each modifier adds a line per match.

**Comment by mrgnw** [comment]
Additional thoughts purely for the sake of brainstorming & conceptualization - I imagine these might not fit the constraints yet but maybe one could get close, or maybe they could helps us get to something else down the road.

#### c) key:values under `matches:`, with array-like syntax for modifiers
```yaml
matches:
  - ":espanso": "Hi there!"
  - "hey": [Hey there!, w]
  - "hej": [Hallå där!, w]
```
(still have to account for keyword conflicts)

#### d) subsections of matches for most common / simple use cases
```yaml
matches:
 - static:
   - ":espanso": "Hi there!"
   - ":x2": "Hi again!"
 - word:
   - hey: hey there!
   - hej: Hallå där!
 - trigger: ":bye"
   replace: "See you later!"
```
(no keyword conflicts, but adds 1-2 new keywords/features)

#### e) simple = static match + word match
`word: true` and using a prefix  cover the same core concern - not accidentally triggering matches.

For simple matches, would it be reasonable to assume:
- simple matches are word matches by default
- unless they start with a non-alphanumeric character

```yaml
matches:
 - simple:
   - ":espanso": "Hi there!"
   - ":x2": "Hi again!"
   - hey: hey there!
   - hej: Hallå där!
 - trigger: ":bye"
   replace: "See you later!"
```
(no keyword conflicts, but 1 new keyword/feature, with an assumption that prefixes & word matches work together for the same purpose)
