### ISSUE TITLE
Inject variables in Form layout and parameters

### ISSUE THREAD

**Issue by AmberHaelo** [federico-terzi/espanso#441]
I use global variables a lot, and was trying to find a way to easily combine them with the excellent new form feature. I didn't see it documented specifically, but once you get to the part about creating custom form layouts and variable scoping, it can be guessed at. Here is the solution for anyone else that is curious:

```yaml
global_vars:
  - name: "author"
    type: dummy
    params:
      echo: "AmberHaelo"
matches:
  - trigger: ":test"
    replace: |
      # {{formData.documentTitle}} #
      by {{author}}
    vars:
      - name: "formData"
        type: form
        params:
          layout: |
            # {{documentTitle}} #
            by {{author}}
```

So, this works *pretty well*, and in fact if you're copying this for your own use, do note that using a global variable in the `layout` does nothing; it is a field that ignores anything you type into it. For real use, you would want to keep global variables out of the `layout`.

The reason I put it in there is provide a demonstration for the first proposal here: that global variables be cabable of local override in cases like this. This is a good example. If I want to mark that this document as written by someone else, then I should be able to fill in the field to do so. And to make this more intuitive, it might not be a bad idea for global variables used in a form's layout to act as a *default value*. So this example form when used would then have a blank "Document Title" field followed by an Author field with "AmberHaelo" already typed in. But, I can see how that would cause scope confusion internally, so that leads to the second proposal...

And that is to make all of this a bit easier to use! Basically all of the above is necessary, as best I can tell, if you want to mix globals into your form output. You can't use the easy method (`form` instead of `replace`) because that internally rewrites all fields to `{{form1.fieldName}}`, thus making the internal result `{{form1.author}}`.

But given the precedent for that very approach, how about *this* as a way of creating forms with global variables, without having to sacrifice the easy method:

```yaml
matches:
  - trigger: ":test"
    form: |
      # {{documentTitle}} #
      by {{global_vars.author}}
```

That's a whole lot easier for a human to parse and maintain, if that's all you need! And if one does want the ability to override the global default, or use it in the form, then the first method still works fine for that, and is probably the best solution given you would want to control how the local form variable works and prints itself.

This approach would be compatible with both the simpler variant and the one that currently works. The difference is that we could use the current approach if we want to make use of global variables inside of form elements (or do anything else fancy with them). For archiving articles I might only ever want to use my proper full name by default, but for archiving forum posts, a list of handles would be useful:

```yaml
  - trigger: ":test"
    form: |
      # {{documentTitle}} #
      by {{author}}
    form_fields:
      author:
        type: choice
        values:
          - "{{global_vars.author}}"
          - "Pseudonym One"
          - "Pseudonym Two"
```

Hopefully that all makes sense, but let me know if anything isn't clear. Overall though, thanks for adding this wonderful capability!

**Comment by federico-terzi** [comment]
@AmberHaelo Indeed, having variables inside forms could be useful in many situations. Building on top of your proposal, what do you think about:

```yml
matches:
  - trigger: ":test"
    form: |
      # {{documentTitle}} #
      by {{vars.author}}
```

Instead of using `global_vars`, we use the generic `vars`, which could also include previously defined local variables.
Would that solve your use-case?

**Comment by AmberHaelo** [comment]
Looks great, and yes that would solve the problems I was running into as well as being more flexible all around.

**Comment by federico-terzi** [comment]
Great, I'll make sure to add this feature to the roadmap!

**Comment by shw00p** [comment]
Just wanted to second this feature request! This would be incredibly useful for being able to default the value of a form field to whatever I have on my clipboard. Eg)
``` yaml
global_vars:
  - name: "clipboard"
    type: "clipboard"
matches:
  - trigger: ":test"
    replace: |
       # {{formData.documentTitle}} #
       by {{formData.clip2}}
    vars:
      - name: "formData"
        type: form
        params:
          layout: |
            # {{documentTitle}} #
            by {{clip2}}
          fields: 
            clip2:
              default: {{clipboard}}
```

My current use case for this is using forms and a script to ergonomically add auto-corrections for typos from anywhere to the default.yml file. It would only save a keystroke so not a big deal but would be nice 😁
