### ISSUE TITLE
How can I get "today's date" in the format below?

### ISSUE THREAD

**Issue by MrNotch9** [federico-terzi/espanso#442]
Sep 3rd, 2020

**Comment by federico-terzi** [comment]
I don't belive the `3rd` part is possible out of the box, but you could get close:
`%h %e, %Y`, which should produce `Sep 3, 2020`

I think you'll need a custom script for that

**Comment by MrNotch9** [comment]
> I don't believe the `3rd` part is possible out of the box, but you could get close:
> `%h %e, %Y`, which should produce `Sep 3, 2020`
> 
> I think you'll need a custom script for that

I don't know how to create a custom script. Can you help me?

**Comment by federico-terzi** [comment]
> I don't know how to create a custom script. Can you help me?

What OS are you using?

**Comment by MrNotch9** [comment]
> > I don't know how to create a custom script. Can you help me?
> 
> What OS are you using?

It's macOS 10.15.6

**Comment by federico-terzi** [comment]
You first have to create a python script, place it in `espanso/scripts/date.py` (create the script directory if necessary), with the following content:

```python
from datetime import datetime as dt

def suffix(d):
    return 'th' if 11<=d<=13 else {1:'st',2:'nd',3:'rd'}.get(d%10, 'th')

def custom_strftime(format, t):
    return t.strftime(format).replace('{S}', str(t.day) + suffix(t.day))

print(custom_strftime('%b {S}, %Y', dt.now()))
```

Then add this match:

```yml
  - trigger: ":date"
    replace: "{{output}}"
    vars:
      name: "output"
      type: script
      params:
        args:
          - python3
          - "%CONFIG%/scripts/date.py"
```

Let me know if that works :)
