### ISSUE TITLE
Final newline in | replacements

### ISSUE THREAD

**Issue by sphh** [federico-terzi/espanso#443]
If I use a multiline replacement with `|`, I always get an empty newline at the end, e.g.
```yaml
matches:
  - trigger: ":kr1"
    replace: |
      Kind regards
      Max
  - trigger: ":kr2"
    replace: "Kind regards\nMax"
```
`:kr1` result in
```
Kind regards
Max

```    
and `:kr2` results in
```
Kind regards
Max
```
Note the final empty line in the `:kr1` expansion.

I would expect both matches to expand exactly in the same way.
