### ISSUE TITLE
Cursor Hints issue when using Microsoft Sticky Notes

### ISSUE THREAD

**Issue by Sispheor** [federico-terzi/espanso#445]
When using this conf:
```yaml
 - trigger: ":md"
    replace: |
      ```
      $|$
      ```
```

In the notepad app it's ok but in the Microsoft Sticky Notes app I get the markdown code highlight quotes but instead of the cursor I have `44444` on the last line:
```
'''

'''
44444
```

**Comment by federico-terzi** [comment]
Hey @Sispheor,

That's interesting. To mitigate the problem, you might want to try the `force_clipboard` option:

```yaml
 - trigger: ":md"
   force_clipboard: true
   replace: |
      ```
      $|$
      ```
```

Cheers :)
