### ISSUE TITLE
Package dadjoke doesn't seem to work on Windows

### ISSUE THREAD

**Issue by marc-oclock** [federico-terzi/espanso#451]
Hi ! 😃

After installing the [dadjoke package](https://hub.espanso.org/packages/dadjoke/) on Windows I tried it but nothing is replaced. 
I use the ":dadjoke" trigger, it disappears and then: nothing. Just a blank space.

- I have curl installed properly. -> _curl 7.55.1 (Windows)_
- Windows 10

I do have rights to add label but you can add at least : Windows, bug ?

**Comment by federico-terzi** [comment]
Hey @marc-oclock,

Could you please post the output of `espanso log` here? That should give us more information about the error.
Moreover, do you use Windows Subsystem for Linux? If that's the case, we could find an even easier way to make it work.

For reference, this is the match the package is using:

```yaml
- trigger: ":dadjoke"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl -H 'Accept: text/plain' https://icanhazdadjoke.com/"
```

Cheers :)
