### ISSUE TITLE
Time-dependent (or argument-dependent) expansion: "Good morning Federico!"

### ISSUE THREAD

**Issue by rsuzuki0** [federico-terzi/espanso#454]
Currently, I can only see how to do it in two steps, the first step by automatic expansion, and the second, passive. I want this to be automatic, one-step expansion:
```
  - trigger: ".g "
    replace: ":greetings{{hour}}"
    vars:
    - name: hour
      type: date
      params:
        format: "%H"

  - triggers: [":greetings11", ":greetings12"]
    passive_only: true
    replace: "Hello"

  - triggers: [":greetings20", ":greetings21", ":greetings22", ":greetings23"]
    passive_only: true
    replace: "Hello"

  - triggers: [":greetings19", ":greetings18", ":greetings17"]
    passive_only: true
    replace: "Good evening"

  - triggers: [":greetings05", ":greetings06", ":greetings07", ":greetings08", ":greetings09", ":greetings10"]
    passive_only: true
    replace: "Good morning"

  - triggers: [":greetings13", ":greetings14", ":greetings15", ":greetings16"]
    replace: "Good afternoon"
    passive_only: true
```
P.S. for this purpose, I had to expand the passive trigger definition to include [[:numbers:]] by using [[:alnum:]] in place of \\p{L} like:

```
passive_match_regex: "(?P<name>:[[:alnum:]]+)(/(?P<args>.*)/)?"
```

It's probably a good idea to allow numbers and an "_" and maybe even "-" in this if there is no harm.
