### ISSUE TITLE
Thunderbird plain text and html editor

### ISSUE THREAD

**Issue by sphh** [federico-terzi/espanso#455]
I just noticed, that espanso behaves differently in Thunderbird's plain text and html editor.

I need multiline expansions, so according to https://github.com/federico-terzi/espanso/issues/285#issuecomment-629849295 I have:
```yaml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
paste_shortcut: CtrlShiftV

matches:
  - trigger: ":kr"
    replace: |-
      Kind regards
      Max
```

I get the following results:
- Plain message editor:
```
```
(Yes, nothing)
- HTML message editor:
```
Kind regards
Max
```
```html
  <body>
    Kind regards<br>
    Max<br>
  </body>
```

With
```yaml
filter_class: "Thunderbird"
backend: Clipboard
```
(`paste_shortcut: CtrlShiftV` commented out)
I get the following results:
- Plain message editor:
```
Kind regards
Max
```
- HTML message editor:
```
Kind regards Max
```
```html
  <body>
    Kind regards
    Max
  </body>
```

And with just
```yaml
filter_class: "Thunderbird"
```
(`backend: Clipboard` also commented out):
- Plain message editor:
```
Kind regards
Max
```
- HTML message editor:
```
Kind regards

Max
```
```html
  <body>
    <p>Kind regards</p>
    <p>Max<br>
    </p>
  </body>
```

I tried to differentiate the two message editors by their window properties, but no luck, because `espanso detect` returns the same for both:
```
Detected change, current window has properties:
==> Title: 'Write: (no subject) - Thunderbird - Max Mustermann <mm@mannomann.com>'
==> Class: 'Thunderbird'
==> Executable: ''
```

Any idea how to get a consistent behaviour for both editors?

**Comment by federico-terzi** [comment]
Hey @sphh,
Thank you! That finally makes sense :) I was wondering whether some users were able to use that workaround while others couldn't...

> Any idea how to get a consistent behaviour for both editors?

That's a good question. Unfortunately, I don't have any idea to solve the problem at the moment.
Hopefully, when #214 gets implemented, this problem will be solved as well (as you could set up a match as a rich text match).

Cheers :)

**Comment by sphh** [comment]
I had a fresh look at this issue using the latest version 0.7.3.

I removed the entry for the `backend`, now using the default:
```yaml
filter_class: "Thunderbird|TeXstudio"
#backend: Clipboard
```

Looks like espanso now inserts the replacement both into the html and plain text editors! That's very good!

But I noticed the following, when playing with `markdown` and `html` replacements: They work fine in the html editor, but if I use them in Thunderbird's plain text editor, I get the following:
```yaml
matches:
  - trigger: ":kr"
    markdown: |-
      Kind regards
      Max
```
becomes in the plain text editor:
```
楋摮爠来牡獤䴠硡
```
(AI at work translating it on the fly to Chinese?)

The same for
```yaml
matches:
  - trigger: ":kr"
    html: |-
      Kind regards<br />
      Max
```
⇒
```
楋摮爠来牡獤戼⁲㸯䴊硡
```

**Comment by federico-terzi** [comment]
Hey @sphh,

Thank you for the investigation! 

> But I noticed the following, when playing with markdown and html replacements: They work fine in the html editor, but if I use them in Thunderbird's plain text editor, I get the following:

That's interesting, does it happen on every application or in Thunderbird only?

If `xclip` could support multiple paste formats (last time I searched it wasn't clear how to do it), we could instruct espanso to copy both the Text and HTML versions in the clipboard and let the text editor decide which one was best suited.

Cheers :)

**Comment by sphh** [comment]
Good question regarding other applications!
Here are my results:
1. `replace`:
    - works in TB html editor
    - works in TB plain text editor
    - works in Xed and the terminal
2. `markdown`: works in TB html editor
    - works in TB html editor
    - gives Chinese characters in TB plain text editor
    - removes the trigger, but does not insert anything

Have you asked at https://github.com/astrand/xclip/ to support multiple targets?

These bug reports might be related: https://github.com/astrand/xclip/issues/93 https://github.com/astrand/xclip/issues/94

**Comment by federico-terzi** [comment]
@sphh Thank you for the detailed investigation! This information will be very useful.

> Have you asked at https://github.com/astrand/xclip/ to support multiple targets?

No, I haven't. Besides the fact that the project does not seem very active, I'm investigating possible alternatives to xclip, as I'm currently working on a major refactor. Hopefully, we will be able to fix that issue and remove the xclip dependency :)

**Comment by sphh** [comment]
Thanks for taking care of this. Looking already forward towards the refactored program!

**Comment by federico-terzi** [comment]
@sphh Thanks, I'll make sure to create a tracking issue in the next few days so that we can all keep track of the refactoring

**Comment by sphh** [comment]
Thanks for the continuing work on this program!

I upgraded to 2.1.2-alpha and tested this again.

I created an application specific config file for Thunderbird:
```yaml
filter_class: "Thunderbird"
backend: Auto
#backend: Clipboard
#backend: Inject
```
and dis/enabled the different backends (edited on the fly with Espanso notifying me, that the configuration was reloaded as soon as I save the file). All of them show the same behaviour:
1. The text is correctly expanded in a terminal, in CudaText, Spyder, Firefox, … and in Thunderbird HTML message edit windows.
2. The match is deleted, but no expansion inserted into Thunderbird plain message edit windows.

**Comment by federico-terzi** [comment]
Hey @sphh,

Thanks for investigating! The v2 comes with a built-in patch for thunderbird, which might be interfering with your experiment: https://github.com/federico-terzi/espanso/blob/master/espanso/src/patch/patches/linux/thunderbird_x11.rs#L37-L40

One thing you might try is editing the app-specific config for thunderbird you created, adding this line:

```yaml
paste_shortcut: "SHIFT+INSERT"
backend: Clipboard
```

Let me know if that helps :) Also you might want to type `#acfg#` inside Thunderbird. That will show you the active configuration being used by Espanso. If you post it here, that might help debug this further 

Cheers :)

**Comment by sphh** [comment]
Thanks.

I tested it with this configuration (`.config/espanso/config/thunderbird.yml`):
```yaml
filter_class: "Thunderbird"
paste_shortcut: "SHIFT+INSERT"
backend: Clipboard
extra_includes:
  - "../match/_correspondance.yml"
```

`#detect#` returns
```yaml
title: 'Write: (no subject) - Thunderbird'
exec: '/usr/lib/thunderbird/thunderbird'
class: 'Thunderbird'
```

and `#acfg#`:
```yaml
[espanso config: "/home/user/.config/espanso/config/thunderbird.yml (PATCHED: thunderbird_x11)"]

backend: Clipboard
enable: true
paste_shortcut: Some("CTRL+SHIFT+V")
inject_delay: Some(15)
key_delay: Some(15)
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
backspace_limit: 5
search_trigger: Some("jkj")
search_shortcut: Some("ALT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "/home/user/Data/dotConfig/espanso/match/_correspondance.yml",
    [...]
]
```

As you can see, `paste_shortcut` is not `"SHIFT+INSERT"`, but the file `_correspondance.yml` is loaded, so I guess `config/thunderbird.yml` is picked up correctly.

**Comment by federico-terzi** [comment]
@sphh Thanks! Ok, that looks correct

> As you can see, paste_shortcut is not "SHIFT+INSERT", but the file _correspondance.yml is loaded, so I guess config/thunderbird.yml is picked up correctly.

You're right! That's because the patch overrides the custom config you specified. To avoid that, you can add this option to your `thunderbird.yml`:

```
apply_patch: false
```

Let me know if that helps :)

**Comment by sphh** [comment]
Thanks. 

With `apply_patch: false` `#acfg#` shows `paste_shortcut: Some("SHIFT+INSERT")`, but now I get the following behaviour:
1. Expansion in the plain message editor works as expected.
2. In the HTML message editor, the current clipboard is inserted instead of the expansed phrase (and there is a _long_ delay between removing the shortcut and inserting the clipboard).

This behaviour is independent of the setting of the `paste_shortcut`.

But if I switch back to `backend: Auto`, everything is working fine.

My working `config/thunderbird.yml` is now:
```yaml
filter_class: "Thunderbird"
apply_patch: false
backend: Auto
extra_includes:
  - "../match/_correspondance.yml"
```

and `#acfg#`:
```yaml
[espanso config: "/home/user/.config/espanso/config/thunderbird.yml"]

backend: Auto
enable: true
paste_shortcut: None
inject_delay: None
key_delay: None
apply_patch: false
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
backspace_limit: 5
search_trigger: Some("jkj")
search_shortcut: Some("ALT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "/home/user/Data/dotConfig/espanso/match/_correspondance.yml",
    [...]
]
```

**Comment by federico-terzi** [comment]
@sphh Thanks! That's interesting

> But if I switch back to backend: Auto, everything is working fine.

So if you keep `Auto`, everything works as expected on both the Plain and HTML editors? If that's the case, we might need to remove the thunderbird patch :)

**Comment by sphh** [comment]
> So if you keep Auto, everything works as expected on both the Plain and HTML editors? 

Yes.

>If that's the case, we might need to remove the thunderbird patch :)

I wouldn't be surprised, if it depends on the version of Thunderbird :( The version I currently use is `78.14.0 (64-bit)` (on `Linux Mint 20.2`).

I just noticed another problem with expansions, but this problem shows in Thunderbird HTML editor _and_ [`xed`, Linux Mint's editor](https://github.com/linuxmint/xed/) from the XApplication family. I could not identify any other editor showing this behaviour:
- Sometimes the expansion phrase is deleted, but no expanded phrase inserted (I believe this happens with expanded phrases consisting of just one single character).
- Sometimes the expansion phrase is deleted and the current contents of the clipboard is inserted (after a very long wait of some seconds).
- Sometimes everything works as it should (I believe it works, if there is cursor position specified in the expanded phrase).

Is this the behaviour, the thunderbird patch try to resolve? If not, I am happy to open a separate bug.

**Comment by federico-terzi** [comment]
@sphh Thanks!

> I wouldn't be surprised, if it depends on the version of Thunderbird :( The version I currently use is 78.14.0 (64-bit) (on Linux Mint 20.2).

I've originally added the patch due to this issue: https://github.com/federico-terzi/espanso/issues/351, it seems I mistakenly added the `paste_shortcut` override even if it wasn't needed, so I'll try removing that first

Regarding the other problems you mentioned, perhaps slowing down the injection a bit might help:

```yaml
inject_delay: 15
key_delay: 15
```

Cheers :)

**Comment by sphh** [comment]
Unfortunately that does not help:

I can remove the `key_delay: 15` (I even tried `30`) and the phrase to be expanded still gets removed.

It does not matter, if I have `inject_delay: 15` (or `30`) in my configuration, it still inserts the actual contents of the clipboard and not the expanded phrase.

And I noticed something else: I have Thunderbird message editor and a terminal open (to edit Espanso's config file). I type `;copyright` (which should be become a `©`) in the Thunderbird message editor. As soon as I finish that phrase, it gets deleted. No `©` gets inserted. Then I switch to the terminal and press `Backspace` and suddenly `;copyright` appears in the terminal …

**Comment by federico-terzi** [comment]
@sphh I see, thanks!

Another thing you might try is increasing the `pre_paste_delay` to something like 500 or more. From the docs:

![image](https://user-images.githubusercontent.com/20475953/149005434-1cdcfb8b-5722-43c4-8ae7-8390f59c222a.png)

And also the `restore_clipboard_delay` option:

![image](https://user-images.githubusercontent.com/20475953/149005501-b5005a8a-b8a2-4f55-9e2b-a1403bb3e8c2.png)

For more info: https://espanso.org/docs/next/configuration/options/#options-reference

> Then I switch to the terminal and press Backspace and suddenly ;copyright appears in the terminal …

This is interesting, how do you switch to the terminal window? (using the mouse, keyboard shortcut, something else?). Pressing backspace immediately after an expansion "reverts" it due to the `undo_backspace` feature, which can be disabled. The strange thing is that Espanso should invalidate the "undoability" as soon as some actions occur, including changing the window... So this is likely a bug :)

**Comment by sphh** [comment]
Thank you for your patience! I just added `pre_paste_delay: 500` to the Thunderbird specific configuration. It is working for now, nevertheless I will observe it.

I switch to the terminal window by mouse: I use `focus follows mouse`, so I just move the mouse pointer over the terminal and it gets the input focus. (BTW with the expansion working for now, I do not get the behaviour described).

**Comment by sphh** [comment]
Sorry, the all clear came to early. I again experience this behaviour!

To recap:
1. It does not happen in the plain text editor.
2. It does happen in the HTML editor.
3. It does not happen in the plain text HTML editor (add-on `ThunderHTMLedit`).

I increased all timeouts to very large values:
```yaml
filter_class: "Thunderbird"
apply_patch: false
backend: Clipboard
pre_paste_delay: 1000
key_delay: 300
inject_delay: 300
restore_clipboard_delay: 1000
extra_includes:
  - "../match/_correspondance.yml"
```
