### ISSUE TITLE
Toggle between yml files.

### ISSUE THREAD

**Issue by nandhukumar86** [federico-terzi/espanso#462]
Hi Team,

I work on both C# and Python. 
I need a feature to toggle between the programming languages.

Say, I have two yml files: csharp.yml and python.yml. Both should contain ':print' which triggers its corresponding print texts. 

But at a point, I want anyone of them to be enabled. Is there a feature already exists, if so how can I enable this?

**Comment by federico-terzi** [comment]
@nandhukumar86 This seems like a great feature to have! I was thinking about adding "modes" to espanso, so that only some matches could be enabled at a given time. I'll add it to the roadmap :)

**Comment by nandhukumar86** [comment]
Thanks, @federico-terzi - for considering this as a feature.

**Comment by gabindu** [comment]
Just a quick note that as a quick and dirty workaround, you can simulate modes by moving the relevant config files in and out of the `user` folder with a shell command or script. For example, I use these triggers to activate or deactivate my `accents.yml` file:

```
  - trigger: ":accoff"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - mv
            - "%CONFIG%/user/accents.yml"
            - "%CONFIG%/inactive/"

  - trigger: ":accon"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - mv
            - "%CONFIG%/inactive/accents.yml"
            - "%CONFIG%/user/"
```

It's a bit slow, since you have to wait for the automatic config reloading, but it works. (And one could make this fancier by writing a custom script which enables true toggling, or cycling through several files.)
