### ISSUE TITLE
FEATURE: Form Labels

### ISSUE THREAD

**Issue by potsed** [federico-terzi/espanso#468]
Love what is done with Espanso! 

That said please have an option to separate the form from the content to prevent the form box opening too big on long copy snippets.

Perhaps someone with some RUST experience can do something similar to parsing this:

```
matches:
  - trigger: ":shortform"
    word: true
    form: |
              Some long copy ....
              ....
              ....
              ....
              {{name}}
              {{choice}} 
              ....
    form_short: true
    form_fields:
      name:
        label: "Full Name"
      choice:
        type: choice
        label: "Choose Something"
        values:
          - ON
          - OFF
```

To display a shorter labelled form like:

![image](https://user-images.githubusercontent.com/542347/94202562-3b1c9300-ff01-11ea-8ce8-3d08ea611689.png)

**Comment by federico-terzi** [comment]
Hey @potsed,

Thank you for the feedback! You can already do something similar with the verbose form syntax ([docs](https://espanso.org/docs/forms/#controls-with-the-verbose-syntax)), in your example:

```yaml
  - trigger: ":shortform"
    replace: |
              Some long copy ....
              ....
              ....
              ....
              {{form1.name}}
              {{form1.choice}} 
              ....
    vars:
      - name: "form1"
        type: form
        params:
          layout: "Full Name: {{name}}\n Choose Something: {{choice}}"
          fields:
            choice:
              type: choice
              values:
                - ON
                - OFF
```

Which produces:

![image](https://user-images.githubusercontent.com/20475953/94203542-e1e03f80-febf-11ea-9cc9-143923b4fb10.png)

But when expanded:

```
Some long copy ....
....
....
....
Hey
ON 
....
```

Is that what you were looking for? Given that you didn't find it, we should probably improve the docs :)

Cheers :)
