### ISSUE TITLE
How to insert this week’s date range?

### ISSUE THREAD

**Issue by nicrivard** [federico-terzi/espanso#473]
Hi - would it be possible to leverage the Date command in `shell` to display this week’s date range (week starts on Monday) in “YYMMDD - YYMMDD” format? This could be offset to also show last week’s date range and next week’s date range?

This links to issue #311

**Comment by federico-terzi** [comment]
Hey,

Just to make sure I understand properly, are you trying to use the output of the Date command inside a shell extension?

Cheers :)

**Comment by nicrivard** [comment]
Hey - thanks for the quick reply, Federico. 

Sorry, I think I meant to write : "...the Date command in `chrono`...".  I was inspired by this comment: https://github.com/federico-terzi/espanso/issues/311#issuecomment-640257639 which suggested using `shell`.

I've set-up a match which works instantaneously on this trigger: 

`- trigger: ":today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%y%m%d %A"`

so what I'm envisioning is something like:

`- trigger: ":week"
    replace: "{{week}}"
    vars:
      - name: week
        type: date
        params:
          format: "%y%m%d - %y%m%d(+6)"`

But if you think there's a better / easier way of doing it in `shell` or another language, please advise 😅

**Comment by federico-terzi** [comment]
Hey,
You have to use 2 variables, such as:

```yaml
- trigger: ":week"
  replace: "{{week}} - {{nextWeek}}"
  vars:
    - name: week
      type: date
      params:
        format: "%y%m%d"
   - name: nextWeek
      type: date
      params:
        format: "%y%m%d"
        offset: 604800 # 7 days in seconds
```

Cheers :)
