### ISSUE TITLE
[feature] Allows using script to output a dynamic list for a field

### ISSUE THREAD

**Issue by yihou** [federico-terzi/espanso#478]
Just throwing out my ideas here. Currently users can list down static items defined in the config, but cant display dynamic list. What if we can add shell script to output comma separated values as the field's list?
Example:
```yml
  - trigger: ":ssh"
    replace: "ssh {{address}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Choose your address {{address}}
       fields:
         name:  address
         type: shell
         params:
           cmd: "./comma_separated_ssh_list.sh" # allow gather list of ssh hostname from ~/.ssh/config
           # script output => address1, address2, address3
```

**Comment by federico-terzi** [comment]
Hey,
Thank you for the feedback! This could be a great idea indeed, and it's related to #441.
I'll make sure to add it in one of the next versions of espanso :)

**Comment by federico-terzi** [comment]
Hey @yihou ,

The next version 2.1.0-alpha will ship with the new [variable injection](https://espanso.org/docs/next/matches/variables/) mechanism that should handle your use-case well, thank you for the help! :)

You'll also need to slightly change the form definitions for the new control syntax: https://espanso.org/docs/next/migration/what_changed/#new-forms-control-syntax

The following example shows how you could use the output of a shell command to populate a form's choice/list control. In this case, the match can be used to implement a rudimentary file-picker:

```yaml
  - trigger: ":file"
    replace: "{{form1.file}}"
    vars:
      - name: files
        type: shell
        params:
          cmd: "find ~/Documents -maxdepth 1"
      - name: form1
        type: form
        params:
          layout: |
            Select file:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
```

Cheers :)
