### ISSUE TITLE
Python script returns blank space

### ISSUE THREAD

**Issue by psyguy** [federico-terzi/espanso#479]
Hi,

I am trying to run the following python script (located in `/scripts/` of the folder containing `default.yml`):

``` python
import time

number = int(time.time())
base36 = ''
alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"

if number < len(alphabet):
    base36 = alphabet[number]
else:
    while number != 0:
        number, i = divmod(number, len(alphabet))
        base36 = alphabet[i] + base36

print(base36)
```

With the following command:

``` yml
  - trigger: ":pyscript"
    replace: "{{output}}"
    vars:
      - name: "output"
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/time2base36.py"
```

But espanso returns a blank space. What am I doing wrong?

(I tried it first with bash script and had the same issue as I asked on [Reddit a few hours ago](https://www.reddit.com/r/espanso/comments/j3v7pe/printing_the_outcome_of_a_bash_script_shell_noob/). I blamed my bash-illiteracy though 😄, and tried it in Python.)

**Comment by Hammer2900** [comment]
In my case all working, try this.

```
  - trigger: ":test"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python /home/hammer/Documents/_HOME/dry-python-bot/2.py"
```
