### ISSUE TITLE
Injecting python arguments using forms/passive mode

### ISSUE THREAD

**Issue by psyguy** [federico-terzi/espanso#486]
Hi,

I want to use forms and passive mode to insert two arguments to the script (`test2arg.py`) that I have in `/%CONFIG%/scripts/`:

``` python
import sys

inp1 = str(sys.argv[1])
inp2 = str(sys.argv[2])

print("First: " + inp1 + ", second: " + inp2)
```

I have tried (and failed) using forms (the following), but it returns `First: year, second: month`:

``` yaml

  - trigger: ":pyfor"
    replace: "{{output}}"
    vars:
      - name: year
        type: form
        params:
          layout: |
            Year {{year}}
            Month {{month}}
      - name: output
        type: script
        params:
          inject_args: true
          args:
            - C:/Users/haqiq001/Anaconda3/python.exe
            - "%CONFIG%/scripts/test2arg.py"
            - year
            - month
```

And this is what I am trying as a passive command:

``` yaml
  - trigger: ":pypass"
    replace: "{{output}}"
    passive_only: true
    vars:
    - name: output
      type: script
      params:
        inject_args: true
        args:
          - C:/Users/haqiq001/Anaconda3/python.exe
          - "%CONFIG%/scripts/test2arg.py"
```

And nothing happens when I type `:pypass/one/two/` and control-select it. (I have added `enable_passive: true` and `passive_key: CTRL` already, and in fact, could not even reproduce `:greet/jon/` example.)

I am on Windows 10 (previously #479 😅), and `espanso log` looks fine. How can I solve these issues (the former being more important)?

Thanks in advance!

**Comment by federico-terzi** [comment]
Hey,
Keep in mind that form arguments are passed as env variables to scripts and not as command-line arguments, so in your case, you should change the python script as follows:

```python
import os

inp1 = os.environ['ESPANSO_YEAR_YEAR']
inp2 = os.environ['ESPANSO_YEAR_MONTH']

print("First: " + inp1 + ", second: " + inp2)
```

and then the match would become:

```yml
  - trigger: ":pyfor"
    replace: "{{output}}"
    vars:
      - name: year
        type: form
        params:
          layout: |
            Year {{year}}
            Month {{month}}
      - name: output
        type: script
        params:
          args:
            - C:/Users/haqiq001/Anaconda3/python.exe
            - "%CONFIG%/scripts/test2arg.py"
```

If you want to know more, please take a look at [this section of the docs](https://espanso.org/docs/forms/#using-with-script-and-shell-extension)

Cheers :)
