### ISSUE TITLE
Encoding issue on system start

### ISSUE THREAD

**Issue by kaaloo** [federico-terzi/espanso#489]
After starting or rebooting my computer running Ubuntu 20.04, output from espanso date commands is not correctly encoded.  For instance expanding the following trigger works fine.

```
  - trigger: ":espanso"
    replace: "Hi there!"
```

However this one

```
  - trigger: ":ts"
    replace: "{{ts}}"
    vars:
      - name: ts
        type: date
        params:
          format: "%F %T"
```

displays

```éàéà)&à)&( àèM"_M'à```

Running `espanso restart` restores the expected behavior.  Perhaps the daemon is started before relevant environment variables are set?
