### ISSUE TITLE
An inconsistent issue in VSCode's integrated terminal

### ISSUE THREAD

**Issue by hos4m** [federico-terzi/espanso#496]
![Kapture 2020-10-20 at 08 27 31](https://user-images.githubusercontent.com/4350401/96585859-276d0e00-12ae-11eb-874b-ef3f0db5667a.gif)

My shortcut should expand from `:git` to `git add . && git commit -m ""`

As it's demonstrated in the GIF, the 1st and 2nd attempts work fine but the 3rd doesn't.

OS version: macOS 10.15.7
VSCode version: 1.50.1

It's worth mentioning that this issue doesn't happen when I'm using Espanso outside VSCode's terminal.

**Comment by federico-terzi** [comment]
Hey @hos4m,
Thanks for reporting this issue! Could you try adding `force_clipboard: true` to your match and see if that helps?

```yaml
  - trigger: ":git"
    force_clipboard: true
    replace: "git add . && git commit -m \"$|$\""
```

It seems like VSCode is not able to process espanso input fast enough, so this method should help.
Let me know if that improves the situation

Cheers :)
