### ISSUE TITLE
Delay the expanding's speed

### ISSUE THREAD

**Issue by trolologuy** [federico-terzi/espanso#500]
Hi, 

I'm using something similar to the following snippet:
```
  - trigger: ":mytrigger"
    backend: "Inject"
    replace: |
      some_id = '{{clipboard}}'
      # A rather lengthy shell script
    vars:
      - name: "clipboard"
        type: "clipboard"

```
I'm encountering some issues with a program I'm interacting with that is reading character after character.
Pasting stuff, through the system native copy/paste works.

When using espanso, the "expanding" is rather slow (made character after character?), which causes that program to fail.
Could it be possible to set a "timer" to paste all that was processed into espanso at once? 

The idea would be that the expanding would follow the same behavior as a system-triggered copy and paste.

**Comment by federico-terzi** [comment]
Hey @trolologuy,

Two things to keep in mind:
* the backend option can't be used inside a match, but must be declared in the top-most configuration file level (above the `matches` section).
* You might be able to accomplish your goal with the `force_clipboard: true` option:

```yaml
  - trigger: ":mytrigger"
    force_clipboard: true
    replace: |
      some_id = '{{clipboard}}'
      # A rather lengthy shell script
    vars:
      - name: "clipboard"
        type: "clipboard"
```

Let me know if that helps

Cheers :)
