### ISSUE TITLE
Inability to reference variables inside shell

### ISSUE THREAD

**Issue by KuSi833** [federico-terzi/espanso#505]
I'm on Windows 10, and using the version 0.7.2

The following code doesn't output anything for me:

```
- trigger: ":rev"
  replace: "{{reversed}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Reverse {{name}}
    - name: reversed
      type: shell
      params:
       cmd: "echo $ESPANSO_FORM1_NAME | rev"
```

Furthermore if I change the cmd to this:
`cmd: "echo test $ESPANSO_FORM1_NAME"`
It does write test, yet the form1_name is still missing, therefore I would assume the problem is with the reference?

**Comment by federico-terzi** [comment]
Hi @KuSi833,
That's because on Windows 10 you don't have the `rev` command by default, so unfortunately the first example will not work.
Do you have Windows Subsystem for Linux installed? If that's the case, the solution is simply to specify `shell: wsl` such as:

```yaml
  - trigger: ":rev"
    replace: "{{reversed}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Reverse {{name}}
    - name: reversed
      type: shell
      params:
       cmd: "echo $ESPANSO_FORM1_NAME | rev"
       shell: wsl
```

If you don't have WSL installed, then `rev` will not work but you can make the other example work by changing the shell to `cmd` (Command Prompt) and using the percent sign instead (see: https://superuser.com/questions/341192/how-can-i-display-the-contents-of-an-environment-variable-from-the-command-promp)

```yaml
  - trigger: ":rev"
    replace: "{{reversed}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Reverse {{name}}
    - name: reversed
      type: shell
      params:
       cmd: "echo test %ESPANSO_FORM1_NAME%"
       shell: cmd
```

Cheers :)
