### ISSUE TITLE
Newline doesn't get expanded in Linux/Thunderbird when text contains special character

### ISSUE THREAD

**Issue by bojanra** [federico-terzi/espanso#509]
The configuration with a newline and special character

```yaml
matches:
  # German greeting text replacement
  - trigger: ":mfg"
    replace: ":Mit freundlichen Grüssen\nBojan"
```
gets in Thunderbird expanded to
```
Mit freundlichen Grüssen Bojan
```
Everywhere else it's correctly expanded to

```
Mit freundlichen Grüssen
Bojan
```

**Comment by federico-terzi** [comment]
Hey @bojanra,

Could you please try adding the `force_clipboard: true` option and see if that helps?

```yaml
matches:
  # German greeting text replacement
  - trigger: ":mfg"
    force_clipboard: true
    replace: ":Mit freundlichen Grüssen\nBojan"
```

Cheers :)
