### ISSUE TITLE
Add an option to disable Passive Argument injection in shell extension and disable it by default

### ISSUE THREAD

**Issue by MatteoGgl** [federico-terzi/espanso#513]
I created this following snippet inside `.config/espanso/user/shell.yml`:

```
- trigger: "wg:do"                                                            
     replace: "sudo wg-quick down {{inet}}"                                      
      vars:                                                                       
        - name: inet                                                              
          type: shell                                                             
          params:                                                                 
            cmd: "ip a | grep 'global mullvad' | awk '{ print $5 }'" 
```

The command when run from shell correctly outputs `mullvad-fi2`. When executed through espanso the variable gets replaced with `inet 10.67.2.181/32 scope global mullvad-fi2` which is the output given when omitting the `awk` pipe.

This results in the expansion being:

`sudo wg-quick down inet 10.67.2.181/32 scope global mullvad-fi2`

when the correct result would be:

`sudo wg-quick down mullvad-it8`

I noticed when testing for the issue that if the single quotation marks surrounding the awk print instruction are changed to double quotation marks, the command ignores awk, effectively only printing the result of the grep expression.

I'm currently on Ubuntu 20.04, using bash, espanso version 0.7.2.

**Comment by federico-terzi** [comment]
Hey Matteo,

Thanks for reporting this issue! This is the result of a weird rule espanso has that automatically replaces positional arguments, such as `$1`, with the ones from [Passive Mode](https://espanso.org/docs/passive-mode/).

I understand this can be very inconvenient in this case, so I'll make sure to add an option to disable this replacement in the future version :)

In the meanwhile, you could try replacing the `$5` with something different, such as:

```
- trigger: "wg:do"                                                            
     replace: "sudo wg-quick down {{inet}}"                                      
      vars:                                                                       
        - name: inet                                                              
          type: shell                                                             
          params:                                                                 
            cmd: "ip a | grep 'global mullvad' | awk -v col=5 '{ print $col }'" 
```

Let me know if that works for you

Cheers :)
