### ISSUE TITLE
Docs: couldn't find anything in docs about scripts

### ISSUE THREAD

**Issue by Maxhodges** [federico-terzi/espanso#515]
scripts in Python only? can script in JavaScript? should answer in docs or FAQ

**Comment by federico-terzi** [comment]
Hey,
Thank you for the feedback! Yes, you can use other languages, you just need to specify the path to the interpreter instead of `python`. For example, if you want to use JS, you could do:

```yaml
- trigger: ":jsscript"
  replace: "{{output}}"
  vars:
    - name: output
      type: script
      params:
        args:
          - node
          - /path/to/your/script.js
```

Cheers :)

**Comment by yannxaver** [comment]
> 

This does not work for me. espanso says:
```
16:47:11 [worker(97314)] [WARN] extension 'script' on var: 'output' reported an error: could not execute script: '`node`', error: '`No such file or directory (os error 2)`'
16:47:11 [worker(97314)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute script: '`node`', error: '`No such file or directory (os error 2)`'
```

**Comment by federico-terzi** [comment]
@yannxaver I'm sorry you experienced this problem! What kind of absolute path did you try?
* Did you specify the absolute path of `node` as well?
* Did you install node through nvm?
Cheers :)

**Comment by yannxaver** [comment]
Haha, no worries @federico-terzi . Your app is awesome :)

Yes I am using nvm and this is the config that led to the error above: 

```yaml
- trigger: ":script"
  replace: "{{output}}"
  vars:
      - name: output
        type: script
        params:
          args:
            - node
            - "%CONFIG%/scripts/time.js"
```

When I switch the node variable to this: 
`"/Users/myname/.nvm/versions/node/v16.7.0"` 
then the error changes to: 
`[WARN] extension 'script' on var: 'output' reported an error: could not execute script: '/Users/myname/.nvm/versions/node/v16.7.0', error: 'Permission denied (os error 13)'`

**Comment by federico-terzi** [comment]
@yannxaver Interesting, thanks!

Given that `nvm` does quite a few things under the hoods, you might try invoking it through the shell:

```yaml
- trigger: ":script"
  replace: "{{output}}"
  vars:
      - name: output
        type: shell
        params:
          cmd: "node $CONFIG/scripts/time.js"
```

Let me know if that helps :)

**Comment by yannxaver** [comment]
`10:49:07 [worker(25442)] [ERROR] shell command exited with code: exit status: 127 and error: sh: node: command not found`

**Comment by federico-terzi** [comment]
@yannxaver Interesting, perhaps we need to activate the `nvm` environment? Like

```
   cmd: "nvm use 16 && node $CONFIG/scripts/time.js"
```

I haven't tested it though

**Comment by yannxaver** [comment]
```
10:27:10 [worker(82836)] [ERROR] shell command exited with code: exit status: 127 and error: sh: nvm: command not found
```

nvm is installed and working though

**Comment by federico-terzi** [comment]
@yannxaver Thanks! What happens if you change the shell to `bash`? Such as:

```
- trigger: ":script"
  replace: "{{output}}"
  vars:
      - name: output
        type: shell
        params:
          cmd: "node $CONFIG/scripts/time.js"
          shell: bash
```

I suspect that because Espanso is using `sh` by default, `nvm` hasn't been registered: https://github.com/nvm-sh/nvm#install--update-script

**Comment by yannxaver** [comment]
Same error with `bash` shell. By the way, my default shell is `zsh` (which is the default on macOS now I think). Since `zsh` cannot be chosen as an argument for shell I assume that the espanso config considers `sh === zsh`?

**Comment by TyMick** [comment]
I found in https://github.com/federico-terzi/espanso/issues/966#issuecomment-1022723885 that Espanso can't read my `$PATH` on macOS. When I change my shell extension command to `echo $PATH`, typing the match produces just `/usr/bin:/bin:/usr/sbin:/sbin`, and my `node` is in `/usr/local/bin`.

Also, I confirmed that I can access `node` myself from fish (my default shell), zsh, bash, and sh, so the problem isn't the choice of shell.

```console
ty.mick@ws2833 ~> node -v
v16.13.2
ty.mick@ws2833 ~> zsh
ty.mick@ws1990 ~ % node -v
v16.13.2
ty.mick@ws1990 ~ % exit
ty.mick@ws2833 ~> bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ node -v
v16.13.2
bash-3.2$ exit
exit
ty.mick@ws2833 ~> sh
sh-3.2$ node -v
v16.13.2
```

**Comment by TyMick** [comment]
If we rename this issue something like "Script/shell extensions can't read `$PATH` on macOS", I'll go ahead and close #966 in favor of this. 👍🏼

**Comment by federico-terzi** [comment]
@TyMick Thanks! Let's keep this one open as it's more related to the documentation side :)

**Comment by lucasrafaldini** [comment]
@federico-terzi I would like to add it in documentation but I didn't found any docs folder.

**Comment by AucaCoyan** [comment]
This issue was solved in the current documentation (can't really pinpoint a moment in git history where)

**Comment by ethyde** [comment]
Hello !

So what is the right solution to use a JS script on macos with nvm?

I couldn't find the information in the doc either :/

**Comment by AucaCoyan** [comment]
Hi! I looked up quickly in the code base and [this line](https://github.com/espanso/espanso/blob/c4b3d5ae279807ce1fd146e1219aa063685c021a/espanso-config/src/matches/mod.rs#L210) suggests that you can put everything on the Params type (a little bit below)
```rust
pub type Params = BTreeMap<String, Value>;
```
so this should work? (question mark)
```yaml
  - trigger: ":jsscript"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - nvm run
            - /path/to/your/script.py
```
Feel free to open an issue or ask in the [Discord](https://discord.gg/4QARseMS6k) to follow up easily
