### ISSUE TITLE
Possible to add support for bash in Windows Terminal on Win10

### ISSUE THREAD

**Issue by TSSlade** [federico-terzi/espanso#521]
I'm accustomed to working with bash on Ubuntu and MacOS, and for some reason really struggle with Powershell and Cmd. Insufficient permissions on the work laptop to run WSL, although I'm perfectly able to run Windows Terminal with a git-bash shell within it.

Would it be possible for espanso to support the bash shell on Windows?

**Comment by federico-terzi** [comment]
Hey @TSSlade,

Sorry for the late reply! How do you use bash on Windows? Do you simply execute `bash`?
If that's the case, you might try to specify `shell: wsl` anyway.
You see, under the hoods, when you specify the WSL shell espanso just invokes `bash -c <your command>`.
So as long as you have `bash` in the path, it should be working

Cheers :)

**Comment by TSSlade** [comment]
@federico-terzi - yeah, I just have a 'profile' in WindowsTerminal that points at the git-bash executable and opens up a pane running bash. And yes, that bash executable is on the path. I'll give the `wsl` approach a try and see if that works instead.

Current workaround for what I was trying to do involved writing a python script and executing it, but there's seriously non-trivial delays in spinning that up that make for a bit of a herky-jerky experience. Hopefully the bash approach will be faster.

**Comment by Wittionary** [comment]
@TSSlade 
Prefixing my command with "wsl" was enough to do the trick for me though I haven't tested it with multiple args. Let me know how it goes!

Example:
```yaml
  - trigger: ";;pwd"
    replace: "{{pwd}}"
    vars:
      - name: pwd
        type: shell
        params:
          cmd: "wsl pwd"
```

So what normally returns:
```
Path                                        
----                                        
C:\Users\wittionary\AppData\Local\Programs\espanso
```
becomes
```
/mnt/c/Users/wittionary/AppData/Local/Programs/espanso
```

**Comment by TSSlade** [comment]
@federico-terzi : Not sure things are working as expected per the above. Here are the configs:

```
  # Breadcrumb
  - trigger: ";bc"
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo `date -v -1d \"+[[%Y-%m-%d|<< Yesterday]]\"`' | '`date -v +1d \"+[[%Y-%m-%d|Tomorrow >>]]\"`"
          shell: wsl
          # cmd: (echo "[[$((Get-Date).AddDays(-1) | Get-Date -UFormat "%Y-%m-%d")|<< Yesterday]] | [[$((Get-Date).AddDays(+1) | Get-Date -UFormat "%Y-%m-%d")|Tomorrow >>]]")
          # shell: powershell
```

When I run it with the `shell: wsl` option, I get back " | ". When I run it with `shell: powershell`, I get the expected result:
![image](https://user-images.githubusercontent.com/3211478/100615877-195ad600-32cd-11eb-9771-a968c62fd2a1.png)

@Wittionary: when I try your approach - `cmd: wsl echo all-the-rest-here` - I just get a ` ` (blank space) as output.

For what it's worth, this is all being run in the context of a filter that enables these commands for Obsidian.md but not other applications.

**Comment by federico-terzi** [comment]
@TSSlade thanks for experimenting!

> when I try your approach - cmd: wsl echo all-the-rest-here - I just get a (blank space) as output.

If you don't have WSL installed, that's unlikely to produce some result :) Could you please try with:

```
cmd: bash -c 'echo hello'
```

If that works, then it's just a matter of escaping all those quotes in your command :)

**Comment by TSSlade** [comment]
> If that's the case, you might try to specify shell: wsl anyway.
You see, under the hoods, when you specify the WSL shell espanso just invokes bash -c <your command>.
So as long as you have bash in the path, it should be working

Yeah, it seemed odd to me that your recommendation was to try specifying shell as `wsl`, but I am willing to follow directions. ;-)

```
(base) tslade@my-computer:~$ which bash
/usr/bin/bash
```
Given the following overall setup:
```yaml
      - name: output
        type: shell
        params:
          # cmd: "bash -c echo `date -v -1d \"+[[%Y-%m-%d|<< Yesterday]]\"`' | '`date -v +1d \"+[[%Y-%m-%d|Tomorrow >>]]\"`"
          # cmd: bash -c echo "$(date -d 'yesterday' +[[%Y-%m-%d)" '|<< Yesterday]] | ' "$(date -d 'tomorrow' +[[%Y-%m-%d)" '| Tomorrow >>]'
          # cmd: bash -c 'echo hello'
          # shell: wsl
          # cmd: (echo "[[$((Get-Date).AddDays(-1) | Get-Date -UFormat "%Y-%m-%d")|<< Yesterday]] | [[$((Get-Date).AddDays(+1) | Get-Date -UFormat "%Y-%m-%d")|Tomorrow >>]]")
          # shell: powershell

```

...differing values of `cmd:` and `shell:` give results as follow:

Does the thing work via Powershell? Yes.
```
          # cmd: (echo "[[$((Get-Date).AddDays(-1) | Get-Date -UFormat "%Y-%m-%d")|<< Yesterday]] | [[$((Get-Date).AddDays(+1) | Get-Date -UFormat "%Y-%m-%d")|Tomorrow >>]]")
          # shell: powershell
# Result:
#   [[2020-11-30|<< Yesterday]] | [[2020-12-02|Tomorrow >>]] 
```
Does the thing work via bash? Yes via the CLI.
```
(base) tslade@my-computer-name:~$ echo "$(date -d 'yesterday' +[[%Y-%m-%d)" '|<< Yesterday]] | ' "$(date -d 'tomorrow' +[[%Y-%m-%d)" '| Tomorrow >>]'
# Result:
# [[2020-11-30 |<< Yesterday]] |  [[2020-12-02 | Tomorrow >>]
```
Not via espanso.
```
          cmd: bash -c echo "$(date -d 'yesterday' +[[%Y-%m-%d)" '|<< Yesterday]] | ' "$(date -d 'tomorrow' +[[%Y-%m-%d)" '| Tomorrow >>]'
          shell: wsl

# Result:
# {a blank space}
```
No error in the log, no error in the terminal. Just a blank space.

Can we reach bash this way? Yes.
```
          cmd: bash -c 'echo hello'
          shell: wsl

# Result: 
# hello 
```

**Comment by Wittionary** [comment]
I'm able to get this to fire in Obsidian (that forum thread got me to install Espanso too haha) on Windows 10 with WSL:
```yaml
  # Breadcrumb
  - trigger: ";;bread"
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo \"$(date -d 'yesterday' +[[%Y-%m-%d)\" '|<< Yesterday]] | ' \"$(date -d 'tomorrow' +[[%Y-%m-%d)\" '| Tomorrow >>]'"
          shell: wsl
```

The only oddity I've found is that I have to type an extra space at the end of the word which puts a space just before the final "]".
