### ISSUE TITLE
Support multiple line selections in form list

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#525]
Pasting a user request:

I’m running into a limitation with forms and wanted to see if the answer exists. Below is some example code. Ignore any bad formatting. I’m on mobile. I want the ability to select and arbitrary number of choices. In some cases I might need first choice. Sometimes I’ll need second choice and fourth choice. I might even need all of the four choices.

As far as I can tell, with type:list you can only select a single choice. Is there another type of form that lets you select multiple choices, or perhaps another parameter for the form?

```
- trigger: ":form"
form: |
  {{choices}}
form_fields:
  choices:
    type: list
    values:
      - First choice
      - Second choice
      - Third choice
      - Fourth choice
```
