### ISSUE TITLE
Nested Matches Image do not work

### ISSUE THREAD

**Issue by aivoo** [federico-terzi/espanso#530]
```
  - trigger: ":espanso"
    image_path : "C:/Users/Administrator/Desktop/1.png"

  - trigger: ":one"
    replace: "nested"
  
  - trigger: ":nested"
    replace: "This is a {{text}} {{image}} match"
    vars:
      - name: text
        type: match
        params:
          trigger: ":espanso"
      - name: image
        type: match
        params:
          trigger: ":espanso"
```
The **Image** could not be sent successfully

System: Windows 10
