### ISSUE TITLE
Feedback Wanted: Removing Passive Mode

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#540]
Hi guys,

I'm planning to do a big rewrite of the espanso core in the upcoming months to fix some longstanding problems. As part of this "clean up", I'm also considering removing Passive Mode, as it always felt pretty hacky, and its original purpose (having arguments inside matches) can be now achieved using Forms.
Removing Passive Mode would make the core cleaner and most likely less prone to errors.

* If you are **against** this choice (and you want to keep Passive Mode), place a thumbs down reaction to this post
* If you are **ok** removing passive mode, place a thumbs up

**Comment by MikhailTNY** [comment]
Didn't even realize it existed and on the docs, it did say the feature was experimental. I rather Espanso stay lean and focused at doing one task the best.

**Comment by s373r** [comment]
sad news for me :(

a part of my workflow heavily depends on the passive mode replacement feature

more context:
- I use obsidian.md and have tons of templates
- as you might have guessed, these templates contain passive commands like `:obsidian_paste_breadcrumb`, `:obsidian_add_meetings_from_gcal`, etc 
- after loading templates, a simple combination (`Ctrl + A` & double `Ctrl`) makes a little magic for me

just wanted to note, the passive mode is (was?) a lifesaver sometimes

anyway, thanks a lot for the project/documentation! you did definitely great job!

and have good vibes during clean-up/refactoring

**Comment by zealiao** [comment]
I don't know why that the passive mode does't work on my Windows10 and Linux(Deepin), but I think this mode will be very useful to me.

Some reasons like @s373r, and the most important is that I can do much of things with Python by reciving arguments.

Please don't remove it,  just make it more perfect! Thank you!

**Comment by matgrioni** [comment]
I think a huge "power user" feature of espanso is the ability to run scripts, and along with that comes providing arguments to the scripts to make them much more flexible. The form functionality keeps this in part, but I think that keeping everything text based also provides some niceties (less keyboard gymnastics for example :) ).

I see in #118 that the idea was floated of using a termination characters to signal to espanso that the trigger is done. This would mean that the same functionality in passive mode could be provided in real time, and all in the cli. The original proposal was for using a regex. However in this case, (assuming no lookahead/behind support) a single character regex is just a set of acceptable characters, which I think helps assuage concerns about real time performance since I assume this type of comparison is already what espanso is doing.

I can see that the choices here have to be taken with serious consideration as explained in #118, but at the base of it, I'm not sure how a final '//' as the final termination sequence would not solve these issues at the least. The first is needed to signal the end of the current argument (can be escaped as \/ with '\/' being escaped as \\/). All of this could also be included or excluded behind a flag, so that those that wish to continue using forms can.

Sorry for the ramblings, hopefully that was helpful. :) For what it's worth also, my vote is to keep passive mode, since it opens up a use case beyond arguments, allowing easy use of templated files for example.

**Comment by federico-terzi** [comment]
@matgrioni Thank you for the detailed feedback! I'm currently working on a major refactor, and as part of that, I'm also changing the implementation of the matcher module. I'll make sure to experiment with some approaches to see whether a "lightweight" regex engine could be possible. I can't promise anything, but I'll definitely have a look at it :)

**Comment by glgoose** [comment]
I have a use case that requires arguments. Could perhaps be helpful to have another specific case to consider for designing the rewrite of multiple argument support.

**Use-case**: I want to search something on a specific site without going to the specific site and having to type it in the search bar there
**Current solution**: in brave/chrome ([see docs](https://support.google.com/chrome/answer/95426?co=GENIE.Platform%3DDesktop&hl=en)) & firefox I can add shortcuts that fill in the query in the search URL, which works great but..
**Problem w/ current solutions**: 
  * differences per browser:
    * triggers: in brave I can just type space after the trigger, in firefox it's tab
    * settings: in brave it's easily configurable, firefox is a bit hacky with bookmarks & keywords inside
  * can't easily sync settings between browsers or devices (i.e. no central place to adjust all settings)
  * can't easily back these configurations up

## Example
Search for a 'text expander' on GitHub.

**In Chrome/Brave (with my settings):**
type `gh` + SPACE + `text expander` + ENTER
→ immediately goes to `https://github.com/search?q=text+expander`

Works well and doesn't require a lot of keystrokes.

So I've been trying to find a way to do this with espanso. I came across passive mode, though couldn't get it to work and looking for a solution to make it work with espanso I found this issue thread.

**Example of how I would want it to work with espanso:**
type `gh:text expander:`
→ immediately expands to `https://github.com/search?q=text+expander` upon typing last delimiter `:`

OR

type `gh` + TAB + `text expander`+ ENTER
-> expands to `https://github.com/search?q=text+expander`
In this case TAB would work as a second signaler to allow the input of an argument
  * support multiple arguments by:
    * pressing TAB → clears first argument, allowing you to type the next arg OR separate args by delimiter e.g. `,`
    * end argument input by pressing ENTER

**feature-request**: Would be great if you could automatically have a keystroke follow immediately after expansion e.g. ENTER (without having to type it)
So that in our example above an ENTER would automatically follow after the URL so that you go to the SERP.

## Configuration
What would be nice if you could configure smth like:
file: `$CONFIG$/user/search.yml`
```yaml
filter_title: ["Brave", "Firefox"]

global_vars:
   # would be nice if `query` below wouldn't need to be declared like this
  - name: query
    type: shell
    params:
      cmd: "echo $0$"
      inject_args: true
  
  # need to encode the query e.g. replace ' ' (space) with '+'
  - name: query_enc
    type: shell
    params:
       # if possible ideally could just reference $0$ below directly without needing the `query` var
      cmd: >
        echo python3 -c "import sys, urllib.parse as ul;
        print (ul.quote_plus($ESPANSO_QUERY))"    

matches:
  # `gh:text expander:` -> `https://github.com/search?q=text+expander`
  - trigger: "gh:$0$:"    # $0$ syntax would automatically declare it as a variable
    replace: "https://github.com/search?q={{query_enc}}"
    # ideally also the vars below could be omitted because they are global but I think currently it is required
    # saw this at: https://espanso.org/docs/matches/#advanced-topics
    vars:
      - name: query
        type: global
      - name: query_enc
        type: global

  # `imdb` + TAB + `dark knight` + ENTER -> `https://www.imdb.com/find?q=dark+knight` + ENTER
  - trigger: "imdb%TAB%$0$%ENTER%"    # there's probably a cleaner/nicer way to indicate keys
    replace: "https://www.imdb.com/find?q={{query_enc}}"
    action-end: "%ENTER%"    # after expansion execute key stroke
    # omitted the global vars here
```

## Solution with espanso would work if
* it's possible to expand immediately upon typing the last delimiter (i.e. if passive is not required for multi arguments)
    * otherwise it's too cumbersome, e.g. selecting the text + double pressing some key
 * it doesn't require a lot of extra keystrokes over how it's currently be implemented in browsers (e.g. trigger + space + query + enter)

**Comment by 4lch4** [comment]
@glgoose, it's a known issue the docs are a bit out of date and I've taken it upon myself to try and get them updated. Thanks for mentioning what you found! I'll be sure to make a note and get this addressed :)

**Comment by federico-terzi** [comment]
@glgoose Thank you for the feedback! Perhaps, the upcoming Regex triggers will solve your use case, so stay tuned!

**Comment by JPUnD** [comment]
I'm unsure if mentioned so far, but the passive mode was used to behave like a function, but having something like:
```
- trigger: ":echo($0, $1)"
  replace: "{{output}}"
  vars:
    - name: output
      type: shell
      params:
        cmd: "echo $0 && echo $1"
```

Would work as expected, considering that espanso would only trigger after the final bracket `)` is closed. This would also allow you to overload the function making room for optional arguments.

**Comment by Orcomp** [comment]
Just discovered passive mode and went searching to see if there was a trigger option. (Instead of CTRL + A and double press CTRL)

Simple regex triggers would be enough. 
I am planning to write a few console applications that can process a bunch of args.

All I would need is:

```
- trigger: ":vs($0)"
  replace: "{{output}}"
  vars:
    - name: output
      type: shell
      params:
        cmd: "vs.exe $0"
```
I would use this to manage all my Visual Studio shortcodes. 

Ideally it will simply trigger as soon as the last parenthesis is closed.
