### ISSUE TITLE
Problem with expanding matches in espanso v0.7.3

### ISSUE THREAD

**Issue by online** [federico-terzi/espanso#543]
Hello.

The problem can be seen in this video https://youtu.be/3DHMEyIL8FA. Before that, I had a problem with expanding matches in Telegram Desktop. I’m using Ubuntu 20.04.

Here is my config from file ~/.config/espanso/default.yml
```yml
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":дд"
    replace: "Добрый день.\n\n"

  - trigger: ":ду"
    replace: "Доброе утро.\n\n"

  - trigger: ":дв"
    replace: "Добрый вечер.\n\n"

  - trigger: "Здр"
    replace: "Здравствуйте.\n\n"

  # HTML теги
  - trigger: ":a"
    replace: "<a href='{{clipboard}}'>$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":b"
    replace: "<b>$|$</b>"

  - trigger: ":code"
    replace: "<code>$|$</code>"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

```
