### ISSUE TITLE
Parse markdown/html at paste-time?

### ISSUE THREAD

**Issue by j6k4m8** [federico-terzi/espanso#553]
My understanding is that this is not quite possible with the current Rich-Text / Markdown support, but I am hoping I'm wrong!

I'd love for the following to work:

```yml
    - trigger: ":paste-my-markdown:"
      markdown: "{{clipboard}}"
      vars:
        - name: "clipboard"
          type: "clipboard"
```

In other words:
1. Replace the substitution text with the contents of my clipboard
2. Convert the markdown to rich text
3. Paste the rich text at the cursor

My understanding is that this is not possible because the markdown is converted when espanso starts up, NOT at paste time; is that a correct assumption? Is this something you'd consider making possible in the future?
