### ISSUE TITLE
Auto closing curly/square brackets don’t work

### ISSUE THREAD

**Issue by karkraeg** [federico-terzi/espanso#560]
In my `default.yml` I have configured the following:

```yml
  - trigger: "("
    replace: "($|$)"
  - trigger: "["
    replace: "[$|$]"
  - trigger: "{"
    replace: "{$|$}"
  - trigger: "`"
    replace: "`$|$`"
```

But only the auto-closing round brackets work. Typing for example curly brackets results in deleted text:

https://user-images.githubusercontent.com/8436596/103572420-d17f2e00-4ecc-11eb-91aa-7831cac261d5.mp4

What am I missing or is this a known issue? Thanks!
