### ISSUE TITLE
Passive_mode $0 return "sh" 

### ISSUE THREAD

**Issue by snakewa** [federico-terzi/espanso#564]
Version: espanso 0.7.3
OS: MacOS Big Sur 10.0.1

Pass mode only works for replace. If I try to access arguments in shell type variable, arguments are not passed to the command.

```
enable_passive: true
auto_restart: true
passive_key: RIGHT_META
matches:
  - trigger: ":rev"
    replace: "$0$ - $1$ - $2$ - {{output}} - "
    passive_only: true
    force
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo \"[$0][$1][$2]\""
```

expended as the following:

```
abc - 123 - ddd - [sh][][] - 
```

expecting:
```
abc - 123 - ddd - [abc][123][ddd] - 
```

**Comment by federico-terzi** [comment]
Hey @snakewa,

You might be looking for the `inject_args` option :)

```yaml
  - trigger: ":rev"
    replace: "$0$ - $1$ - $2$ - {{output}} - "
    passive_only: true
    force_clipboard: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo \"[$0][$1][$2]\""
          inject_args: true
```

Cheers :)
