### ISSUE TITLE
Passive mode argument expands $0 to "bash"

### ISSUE THREAD

**Issue by jmiskovic** [federico-terzi/espanso#582]
On Fedora Linux, espanso v0.7.3, using example from online documentation:

```yaml
- trigger: ":rev"
  replace: "{{output}}"
  passive_only: true
  vars:
    - name: output
      type: shell
      params:
        cmd: "echo $0 | rev"
        trim: true
```

Testing with input text `:rev/123/`

The expected replacement would be `321`, but instead it's replaced with `hsab`.

It seems `$0` expands to the name of shell process, and passive mode argument is not accessible from shell.

**Comment by jmiskovic** [comment]
Since commit 1431145 the shell commands require `inject_args` parameter to be set to true.

```yaml
  - trigger: ":rev"
    replace: "{{output}}"
    passive_only: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $0 | rev"
          trim: true
          inject_args: true
```

Since code behaves as expected this issue is just against online docs.
