### ISSUE TITLE
Reference Value From Triggers

### ISSUE THREAD

**Issue by SSimpl3** [federico-terzi/espanso#585]
Would like an feature where we could reference value from triggers
It's useful when it's used like these, I could create each rule one by one but that would be inefficient 

- a apple -> an apple
- a elephant -> an elephant
- an feature -> a feature

```yml
- triggers: ["a a", "a e", "a u", "a e","a o"]
  replace: "an {{reference}}"
  propagate_case: true
  word: true
```

ty for your hardwork

**Comment by federico-terzi** [comment]
Hey @SSimpl3,

Thank you for the feedback! Could you please elaborate on your use-case a bit more? I'm not sure I properly understand it :)

Cheers :)

**Comment by SSimpl3** [comment]
@federico-terzi
I just realized that my use case needs regex to be available for this to have value or it's going to be implemented somehow during the creation of regex, so let's assume regex is implemented and we can take value from trigger

Use case 1 (Vowel Article Correction):
```yml
- trigger: "a {{/[aiueo]/}}"
  replace: "an {{reference}}"
  vars:
   - name: reference
     type: trigger.0
  propagate_case: true
  word: true
```
trigger.0 is referencing the first text from `- trigger:` encased with {{}}
Input -> Result (The bold character is the reference)
- a `a` -> an `a`
- a `i` -> an `i`
- a `u` -> an `u`

Use case 2 (Money Abbreviation):
```yml
- trigger: "{{/[0-9]/}}k"
  replace: "{{ref}}000"
  vars:
   - name: ref
     type: trigger.0
```

- `1`k -> `1`000
- `2`k -> `2`000
- 1`0`k -> 1`0`000

Use case 3 (Unit of Temperature):
```yml
- trigger: "{{/\d\d\d/}}:temp"
  replace: "{{ref}}°C, {{fahrenheit}}°F"
  vars:
   - name: ref
     type: trigger.0
   - name: fahrenheit
     type: shell
     params:
             cmd: "insert command to convert {{ref}} using Celsius to Fahrenheit formula"
```

- `100`:temp -> `100`°C, 212°F
