### ISSUE TITLE
Capitalize Each Word and Lowercase for Propagate Case

### ISSUE THREAD

**Issue by SSimpl3** [federico-terzi/espanso#586]
Perhaps it could be added through propagate case or something
My idea:
```yml
- trigger: ":up"
  replace: "hey my name is ESPANSO"
  propagate_case: [true, true]
```
First boolean if true, typing `:up` would result `hey my name is espanso`
if false, typing `:up` would result `hey my name is ESPANSO`

Second boolean if true, typing `:Up` would result `Hey My Name Is ESPANSO`
if false, typing `:Up` would result `Hey my name is ESPANSO`

Typing `:UP` would result `HEY MY NAME IS ESPANSO`

Use case:
Someone told me to lowercase the filename before submitting a doc, so I cut the filename to clipboard, then I type `:up` to rename the file

**Comment by federico-terzi** [comment]
Hey @SSimpl3,

Thank you for the feedback! Although I can definitely see how this feature could be useful, I'm sure not many people would benefit from it, so it's unlikely that this could be made part of espanso. For your particular use-case, probably the easiest solution is to define multiple matches:

```yaml
- trigger: ":up"
  replace: "hey my name is ESPANSO"

- trigger: ":Up"
  replace: "Hey My Name Is ESPANSO"

- trigger: ":UP"
  replace: "HEY MY NAME IS ESPANSO"
```

Cheers :)
