### ISSUE TITLE
Espanso shell commands do not work without admin rights

### ISSUE THREAD

**Issue by nobee** [federico-terzi/espanso#587]
Is it possible to have espanso run shell commands as administrator? I use my work laptop which requires elevated rights to run Windows PowerShell.

**Comment by jczanfona** [comment]
The default interpreter is **PowerShell**, but you can also use **cmd** if you specify it in the *shell* parameter:
```
  - trigger: ":mydate"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date /t"
          shell: cmd
```
