### ISSUE TITLE
Espanso should warn if there are rules with the same trigger

### ISSUE THREAD

**Issue by fstamour** [federico-terzi/espanso#601]
For example:

```yml
  - trigger: ";tld"
    replace: "Two Letter Acronym"

  - trigger: ";tld"
    replace: "Three Letter Acronym"

  - trigger: ";tld"
    replace: "Top Level Domain"
```

The current behaviour is just to happily load the configuration file. It would be nice if it still load the file, but warn the user about conflicting rules.

This would be a nice user experience improvement.
