### ISSUE TITLE
U+FE0F seems not supported and is replaced to U+7FFF for some reason

### ISSUE THREAD

**Issue by alkuzad** [federico-terzi/espanso#624]
Example package has wttr.in example which works under Windows Terminal normally but produces invalid gliph when produced via espanso

Espanso:
`Legnica, Poland: ⛅翿  +5°C`

Directly:
`Legnica, Poland: ⛅️  +5°C`

U+FE0F is variant selector that forces preceeding character to be displayed as coloured image. In this case it does not seem to be problem as it displays correctly, just with incorrect output.

Trigger config:
```
- trigger: ":wttrin"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'C:\Windows\System32\curl.exe https://wttr.in?format="%l:+%c+%t"'
```

**Comment by federico-terzi** [comment]
Hey @alkuzad,

Thanks for reporting this issue! Could you please try with the force_clipboard mode and see if that helps?

```yaml
  - trigger: ":wttrin"
    replace: "{{output}}"
    force_clipboard: true
    vars:
      - name: output
        type: shell
        params:
          cmd: 'C:\Windows\System32\curl.exe https://wttr.in?format="%l:+%c+%t"'
```

Cheers :)
