### ISSUE TITLE
Enable propagate_case to capitalise each word of a multi-word replacement string

### ISSUE THREAD

**Issue by emmaworthington** [federico-terzi/espanso#625]
E.g., have

```
- trigger: ";ols"
  replace: "ordinary least squares"
  propagate_case: true
```

produce 'Ordinary Least Squares' rather than 'Ordinary least squares', or enable another option to allow this.

**Comment by federico-terzi** [comment]
Hey @emmaworthington,

Thank you for the proposal! I'll add it to the roadmap

Cheers :)

**Comment by federico-terzi** [comment]
Hey @emmaworthington,

The new alpha v2 release now comes with the `uppercase_style` option which handles this use-case as well, for example, you can define a match as:

```yaml
 - trigger: ";ols"
   replace: "ordinary least squares"
   uppercase_style: "capitalize_words"
   propagate_case: true
```

which gets expanded to "Ordinary Least Squares" after typing `;Ols`

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
