### ISSUE TITLE
Passive Mode matches cant process arguments

### ISSUE THREAD

**Issue by Miko4** [federico-terzi/espanso#629]
I have:
  - Ubuntu 20.04.2 
  - installed espanso via snap
  - added the ":rev" example from https://espanso.org/docs/passive-mode/.
  
The Problem:

$0 expands to the name of the shell (bash in my case). so ":rev/hello/" expands to "hsab", not to "olleh", as shown in the documentation. Other attempts to access the arguments ($1, $1$, escaping the dollar, using type: script have not been successful.)

**Comment by federico-terzi** [comment]
Hey @Miko4,

Thanks for reporting this issue! I suspect the docs are not updated, as you might need to add the `inject_args: true` option:

```yaml
- trigger: ":rev"
  replace: "{{output}}"
  passive_only: true
  vars:
    - name: output
      type: shell
      params:
        cmd: "echo $0 | rev"
        inject_args: true
        trim: true
```

That said, keep in mind that passive mode is likely to be removed in the next major version, so things will change. The new Regex trigger should replace most passive-mode use-cases.

Cheers :)
