### ISSUE TITLE
Is it possible to have a global pre-trigger?

### ISSUE THREAD

**Issue by JPUnD** [federico-terzi/espanso#632]
Hi there,

Most packages use the `:` pre-trigger (i don't know what to call it, but i think you understand what i mean), for most of the use cases i imagine having the option for each user to set their own pre-trigger and make pre-trigger agnostic packages would be great.

As a small example, a given package has the following match:
```
matches:
  - trigger: "$pre_trigger$in"
    replace: "∈"
```

User A as their espanso config file like so:
```
pre_trigger: "\\"
```

So when he types `\\int` it expands to ∈

User B on the other hand, due to some personal preference of conflict with a given programming language, has the following in his config file:
```
pre_trigger: "»"
```

So naturally when he types `»in` it gets expanded to ∈

**Comment by federico-terzi** [comment]
Hey @JPUnD,

Thank you for the feedback! Interesting proposal, I can see how that might be useful. Let's add it to the roadmap :)

Cheers :)

**Comment by JPUnD** [comment]
Great, thanks!

Is the roadmap available to the public? 
There's one available on github in the issues, but that's the long-term roadmap.

**Comment by JeppeKlitgaard** [comment]
Alongside this feature, I think it would be fantastic if `espanso` supported global variables in triggers in general (and the `$PT$` or whatever would be the __conventional__ default for 'pre-triggers'.

I personally use a 'post-trigger' as well, but I understand why many people wouldn't want to do this.

I would like to be able to put:

```yaml
# in default.yml
global_vars:
  - name: "PRE"
    type: "symbol"
    value: ":"
  - name: "POST"
    type: "symbol"
    value: " 
```

And:
```yaml
# in user/mymatches
name: mymatches
parent: default

matches:
  # Dashes
  - trigger: "{{PRE}}emdash{{POST}}"
    replace: "—"
```

You might have different pretriggers for different type of letter replacements:

```yaml
# in default.yml
global_vars:
  - name: "PRE"
    type: "symbol"
    value: ":"
  - name: "PRE_GREEK"
    type: "symbol"
    value: "*"
  - name: "POST"
    type: "symbol"
    value: " 
```

Essentially this would change the issue to be "implement variables for triggers" and along that implement a conventional variable for the pre-trigger symbol.

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard,

Thank you for the feedback! Having global vars _inside_ the triggers would be pretty tricky, as the variable resolution happens much later in the process compared to the trigger detection.
That said, having a post-trigger as well could be definitely implemented :)

> Some users (myself included) would probably also like different pre/post-triggers for different groups of matches, so perhaps the convention should be PRE_<name of package>

After the next release #594 is implemented, I was planning to add a feature to solve exactly that problem, so stay tuned for that!

The idea would be to have a `defaults` property that defines the default properties for the file matches:

```yaml

defaults:
  pre_trigger: ":"
  post_trigger: "."

matches:
  - trigger: "hello"
    replace: "world"
  - trigger: "foo"
    replace: "bar"
```

Once that is implemented, both snippets would have the `:` prefix and `.` postfix, which should solve your problem

Cheers :)

**Comment by JeppeKlitgaard** [comment]
@federico-terzi 

I completely forgot to start out with a great big thank you for this excellent project!

I was thinking variables could reasonably be implemented by loading the YAML configuration and then subsequently using some logic to replace `{{string_here}}`-type templates in the trigger keys with the relevant variable from the already parsed configuration. I completely understand if you feel that this is a somewhat inelegant approach though. I haven't had a look at the project code and I am not well-versed in Rust, but I thought this might be a viable approach (albeit _slightly_ hacky).

Considerations:
- Corner cases like using `{{` or `}}` as part of a trigger
- Hierarchy of resolution (probably default.yml should have highest priority such that it can override packages and user files)

This would mean that templates are only resolved once, which is just after the config is loaded.

From your example, (to my understanding) it is not possible to mix pre/post-triggers in the same file, or exempt an individual trigger from, for example, the post-trigger.

Anyway, these were just my thoughts. There might be good reasons why they are non-sensical!

I am looking forward to seeing what new new features you come up with!

**Comment by JeppeKlitgaard** [comment]
This is turning into a whole discussion of it's own, but I couldn't help but look around for a good tool to use for generating configurations for accents and other digraphs dynamically and I landed on either:
- Python and the `mako` (this would just be for my own benefit and would be external to espanso)
- `jsonnet`

I am not sure if this is just me overthinking the automation part of the espanso config, but I would personally like to easily be able to implement a lot of digraphs in a semi-programmatic way (so some type of for loop would be appreciated for this).

I think `jsonnet` solves a lot of the use-cases where the current configuration setup is limited, which will only get worse as overriding definitions from packages will become more common with Espanso Hub.

There are `Rust`-bindings available. It is effectively a "A data templating language for app and tool developers" and it compiles to both JSON and YAML. This would mean that it could be integrated into the existing code base as:
- `.yml` files will be loaded as normal
- `.jsonnet` files will be compiled to `yml` and loaded.

The additional burden of implementing this _very_ powerful configuration tool would, if my cursory understanding of it is right, just be:
- Adding the logic to detect .jsonnet files
- Compile config load and then load the compiled YAML
- Documentation

See: https://jsonnet.org/

**Comment by federico-terzi** [comment]
@JeppeKlitgaard Thank you for the insightful comments!

I can see your point, but while I think there could be some use-cases in which a templating language over the standard configs might be useful, the additional burden might be difficult to justify. For example, we are also planning to introduce a GUI editor in the near future and having to deal with a templating language on top of the configs could make it incredibly difficult :)

Also, keep in mind that variables are _dynamic_. Every time you use a variable inside a match, it gets evaluated again. While this might seem unnecessary for simple, _static_ variables, it's necessary when those variables' values are the result of a shell or script evaluation: https://espanso.org/docs/matches/#shell-extension

That said, nothing stops you from building a small utility that "renders" custom YAML files to be fed to espanso :)

**Comment by rickalex21** [comment]
@federico-terzi This sounds like a good idea. My problem right now is that I can't use 'tab' in obsidian so the work around for now is to do `keyword\r` to trigger something. Is it possible to trigger on CTRL+Space in Linux ? When typing in markdown I insert links with the keyword 'here', go here. Another thing, tabstops like ultisnips would be very cool `${1:NAME}` ...`${2:Address}`... AFAIK: only one `$|$`. Thanks.

```yaml
global_vars:
  - name: mytrigger
    type: echo
    params:
      echo: CTRL+Space
matches:
# var don't work in trigger..., I presume this would be considered a post_trigger.
 - trigger: "here{{myTrigger}}"
    replace: "[here.]({{clipHere}})"
    vars:
      - name: "clipHere"
        type: "clipboard"
```
Now I would only have to type  "Go to this link here`Ctrl+Space`" and it would output:
```markdown
Go to this link [here](https://github.com/federico-terzi/espanso)
```
Thanks, keep up the great work.
