### ISSUE TITLE
txt files as replace/variable , maybe file extension

### ISSUE THREAD

**Issue by grenudi** [federico-terzi/espanso#638]
would be nice to have something like this: 
  
```
- trigger: ":instruction-outlook"
  replace: "Please use this instruction: \n{{file}}\n"
  vars:
    - name: file
      type: file
      params:
        relpath: "../blah/instructions/outlook-connect.txt"
        abspath: "c:/users/.../blah/instructions/outlook-connect.txt"
```
  
I could use git submodule in that way, with separate git for txt files with contents for replacements , instructions for example.
