### ISSUE TITLE
Multiple instances of espanso opening up

### ISSUE THREAD

**Issue by gtlsgamr** [federico-terzi/espanso#639]
Hello, I have a script which is run as a cmd for a form which is called on a trigger.
e.g. 
1. Type the trigger :form
2. A form comes up, where you enter variables
3. You click on submit, the value of form is used as arguments to the script.

What the script does is, it adds new triggers to the default.yml file. This seems to work for now, the only issue I'm facing is, calling the trigger once opens up 3 or 4 espanso forms. I am sharing the script and yml config below.

This is the script that is called on form submission
`#!/bin/sh
espansopath="${HOME}/.config/espanso"
espansofile="${espansopath}/default.yml"
triggerfile="${espansopath}/triggerfile.yml"
replacefile="${espansopath}/replacefile.yml"
trigger=$1
replace=$2
printf "%s" "$replace" > "$replacefile"
sed -i -e 's/^/                /' "$replacefile"
{ echo -e "\n\n  - trigger: \"$trigger\"";echo "    replace: |";cat "$replacefile";} >> "$espansofile"
`
This is the yml config for the form trigger

```
  - trigger: ":rev"
    replace: "{{reversed}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Trigger {{name}}
          Replace {{name2}}
        fields:
          name2:
            multiline: true
    - name: reversed
      type: shell
      params:
       cmd: '/bin/bash espansoedit.sh "$ESPANSO_FORM1_NAME" "$ESPANSO_FORM1_NAME2"'
```
