### ISSUE TITLE
Passive Mode outputs the word "bash"

### ISSUE THREAD

**Issue by AntoninJcb** [federico-terzi/espanso#654]
Hello, and thank you for your awesome tool!

I've just discovered your passive mode, but the output text is not my /arg1, but bash.
With the example of "echo $0 | rev", doing `:rev/hello/` outputs... `hsab`! (the string bash in reverse).

I am trying to replace every space character by an underscore, but I had the same problem using your example:
```
- trigger: ":under"
  replace: "{{output}}"
  passive_only: true
  vars:
    - name: output
    type: shell
    params:
      cmd: "echo $0 | tr ' ' '_'"
```
Input:
`:under/a random string/`
Output:
`bash`

My `default.yml` only contains the lines `enable_passive: true` and `passive_key: CTRL`.

Thank you for your help, and sorry if I've missed something!

Edit: I've tried it using LibreOffice, a Linux Prompt Dialog, my browser search bar and Kate text editor. I am not trying this on a console, as you mentioned it is not working anyway

**Comment by federico-terzi** [comment]
Hey @AntoninJcb,

Thanks for reporting this issue! You might want to specify the `inject_args: true` option:

```
- trigger: ":under"
  replace: "{{output}}"
  passive_only: true
  vars:
    - name: output
      type: shell
      params:
        inject_args: true
        cmd: "echo $0 | tr ' ' '_'"
```

Let me know if that helps! 

By the way, I'm closing this issue as passive mode is going away in the next release and this won't be relevant anymore. We'll have another alternative by then (regex triggers), but that's the topic for another issue.

Cheers :)
