### ISSUE TITLE
Fails when the replaced text contains pipes

### ISSUE THREAD

**Issue by mmngreco** [federico-terzi/espanso#655]
Hello, first of all, thank you for this amazing app. I'm using, ubuntu 20.04.

Here is my problem, I've written a trigger like the following:

```yaml
matches:
  - trigger: ":h"
    replace: "--help | less"
```

When I write `:h` I get the following:

```
--help 1 less
```

Notice the pipe "|" is replaced by "1". 

Others attemps with the same result:

```yaml
  - trigger: ":h"
    replace: "{{help}}"
    vars:
      - name: help
        type: shell
        params:
          cmd: "echo '--help | less'"

```

```yaml
  - trigger: ":h"
    replace: "--help \| less"

```

**Comment by federico-terzi** [comment]
Hey @mmngreco,

Thanks for reporting this issue! This might be related to https://github.com/federico-terzi/espanso/issues/569 and https://github.com/federico-terzi/espanso/issues/489
As a temporary workaround, you could try the `force_clipboard: true` option:

```yaml
matches:
  - trigger: ":h"
    replace: "--help | less"
    force_clipboard: true
```

Let me know if that helps! Closing in favor of the other two, feel free to reopen the issue if the problem persists

Cheers :)
