### ISSUE TITLE
Espanso get confused while changing keyboard layout on linux

### ISSUE THREAD

**Issue by beaussan** [federico-terzi/espanso#660]
## Description

While changing the keyboard layout in linux, espanso write the wrong output

## Steps to reproduce
* run `setxkmap us`
* Start espanso
* correct keys are sent
* run `setxkbmap fr`
* wrong keys are sent

## Workaround
Restart espanso every time you switch the keyboard layout

## Espanso config : 
```
toggle_key: OFF
backend: Auto
matches:
  - trigger: ":tod"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date --rfc-3339=date"
```
