### ISSUE TITLE
Pass var output to form

### ISSUE THREAD

**Issue by scottrobertson** [federico-terzi/espanso#665]
Hey

Sorry if I am missing something, but I tried searching for a while and could not find the answer.

I want to be able to pass the output from a script to a form. In this case, it's because I may want to make modifications to the form output before using the output. For example:

```
  - trigger: ":domain"
    replace: "{{email}}"
    vars:
      - name: email
        type: script
        params:
          args:
            - node
            - /Users/user/Library/Preferences/espanso/email_from_url.js

  - trigger: ":em"
    form: "{{domain}}@mydomain.com"
    vars:
      - name: domain
        type: match
        params:
          trigger: ":domain"
```

Running this, `domain` is not filled in on the form. However if replace `form:` with `replace:` it does output it.
