### ISSUE TITLE
Text and image

### ISSUE THREAD

**Issue by Duckbilled** [federico-terzi/espanso#676]
Is it possible to have a result where I both get a string of text and an image? For example:

Best regards,
path/to/signature.png

**Comment by federico-terzi** [comment]
Hey @Duckbilled,

> Is it possible to have a result where I both get a string of text and an image?

In theory, it can be done with the Rich text feature (available since version 0.7.3), but from my own testing, not every application accepts it. 

Firstly, you will need to get the DATA URL for your image, for example using this website: https://ezgif.com/image-to-datauri

Then, with a little bit of HTML magic:

```yml
  - trigger: ":sig"
    html: |
      <p>Best regards, </p>
      <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAYAAACLz2ctAAAYT3pUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjarZppdhu7doX/YxQZAvoDDAftWplBhp9vF2nasuX78pKYlkiRxSrgNLsByp3/+s/r/oN/1cfscrFWe62ef7nnHgcvmn/9ez0Hn5/fz7/x/oi/v7zvPh9E3ko8p9ef9byPH7xffn7B8vv9+fV9Z+t9nvY+Ufic+PmXdGW9fh/X3idK8fV+eP/t+vt7I/8ynfdPXO/Tvk/++9/ZCMYunC9FF08KyfO76SqJEaSeBs/6HVKJP94JqfE7pfB97Nzn5W/B+7z6LXZ+vN9PX0PhfH0fUH+L0fv9UH57P30uE7+MKPy88pcPLITqf/33S+zu3e3e85rdyJVIVfee1I+pPK84cBLK9Hyt8jB+Cq/teXQejSkuMrbJ5uSxXOghEu0bcthhhBvO87zCYog5nmg8x7hiet5ryWKP60lK1iPcaCRjO3IR0yJribfjZyzhuW5/rrdC48o7cGQMnCzwjT8e7rs3/zePz4nuVemG4NsnVowrqqYZhjKn3xxFQsJ9x7Q88X0e7pe68b8kNpHB8oS5McHh5+sUs4SftZWePCeOKz47/2qNYPt9AkLEtQuDCYkM+Ep5hxq8xUhJEMdGfgYjjynHSQZCKXEHd8lNSpXktKhr8x0Lz7GxxNfbQAuJKKkmIzW0C8nKuVA/lhs1NEoq2ZVSarHSSi+jppprqbVaFUYNS5atWDWzZt1GSy230mqz1lpvo8eegLDSazfXW+99DC46OPXg24MjxphxpplnmXXabLPPsSiflVdZddlqq6+x406b9t91m9tt9z1OOJTSyaeceuy008+41NpNN99y67Xbbr/jk7V3Vr9mLfyWuX/OWnhnTRnLz3H2M2u8bfbjFEFwUpQzMhZzIOOmDFDQUTnzLeQclTnlzPdIU5RI1kJRcnZQxshgPiGWGz65+5m5f8ybK/nfylv8W+acUvf/kTmn1L0z92fevsnaHg+jpCdB6kLF1KcLsHHAaSO2IU7618/jVM5YyjmMOC2rdC4TArNLI1ck+sTaYiWaK1jKffeQuQAjYzZ+jrl3HmtSD7O2ESyGkWOY0TbxL9OlWq4/JLTtW8/ccXUmQQCOP7Zv9LtEEtNXKpbKiiXtZ0gEst8dyumUmB/HWWbifDA3f/t5uum59ZHuCWWdXvR3usX4gu2ovy6AUM462dLl6sffOd2d7aY44tzJ/vGr2e6Ks+84L8kYhP8QKsiEiNxqLvp79l7hml0Lp1JXNnw5d6VWqGWYp948qLBTySFFcyvMXdrmTJ68n12pzcnUypyeGp38xKNA5Z0nYYFN8nzCkiehyXNbTv2VtxGevPUSYzZDmDRX+mIUIXpmfHwdfZOw7Xm3zj7iOe2dex7PK//9s/vbB+9nqjXYSqRg7Nmo8Axf1RsJbEByDAv9dA5K7qZRCW9NacxSQ2YQNBgdR6xyGdmgRDC51CQ4mPV6vnCZ+O1PnrOPc64toRVnLQLlMInt2lb9OTe1dkpG8rRyYdNDyd0yFo1pijq1TMpng5ZtbTqjuVNn1pl9UhZTnLkdYrvroTOZDYiT9kJPcCANrdmWmCdJtDFrjEyeU5Xq8m4lZP6vlf/aYoR9ZxrljswAGezgoiNkUGfPg2az7ajPQEPRPnlHAypKWEDUoJcHKLGsxzPD8XTazKOttfgy1xytHCKF0OtEy5Lr1N4sLVCqrdQ1S2/Ctgx2nUUhHPNhgak1+X3oG0IaKZ+zYFR6I1HIxXNix4XvLuEAnqXOM8vhe3Qjv6nFekhay7m3EFoFGG4+HHR7IauVup7EHpAE2FopoOEKFOErVm3/j2BpTrsevIUnNg00XAJV0f1pLZiGFJHxna8utHfsBG4CX33SXGPgEUY9o+QHIVB9/YTXq3XdGGiGsollq2GCa7DYvNa76bTW0clgLVhDemsg+SSLF9nDMH7FwQc+AvUuThob7koHmgJShlC+HJtxd2rzaZfRTvznTmvI4798wHwGAzhQY6s1g0gUJ/VqOca51lyZmqC+AYoIfky6369dV7NYyjwXjEg9ZmEZ6VAS6Z6SF8PKhtGZAcCDXSflZHOcY43plA1CtnklYIHfW8KGRoPaobRWJbko4kSjXOOcFKohWXeaKXEGP5/4d1Impn0S8Mqr+PdVAt7/+lznbaYy2/UWUI7Q6UvVoMDKVMFLgC3Ro+e2B0vyC0tSHl5YMmKyucKEY9qhRq2keUhwvR05QcdRR8uwi4AvLIJegFM4KSp8cVUMF4DlVZgVeQiAhxLBJppk0avNw4kpWptjHLTHBMAWKOo0p0Htx3+DbL97dj+hYh1bBUbCzbRxqZ0OV+I/UlyyJZGh0JN7mSDu5soRSBYgBhwIHQeZVj3MatBtdF0n2RBIb3FVqqAX4eS0QmwEJq/Qt6vQiyaNj57QO5SQig7r0qukFcUDICyVYgWN9t1xzDCmL1A8fuTPzp67U1VuQlFgBYDOKPJAg8GUNC4X3bv5BBSeSMUo3x3vDfDR57MhBffs6BoBTLxgNqV+8T42UGqbadD7Pa1L462dCkAB2tl9aBybkp/CQmUd/7Xk3C+1l2+l/S3QsEIu6gLSwVnQARXlh7G/EX0yNrwBN61IpWEkoglrHRoT9XfrHhAT/VhbrwmeGwtSDpEponcL4Zc4QsVRkuW2fgyvcTnzHWAxAUWMNnDKpDzK2IdZNENGMvg10zoSHrQa396d5kRDLLU8qiC2RywNREzhXYfMyrUtfP3JFaHSYEP41laQ1w/t4kGFXVTwAPURmwietNLTohFRdNTAJ0CQvcPkKJuZckWXjies9DknRdvAW8i9R7wUigygljIC+kBKXBGYA3CNU2haxA98tOf2WC7wscKGtSQpSBqQeqsM5hoa8Ga4bde41yJw/aIRjOAVAPm4aSDXHXEjBq3PDkyjJfbTvhyKMF8onNSLyhz5VfZBbhktMF+lgJCPPDt+/Ls8KDnER5uYvG1c+s4UOl1/CHZFw3ApJJn4BanR+IGtYQkUuFokt4Q6aI0RQhgNZdn8WbktL6zxhnbHcI4ezkAqwaNtn6KeWAhHpqOTkBgq+wH7CYvMF/EVkBepD9lTLpEKnlyl5obwnsa4VksXwgMIaaF1UBe0NemnyXBA96g3yCqd0hCyOVGZOIUYEI1oxVYNLXMt1lmGLoeZgQf63IVXoydzqSMWXp0M6fwB2TbCbWmumEfAQiHEy+pI8EGO5VAOtqofiAjjV9FKp2KRYG5A/hWNJPAqMjC0936ilNBlKH7OEw/ge0XiqPO71kuMjkX2+9+JFAkOqIOXlB31AuFtNA0iH2l+L3OVi9OShicoT9DIR5Gtm3AMMKIS4aiKwLOxyDi5XYyfTJ6MkTuTr+B1uiKVoSO5RKQbUPZnpHCWgtXLxCg8g12IfwWGAy+xTZdTx7SB1O3Qlx3jE2kfCBJNT9ELncsLnVXyAbmKzwUCwSjgF4GNReBaAOgRJOBghtu0ojQmkkPMq4IF/YmDtA5NS9H1nNE5Via6Ej+RASIZyUwjHmwIXUcLO3yDn7lT7Bh4+hVDrsEvwDGiqLnAXOho+L1LZtKoBEZERd+fS09BMwoFpqZfrZaVL00HIjE+wkaAO3ayUKQt4h8CXgJdMW2vBn4RIBOiD3gt4aU7/D6gkiviZxIJpZw9BprLbJw/iIRAx/0sKoWmUFJOwTjXBlii2lNwu7+ThBvFdZiCh25cN6Gnxf+ZKUFPML+ICgLsZUbEcmbA2ClsA8pjXodORFIzXzziaQwN4CH8h1MJKbdCOUkC3bz7ZfCgk9CbFMc2J/q4Inb6dei50pDpeLpJ8T+wwKm1Gqm6g+W4NDXCkPLJU3oEKVID8QdLhnCVsCD9AESm84hcYgd03EVR5wb8otoZKQcTvLMGrb8F9HZf0IhRrz+EWTgulaN1NaOkccK70dANekMjFwTnTuCtJF+PwJ5fL/aQoKaKMQxbvm1JmzvpLAjuPM76o4br780LINqJ+N81AEZKiUsuWr2mx4Wf7UKE72/0FT9M+tOFpQeVDIREuUGEOwOJGWqkRPFE9VA34EHpBZ8GvyNZsFi4I6S9NxpiCJ1hTqIPPBBdec2yAkEt5/OBaPH1EU3Nh1Q8p47mArWKWMTxoG/eDEPttfYNWNarPEWKIK9ORTK7DT9SrB27PrQQgWi4fm78lQiCbPS9mFudj9nA+J0jvsfcoMEB+VRfmINAmbgLtLxD7pX2qAIUNB0S6QzU/8Lc0RxATcYraxkn4wORFdA0FivZHi1vpoS4wzxj11HAqKIT4VHwEFnjqc8Gbhe8/uKjSvMDURik5eFqYEH8TWnJbnSuMRKdkhykA69S1fZ08gE56QIGj0gPQatLDJdgS+5iM2Y2qKBKvXCEQBNPqS5w8qeQZ6Bqb7aVMjbioJLvPAlBQuQBXBIrcSP/hcxCyx7mD0nN+7ZfMzl0i0exo8SGhz9r17qKWnMDgNj0ORZopWqjOJnNDZB9Y8zEgTrYeyatJyxHeVFS/YLGgFg9UA2JCW0xs6qVvk1dLLqygyDImUjb1Idr810QyHyEEmK0pD+4DHu34OenKDHoKsrxKUp98CrKkd5F+Xzo1J5wU9krYdy8lggPXu7AJEGLZhR2phEHYqKQ288H3v/4iAHwoYM/OAeqCIr3yGkkd3nFDyGU/1zlmPsMimlhvlvHCtBAge6XFyGG0Aq9hoEhS+kRDllLY4/rkAyQvntD0DdCIxSJCBRG9gkH1EK2CQ7isNsyXqcHbAfGnJISZ4gtsDqF0i54DnoL94v1wNmAkHvaDC1jE0L0OQfJOhQ4/ZhhOa5P8e2L+dSa0pIToF2pazwJoJRroVWPPC12Ey0SBa8I23WlPaBLIIvDCAgCHsuMB54LiqgjI3npGz8KKcK3Zy+rkoZDbyuyaPYivwBa5UPL1yhJUt62Cs5I3/pmwTXljlpyT4KF/uRwfxIcy48Ev4jh82HDS8CShz7WMuTdUAHZKmC2BytWMdptt6CclVTRQbiDGUBlH5YsG1mGWLZWPqg+uG1HNQGA0duM1rcj4Cg+T09yRXDXzsWgI7MJgcey7Q7G7Wd+G8Vc/sj+QaXFjBWlmXqgA32VbBTHCnyQG4XoItBpaPJSZUchw4F/WSBXQarQBeD1Cymzw7qgw2jghG1YG3VcpMVnDFo/9FriKVOLxXdszCDFIJY+PcYTmxYcgkW4szlgDVdhDQ8kdgUsp0GnRFLLxBRt1lIK+tAvdEpdoo8gK4ZMP3XD4hmD26Ijw4YvQJqAnGKGW9MFsmmH4PvEyaHmeY9QQamlnTeMgKOHGJgXomAUHCoMQk/oeRA5Lc7YZtKywcK508QFcMC0P6ZTuQRJ8QDYHDz1XQ3tkggMmI3E6rUyzbyRDkvmLzyLCGkhQCEwMrZUPdrM2sLSQW1iRXD375XQrCf3VfC9nnGPB3RD02JtE2JE6wmgZ6bQUz0EImtbGruFusBZjGjLqeVpj8Gj4TcBeTAUjUhckR0VXU4X970N06MaY258N56Mh0ocRXkl2jE6hPCm02G1g0BeUEpdBBqvTYtIXmDF4wALwVGNCsWEtUddLO3TTBQRI0QVOgjzyJUPeRRGS6GOjhh5pBc8QltoxyFq58EDOHRGhKByh/JH4+o+KCHBFY0YLIJepxYh3ivyvbVf0JUceiwUwloleqmPHJkVWWPozDxso46O77t62gG9gIrsCDSqj2DAvA9FSumCCIMSahiNFGLH+cidUOxPF65j7rNG+7Q5rh9RlUBu9AkNFerxkpj7peiUJQK/pbHa0oIbyFYTUBJ1lwZ+kiJDDPRcUXceXcPlU7KQtP1Vtb0RaFxrfBVf6F+ZMlsxGHVFzON2i3AMQNa07HKYJIp4xxV38bB+0PLBKmD9kN3TOmyj//N5lucZF8fMZ7GYOtJC3yrhh3PCYPX8mCcGjFjPwKyYa4teUd3XUJsFpMApRHDlTi12Hpe1xP4oWgRghdlwHstLsWPMpGCoT3gu8kXah3JFypJfLe8syu4VbAw3DvJPZ1RUOvQ8EujO0NF9qDGsP4U0Pd4sI4qoSRoCKUlgNnrLpZOwJNTP1b4FRIwEFmcF6uVAmx6lss7UtiW4ROVOzKw2GahIHBilL0qCsjX7oQU7JJWOO9RAocTx4EsrXSrx8xosFIj/Ai6w/YfixxWCNCkxkhXcGkEbh1H7vQiepKUma3hJEApYLtoPgIu1yJ9zJkALAOs+i79p4Fbrs+iNYB/BXqveUtBa9aY/FmAJghQtK1CaCHX6lLR3ugkmo19f/bN1U8brpfupWG5BuhvkHExKGXJMs9LrRFFeealftqzh0Q72jRvUmzTd0dbGcY1C0s6AlrwQpfQCGfLzxBj7vFATMZ9YUGARJW7MhTaZ+SnTOMBtOhkvspz2evim7uMxifVdcT/n25KgrWedXXtfFBBwkqUhoz9wWHTPxmxMmArTXiKf0iLaJwzyP9jAs5JvWi8tzxodxT4oZzrJlGrYtQO04NG4W4X/wHIbFqb6QG5lassIV49NWOmz4EF4Y/tTD7blUHeypHtsOkyro+sIuQBlDxx2+Ek0R4gBs0f5A9V5nYA1EP1A2fim1qtDkVMvQ6sL1HeUh6f8Q9QGg1rYNFq6YmiLbD4ocvckwciucp4FIKpSS6zppWE5zyw/FffZtG4aR0m+mC8wO1BRrfsJtV1kDeID06BNDpjvRPcgf5I7wjNory4PYByfrJNPCkubFIwJCkGyHMG9brJqVCwmCvYC+yGd6LBKWnp7LyldaWMA4dlq+ezRwsS/10PVrjd88uwDEtjgUgVkkPyIykes9RuevkOAZW15r4Ys7lrWwDjiSiLZAKB6R2nigXMkQx214mR+Tto7xuJhzt5xP1TJs6NatU2ekpZogIWuJfwC6qAMMKDZjBBq17AMGpE6yhBq2wEr1yEau9fsOU3vdFcIR8t80cM/XZtmFIXWDE+lWvxAbyEgL1ys9WzIfGtZWQNDPW2h39SiHGhH3+t+gan2RKC0CjTjUphM1c6HVjcB2lOLAyxwTIdepRs/KxH27XIiBntVrNHEcw4bnCINyqFr+cfxNyL6atUDrEXC5xf/DRC67+e+j6V1awaBMjAYU5Fb+BMMD34FX4CLxItUQQfgMHQngWoHX/6C3IRDSdn8ZjaxSZc/ogBe+r0W8q7dYZR3I2kMYiJh0YqpAysQuKFrEd+oGVR+wNfS30QXNiAbLz8Ayasrjag55bMgIeUMYHGUa0LVcw5GVkRvpl1jWF0rbEO+Htm8/aokJPf6WDFQOLuXAgIBPApivLagVUHvLeh5lCxtQRv88dqCpmuGKA8QDtoCGmiG6o72Ij+6crX/0/7a9PhGfFpB8zBqRnYQ+7shJdezmwCInoKDkKyKzBx3UlXDuj8Ipt5wmIvaLkBb+Yo3GjgriguNLw5MMvY/tCtJJoqQEcgAUcaACzTQuGGIUD/o7BJQBKQOz4UdQTmpegECWh4hcQk7Ckfib5SlxavK5fEK3vy5kQhrl7P7ZzsDEWQjf0ccX56LtuG8lmvXxmHMortFh9cuLvTk0Pkg7QYuGzPQ6lnhnSLoZ8oIm4Vq7HXAwqatrf4h6a8c7bTSmrV0ovtDgAYtV3n60hCXlWq7Hh3sn+qcuj9EwpsRtBtk5wAX/FSfEGQH5p+Ny+hjkFGmq8YeqQBE1CwIphUFTQD2xjxXYOa9nhAKiJG/2fH72zPa7+9MhNvHtJzkdIsLP1WrBLMX3QAGwulOx4vS61pOSGiH1h6BiDHUmvQFruSmY5BgzM/KqImAgTykzAA+x204NewrComTRMTNNW3HobrvDYfqjGvqXhRygxVG11Os5hHsRYqHzk7PLtLSzYuU3EEtoo10fLO4qXzw7Mcm7fnmzh/3zzcofO5HeO7Lokp0y5GMakn0ZwcvqeznjiMniaaNGwSR7gzAh5H5io+Q6NamA8CKaAJNi27QRBS9qozeWIhLgOouXEN1dwLwc93StA2EVHnuntGqwOvuGTPdrKO7Z1r1FEafCc2/8FzIIDTdpGAqNeyqb9hnP9CuwP4u0o1oGZxPy1oCiXVqTeBqx91rYxSJcGPqyuEu895hz6obBfnes/t5LI4dPJMIftaI6WX8dNdSACyerBOrVnk5+oO6WevlcH9AUnXdBTaaUVi56U9tO0P99MY5uPWxIDniQuNqDyCiv7puBXvGXYGXSIyem5g4OKdXvOcx9Gki3niPoBujqKPnvomDJYt4Bi1m4hKXcoGYocaz7hqLkmbhNo+0yur0ZNqzJiE+IQG12IhwTGhXTPabQfOZ//JOFr6IriJ4/w1MVZKXV3y5BQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+MJDxESIFcJKPcAABR+SURBVHja7Z15lFTVncc/r7q6qheqN3qhm6VZG0GQHUXjgoiWa4JB3A1oXOKUy5iZ44yZM5rJSdyNSxOPS2ImJq7jDtJRRBEQRUA2BWTrhqaB3ruqu7r2N3+8ZwwxNt1V9arue32/59Q5nAPUe/feT/3u7977+/0uSElJSUlJSUlJSUlJSUlJSUmlQIrsgn9QTbULKAEqgFFAuf7nUqAIGKB//pk69U8r0Ag0AIeAPfqfm3B7fLKTJYDfwFYATASm6Z/jddjygawkPy0AdOggbgM2AhuArbg97RJA68OmALnALOBM4AfABMAFZKTpraKATwdyNbACWAt04faoEkBrQFcGnAX8UAevUOB2q0CbDuJbwHLgiJVhVCwKXgEwF7hCh2+ASVvSqUP4AvC+FadqxULQKbo/dy2wQF88WEmHgFeAP+h+oyoBFAM8O+AGbgNOBZwWd5uCwCrgMaAGtyciAUwPeE7gEuB2YHIaFxLpUhTYBDwKvIrbE5QApgY8B3A+cI8+5fb3vUwV2Kr3x1LcnpAE0BjwbMApwK/1qVbqu1oF/AJYg9sTkwAmD75hOngLAIfkrEeF9MXKL3B79ksAEwMvE7gRuBsolmz1Sc3AL4GncHvCEsC+6N0nwKaMAxYDZ0g/LyH/8CPgX4ip2znvFuFe0Cak1bMpNwGfALMlfAkbmNnAJ9iUm/QZRVrAHuAbBDwOzJfgGWIN/w+4FbfnsATwu/DNAv4EjJasGKrdwDW4PWslgBp4CvBT4GG0yBQp4+UD7gB+n+4jPVua4XMCDwG/k/ClVC7gSeAhfQz6oQWsqc4DnpX+Xtr9wleB63F7vP0HwJrqMuAltC0WqfTrI+Ay3J4j1gdQW+kuQQuBlxJHG4ALUr1CtqUYvhHAMgmfkJoGLKOmerg1LWBNdTmwFJgix1pobdQt4SHrAKj5fEul5TPVdHx+KnxCWwrgcwEvSvhMNx2/qI+diQHUgkd/j3YeKWUuzQae1cfQhABqJxy/QdvnkzKnLgF+o4+liXxALZxqIfAMYJfjaGpFgOuJqX80IpzLGAtoU2aiRbVI+MwvO/C4PqYmsIDaivdjoEqOnaX0NXBaslfGtiTDl4GWJijhs56qgEf1MRZ2Cr4eLXFIyppaAFwn5hRcU12FFkY/UI6TpdUCzMLt2SWOBdRyDaolfP1CA4EnkpVfkqxV6kK0KlSWlw0Ya3cyKTOb0uwBlDkHMNSRg8vuwGb/7pjEwiGawgHqQ34Od3vZF+xifdhPWyxm5m44Wx/zZ9I/BddUD0E7Oyy1InAKcGF2PqcWDmZ6UQWVrmIKnDm4HE7sSt8nkK5ImK5QN/s629jedoj3m2t5ubOVKKYrdtUITMPtqU8fgFq5jKfQcjospYuyC7iy4jhmlFZSnltAVoYxW5qhWJSDne2sOrybpw9+xZqQ30zd9CxwYyJlQBIF8CRgJRYpl1GoKNxYVMn8yokcX1RhGHTfJ284wJpDe7h/7+esDHaZoctCwOm4PZ+mHkCtLl8NMMfs4BUrNm4uHs4VI6cyJr8Um5LeFJWOUDev7tnI3Qe20KAK7yt+ALjjrVOYyE/cjQWiXBa5SrmlahaTBg5OO3jfKN+RzXXjTmFK8VD+48sVLBfbGs7WWViSOguoWb+1wHSzgjfKZueBUTM5t3IC2RmZwr5nfVc7t218l9f9bSJ353q0vcE+W8F49wHnAVPNCt9luQNZNnMe80ZOERo+gCG5BVRPO59zs/JEfs2pOhMpsICa9fsY7b4NU8kG3FM2hlvHn0q+I9tU7767o4kfff4mX0aFLYD6ib4gifR1TPqq04CZZoTvmcop3HnCHNPBBzA6v4QHq04mU9wc/hN1NgycgrV9v9sxWUHwLEXh+ZEzuWbsSThs5q1lftaQ4/AUDhb19TKA23VGDLOAY9AugDGV5XuyciqXjp4W18mFSMq0ZXD9mBMpFbcdc3VGDAPwGpJ/iZ+h+u3g47mqaiYZJofvG40tKGNh4RBhJxvgamMArKnO7euXp1v/VjSU68edYnrLd9SAKQoXDh4ncjWnq3VWkm4B5wBDzTJQ52S5uHPCmcJvs8Sj44sHM0bcdg2jD6djvQNwWbWCiSKdBygK946fTXH2AKyoAkcWPxZ3GgZYoDOTJAAVCtBuJzKFHhx6ApOKh2BVKShMLRT6LsZzUXpXcLS3U/BZaLeIC6+zs1xcPmqaMOe6Rmm0S+hrUwqBc5IJ4EWYoIqpAvzn6JNMudHc52lYbPdC0ZlJAoBaDWFTRL0szCvlpEEjDX+OCvgjIXZ7m9nScpBtrQ00+L2EY9GUtbXYmYPga/szelN/ujfhWNOAQaLD50ThhhHTDQ8iberu5O26LTzZsIMN4e6jfvJXukq4acQ0Tho0wvB9R7tio8LupD4i7C2tg9CCFNYmOgXPwQRHb5e7SphWOszQZ2xurufHn77KT+u+OAq+b6zin31NnLnlr/xl13piqsE5HgrYxHaK7MCZyfABhb8aVQEWVk4i08Bz3nWNdVyyaSmrjpGzEULlX2vXs66xFilOTwxArUDhRNFbOSfLxYyyEYZ9f52vhdu3LWdXtHeRRq2qyuLd6whGI/0dwInHKnJ5LAs4EigRvZU3DZlIjt2Yk4HuaJh7t33E2nCgT//vhc5mdrYbWOFWVWkXH/ASnaG4AZwquv/nUmycXD7KsO9//8B2nvL2/eaCGLCjzbg63x3hIN4UrrrjVAbHiJw/FoDC13W+dWAlZdnGlDL2hgL8tnZj3P9/Z5dxeRwtAVOkbZIogJNFb527osqwU4/Vh3bzUQIZaUbuCzb5O8zjB8YFYE11DoJHv1RlOBhfVGHId4diUf73wLaEvqPMadxpxY6OJrMAOEJnqc8WMF/0BcjFBRUUOo05dqv1tvBKV0tC3zGpwJj9+6gaY0nLfrMAWEwPcQQ9ATgIEPpQ9YzSESgGHVF/0ZzYAE+xOxlfZEzESq2vldXd7WYBMIceTtJ6ArBS6FYpNsMGOKaqfJAggLcOmUBRVq4h77fm8B7aVVNV0xoaD4BlIrforCwXJQatfn3hIB/64vexrs0rY/7IKQa9W4A/HPwKk6k8HgCFjnicmV9mWOBBQ2cbtXGuYBe6Srhv8jkMyDTmIvKldV+y0lwl3HpkqacRFLrg5OQC434fe30tRPpYMLJYsXFX+XFcO3YW+Q5jEgcP+Tt4uO4LTKjSeAAsErU1NmBUnnERwfs7W3v9b/MUG9cVVLBo1HSOL6owbE8yHIvyu+1rWC9u+BXxsNQTgC5RW1OVkcnAbONeb623sce/V4C5WS7mlYxgdkUVo/NLDI3/U9GOBH/dvA+TyhUPgDnCAujIZqDTmNfrjkaoD/iOdmAyMjklO59ZrhLG5ZcyuqCMIbkFZNtTkxq5teUgN3+9xnxVpHvBkinvchuTW2TYVGdTFB6fpOXTOO0OCh3ZDLA7yLDZDI03/D7t7mjk5i3vURezZmiXKQEcn11g2Hc7bRlMMOh4Lx74Fm1carbC5dYHMD8rBytLRWVj0wFu2PoeG8NBS7fVnAA6rAtgMBrhzX2buW3vOo6oMawuUwJY5rQmgHu9zTy6fTVPtB+kv6gnAH1ivrCCI9NhqUFoD3bzVu0W7j2wmZ3RsBU588UDYKeILclVFBx28wOoAm1BPx/W7+D+ui/4vI85JyZTZzwAtojYkgFAjokBDEYj7Pe1srxhJ48f2sGOSIh+oJZ4ABQy5NauKNht5io4GYhGqO9s49Mj+3j7yG5e87cRo1+pKR4AG8S0gAr5dqfQva0Cjd0+9rQ3sr6lng9bD7A04CWsqvRTNcQD4BERW6IAolReU1GJqSrtoQCNXR3Udray19vMx+0NrA942SsT04/JUk8A7uuPPRWORYnEonRFwoRiUQKxCOFYlFA4RCwWxRsKcCToxxvsYpe/nU86W6gL+TkYi/U5hKsfaV+8PmCn7vcLNb2pqmpYtcJl+7/khztXSWSSuwL+Xh+wJ2++Q8SFSCcqHQauHO0mvshG4AVIR98BdHsCwF7RWhNSVUIG+lYDDUok6sfaq7PUZwsIsFW01vhQ8RtoASty8im00L0iAmhzT395rJ7+XLTW+FWVcNg4AEuyXUztBzWmU6gNiQD4BSDU4WQMaDKwME9Whp2zCodIbJK0qaAzRDyrYIBatD0coUbkSLexcRKnlY3EdninIacVmYrCzwoqqMwtxBcOsrOzhfe6O2gRv9RaXEOlMxQngG5PNzXVm0QDsK7L2Ovrp5QM5eysPGoC3uRaV0XhzXGzOWvIcWTou+mhWBRvqJsNTft5pnYTr/nbrATgJtye7kSmYICVorVqndfYQ5rsjEzuGDk96d/78JCJzP07+AActgyKswZwztDx/GnWfF4ZPYsy62wFHZOd3gD4gWh+4JaAz1A/EOD0wWO4LYm+4M/yy/lJ1Yk9JlPl2B3MHzWVpZPPY4rg59299P8+SAaAW4F6kVq2Ixpmv7fZ0Gc4bHbunDCb87ISzz+e7czlv06YQ24vwsgUYFrJMJ6eOJfh5raE9fRiG+/YALo9EWC5aK1b33zA8GeU5+SxeOoFzM8pjPs7fuDI4enJ51GR07er9qaXVnLfiBmY+Ma75To7CVtAgLdArJP2Zc21BFIQbTLcVcRTM3/EA+Xj+pxAc0P+IF6cMY/RBfGV2blw+Amcn51vRvhUnRmSBeBK4LBILVza7WVXe2NKnlXkzOGOibPZPONiflVWRVVG5vdeHZCjKJyXnceS407j0ekXMWRA/DnMOfZMrqg4zowAHgY+7M0/7N2PWlU7UZQlwPWitDCCSs3B7UwYWG5YldS/V4aiML6onHFFg/CEgjT4Wqnv7sAbChCNRXFkZFLkzGFwbgHDXEU4kuS/TSgsxwZmi6Begqr2Kpu+9yNXU31mb1Y1qdSwDDufzrqM8lxTTlO90gF/B1NXv0CzuXKE5+D2rEjmFAzwCbBTpFbuj0Z4Z/9WS4eBZmdkkmOuy7d36qyQXAC1kJrnRGvtr+q/5EBnG1LC6Lmewq8SsYAALyFYvnB9LMJzu9YZfz1qmuQLB+gwz/Tr0xnBGABVtQ54W7RWP9C0h0+PWDOFpd3fidc8P653dEYMAvDcWwAeRbCjOb+qcveO1Wa6P63X2tR20Cw+bhh4VGfEIAA1bQBWiNb65UEfD3+5kqCFCjl2R8O8eni3WV53BccIPk0OgG5PDHgEEG6k72/ex4u71lvGH/y4YRd/TXJImEGKAI/obBhuAUE7GxYudzEG3Fa3kXfqtqKafHOmsdvHA7vXmWUDehVxxgvEB6BG+j0iWkGvqnLN16t5u3YrUZNaQn8kxEPbPmRFyBQ+bQS4Jx7rl4gF/Ib6N0XsEa+qsmDnKp7/+jNCJvMJ/ZEQ92/5gAdbD5jlld9MZDZMbIu9pvp4YB2CXumgAHcWD+eO8acZdq9cMtUS6OL+rSt4sNU0V7H6gRm4PXFfXpdoAuxXQLWovaMC9zXXculnr7GyYRdRQTd0VVTWN+3n2nVvmAk+9LHfnqiRSEw11QPR8odHiNxTTkXh50WV/GT0DMYUlKQkgqY3P5D6zjZe3LuRhw9/TaO5Ag726davJb0AahBeDLyMCYqelyg2bikdxcXDJlJVUJqWy2fCsSh7vc28e+ArHjq8kwbzpWRGgEtxe15PhpuUDABtwAvApWbqxatcJcwvH8uU4qGU5uQZdv0raFVSj/i9bG6u57VDO3je12TmjaKXgCvjXfkmH0ANwkH6VGy6sgJ2ReGC7HxOLihnWmEFw/OKKczKJS8z66gUyt4qFIvSGQ7SEujigK+FDW0NfNJ+iLf9HcTMHzxWr0+9SYmQT64jVFM9D3gVMHU6lwKMszuZ6silLMfFiKw8BjsHkGHPJPsfLqKOxKKEIiGC4SB7Aj4OBnwcCXSyPtTNvqjlCpBHgUtwe95I2o8/yS/4FrAYuNXMvawCX0WCfBUJgr8Vqb9pMb1MNkqPBdSsYB7wPjBTjpeltA6Yi9vjFRtADcKxwMf0cFW7lKnUCJyG25P0lAxjKjFqL7oICMixM70CwCIj4DMOQE3LgLugv93JYinFgLtQ1XeNeoBxALo9KvCY7rjK+wvMuRarBh7ra5Rz+n3Ao/3BTODPwAI5pqbSK8BVuD2Gpl+k5kC0ptqlN8gtx9UUqgEW4PYYfmVv6k7ka6rz0Tap58rxFVrv6fB1pOJhqbuPQGvQFWh7hFLiwnd5quBLrQX81hLmoUXOyOlYvGn30mRvNItjAb+1hF7gEh1CuToWY7X7MtoZb8pT8NJzJZDb0wlcjbZNE5UMpE1RfQyu1sck5UpvWHBNdQbgAe4DsiQPKVUAuBNYjNuTNiOQ/rj0ZU+AorjRKm8NklykRIeBRahqjZGbzOYA8FtrWAX8EZgl+TBUa4GFuD1fi/Ay4lwLqXXI2QhY/MgiCut9e7Yo8IllAb+1hApwIfA4UCm5SYrq0IKE39HP6JEAHhvEUuBB4EpMHuKf5lXuX4B/x+1pFPEFxS4+rGXbnYdWjWuM5KlP2gXcAbybjOy1/gngtyAW6p15G+CSbPUoH9re3iO4PcIXzzZP+XVtu2YsWlWueYBTsnaUgsAbwD2o6s50b69YD8CjQTwR+B9gNpApV7d8CPw3qvqZWcAzL4BH+4enAD8HzgUc/Qy8IFoAwcPAGpH9PGsCeDSIE4GbgcuAPIuD50UrjbEY2GZW8KwD4N+m5moFhUFoof+LgAlYZ/smCmxDO658BZXDnOuxRCSRYkkboQU5nIRWLOkCYJgJYYwC+4ElaOFSn6YzaEACGD+MDrTz5YvR0gFGCryCDgK70S6FfB1Yi9sTsvLwWB/Ao2G06wCerq+gZ+jWMV0LmJBu5T5Hu2fjY2Bvb24alwBaA8gsoFz3FycDk9BOXIYBBUl+WrsO2y5gM7BJ9+sO9eVyPwmg9aHMBLKBgWhlh8v0TwlQCOTqn3+mLv3TBjQBR4BDaMEALUC30Xm2UlJSUlJSUlJSUlJSUj3o/wFeYkf7rqXu/wAAAABJRU5ErkJggg==" alt="" />
```

I can do:

![rich_image](https://user-images.githubusercontent.com/20475953/119268757-a899d400-bbf4-11eb-8e27-d58de9057e86.gif)

Let me know if that helps

Cheers :)
