### ISSUE TITLE
Global variables are not evaluated if not included in the replacement, even with explicit re-declaration

### ISSUE THREAD

**Issue by kopach** [federico-terzi/espanso#693]
Espanso version: `0.7.3`

Environmental variables seem to not work properly when defined globally. E.g. this won't work:

```bash
global_vars:
  - name: 'time'
    type: 'dummy'
    params:
      echo: '🗓 dd/MMM/yyyy'

matches:
  - trigger: ':test'
    replace: '{{myshell}}'
    vars:
      - name: myshell
        type: shell
        params:
          cmd: 'echo $ESPANSO_TIME'
```

> Note: `$ESPANSO_TIME` is not taken from `time` global variable in this case

But this will:

```bash
matches:
  - trigger: ':test'
    replace: '{{myshell}}'
    vars:
      - name: 'time'
        type: 'dummy'
        params:
          echo: '🗓 dd/MMM/yyyy'

      - name: myshell
        type: shell
        params:
          cmd: 'echo $ESPANSO_TIME'
```

> Note: `$ESPANSO_TIME` is taken from `time` local variable in this case

useful links:
- docs: https://espanso.org/docs/matches/#global-variables
- related issue, where defect was discovered: https://github.com/federico-terzi/espanso/issues/653#issuecomment-841839351

**Comment by federico-terzi** [comment]
Hey @kopach,

Thanks for reporting this issue!

> Environmental variables seem to not work properly when defined globally. E.g. this won't work:

This is expected, as global variables are evaluated lazily. You will need to explicitly declare the global variable as follows:

```yaml
global_vars:
  - name: 'time'
    type: 'dummy'
    params:
      echo: '🗓 dd/MMM/yyyy'

matches:
  - trigger: ':test'
    replace: '{{myshell}}'
    vars:
      - name: "time"
        type: "global"
      - name: myshell
        type: shell
        params:
          cmd: 'echo $ESPANSO_TIME'
```

This wouldn't be necessary if you used the `time` variable inside the replacement, as that counts as an implicit declaration of the variable.

There is a bit of information in the [advanced topics](https://espanso.org/docs/matches/#advanced-topics) section, though it's not perfect :)

Hope that makes sense! Feel free to reopen the issue if this doesn't solve your problem

Cheers :)

**Comment by kopach** [comment]
Hi @federico-terzi, thanks for this clarification.
Unfortunately, I still can't get it working. With exact copy/paste example from above, I'm getting following error with `espanso log`

```log
21:15:11 [ INFO] worker is running!
21:15:28 [ERROR] No extension found for variable type: global
```

I'm getting this error in log once I try to type the trigger (`:test` in this case)
Any ideas what could be wrong here?

**Comment by federico-terzi** [comment]
@kopach Thank you for trying the approach! I've tested it myself and this is indeed a bug. I'll reopen the issue.

I've noticed that if the global variable is included in the replacement, like this:

```yaml
global_vars:
  - name: 'time'
    type: 'dummy'
    params:
      echo: '🗓 dd/MMM/yyyy'

matches:
  - trigger: ':test'
    replace: '{{myshell}}{{time}}'
    vars:
      - name: "time"
        type: "global"
      - name: myshell
        type: shell
        params:
          cmd: 'echo $ESPANSO_TIME'
```

it works, but of course, this shouldn't be the only way. Ideally, declaring the global variable (as I showed in the snippet posted before) should evaluate it without requiring the variable to be included in the replacement text.

I'll keep you posted!

Cheers :)

**Comment by federico-terzi** [comment]
Hey @kopach,

I've tested this issue on Espanso v2 and it seems to work correctly now after declaring the global variable as follows:

```yaml
global_vars:
  - name: 'time'
    type: 'dummy'
    params:
      echo: '🗓 dd/MMM/yyyy'

matches:
  - trigger: ':test'
    replace: '{{myshell}}{{time}}'
    vars:
      - name: "time"
        type: "global"
      - name: myshell
        type: shell
        params:
          cmd: 'echo $ESPANSO_TIME'
```

Thank you for the help!

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
