### ISSUE TITLE
Multi-line cursor in Visual Studio and SQL Server Management Studio inserts random characters

### ISSUE THREAD

**Issue by jvgarner** [federico-terzi/espanso#704]
O/S: Windows 10 Pro v 10.0.19043
Visual Studio Pro 2019 v 16.9.3
SQL Server Management Studio v15.0.18338.0

When I attempt to use multiline cursor (by holding shift + alt and then arrow key down or up) espanso inserts random characters. If I attempt to press right arrow at this point it deletes my text and replaces it with another random character.
![Animation](https://user-images.githubusercontent.com/1078233/124966360-3a1ca400-dff1-11eb-8515-5dec077e6492.gif)

I was able to reproduce with a very simple config file:
```yaml
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ";dt"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
```
