### ISSUE TITLE
Espanso doesn't recognize certain modfiers

### ISSUE THREAD

**Issue by es183923** [federico-terzi/espanso#725]
Steps to reproduce:
1. Create the following expansion:
```yml
  - trigger: ":a:"
    replace: "first example"
```
2. Type `:`
3. Press `cmd-a`
4. Press `:`

result: `first example` appears, even though it shouldn't.
expected result: nothing happens, and you are left with `:`

Here are some more examples that always produce the incorrect result
```yml
  - trigger: "aaa"
    replace: "second example"

  - trigger: " a "
    replace: "third example"

  - trigger: "zbz"
    replace: "fourth example" # do cmd-b instead of cmd-a

  - trigger: "-c-"
    replace: "fifth example" # do cmd-c instead of cmd-a
```
