### ISSUE TITLE
Form fields (Prompt) always add a new line

### ISSUE THREAD

**Issue by r-martins** [federico-terzi/espanso#729]
When using {{choices}} feature, it always add a new line.
For example: 

```yaml
  - trigger: ";voda"
    form: |
      {{choices}}
    form_fields:
        choices:
          type: choice
          values:
            - 0424615555
            - 0424614444
```
When using in web forms, it goes to the next input field. But when using in terminal, it adds a new line (which is very bad sometimes).
![image](http://g.recordit.co/haHLq26AIX.gif)

I tried to use `trim` but had no luck.

**Comment by federico-terzi** [comment]
Hey @r-martins,

I'm sorry you experienced this problem! That's the default behavior with multiline YAML strings: https://yaml-multiline.info/

You could try using the `>-` syntax:

```yaml
  - trigger: ";voda"
    form: >-
      {{choices}}
    form_fields:
        choices:
          type: choice
          values:
            - 0424615555
            - 0424614444
 ```

Let me know if that helps

Cheers :)
