### ISSUE TITLE
trigger "~~~" has unexpected behavior

### ISSUE THREAD

**Issue by rnoennig** [federico-terzi/espanso#740]
given the config below the trigger is not working properly in most applications
```yaml
matches:
  # replace three tilde into a fullwidth tilde
  - trigger: "~~~"
    replace: "～"
```
typing ~~~ in firefox adress bar/html form text inputs results in the three tildes to be deleted, but not replaced
![threetildes](https://user-images.githubusercontent.com/11728006/130350307-d00c38f6-d287-47a5-9008-d94332aa0c0a.gif)

it works in emacs as expected tho

when I change the trigger to a latin text it works everywhere:
```yaml
matches:
  # replace three tilde into a fullwidth tilde
  - trigger: "fulltilde"
    replace: "～"
```

![fulltilde](https://user-images.githubusercontent.com/11728006/130350316-a9be5730-871a-488f-a542-d53ff7d6341d.gif)

any idea why that is happening?

I'm on ubuntu mate 20.04 and use the espanso snap --classic 0.7.3
