### ISSUE TITLE
Output is usually empty

### ISSUE THREAD

**Issue by matildeopbravo** [federico-terzi/espanso#741]
```
  - trigger: ":nif"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "grep NIF $HOME/documents | cut -d ':' -f2 | tee >(xclip)"

```
I have this in my config and whenever I triggered it , it's supposed to replace the trigger by a number and copy to my clipboard as well. The clipboard seems to be working but replacing the text usually doesn't.
