### ISSUE TITLE
Windows 10, have to type trigger twice

### ISSUE THREAD

**Issue by grenudi** [federico-terzi/espanso#745]
Tested on several machines - same behaviour/
When I switch to any input field triggers doesn't work right away, I have to type some random characters first and delete them, only then trigger words expands normally. 

Any advice how to diagnose/fix this ?
I use your extension in my work, with several colleagues and it's very important.
Thanks a lot for your work !

**Comment by federico-terzi** [comment]
Hey @grenudi,

Thanks for reporting this issue! Could you post an example of these problematic triggers? I'm particularly curious to see if you are using the `word: true` option

Cheers :)

**Comment by grenudi** [comment]
> Hey @grenudi,
> 
> Thanks for reporting this issue! Could you post an example of these problematic triggers? I'm particularly curious to see if you are using the `word: true` option
> 
> Cheers :)

For some reason it works like a charm when I try to record it... 

No, I do not use `word: true` option in any trigger, all my triggers start and end with same symbols, for example `-test-` , `.test.` , also option `backend: Clipboard` have no effect either. 

This doesn't depend on usage of  `type: "clipboard"` option as well, though it is used in the demo bellow, nor does it bound to `html`, nor `markdown`, nor `replace` options.

Video demo of  `-зак-` trigger
---

https://user-images.githubusercontent.com/17498075/131931355-d6857fde-2ec9-49c2-a0a9-6137955b9223.mp4

```
  - triggers: ["-закз-"]
    html: |+
      <p>
      <strong>Запрос закрыт согласно комментарию заявителя:</strong>
      <blockquote>{{cb}}</blockquote>
      {{clo}}
      </p>
    vars:
      - name: "cb"
        type: "clipboard"
      - name: clo
        type: match
        params:
          trigger: "-зак-"
```

All contents of file `cloacu--close-according-to-users-reply.yml`
---

```
parent: default

# Mnemonic   : XXX
# Description: XXX
# Data Source: XXX
# TODO: XXX

matches:
# ENGLISH
  # - triggers: ["  "]
  #   replace: |+

  # - triggers: [".."]
  #   markdown: |+

  - triggers: ["-cloacu-"]
    html: |+
      <p>
      <strong>[Closed according to requesters reply]</strong>
      <blockquote>{{cb}}</blockquote>
      {{zak}}
      </p>
    vars:
      - name: "cb"
        type: "clipboard"
      - name: zak
        type: match
        params:
          trigger: "-clo-"

# RUSSIAN
  # - triggers: ["  "]
  #   replace: |+

  # - triggers: [".."]
  #   markdown: |+

  - triggers: ["-закз-"]
    html: |+
      <p>
      <strong>Запрос закрыт согласно комментарию заявителя:</strong>
      <blockquote>{{cb}}</blockquote>
      {{clo}}
      </p>
    vars:
      - name: "cb"
        type: "clipboard"
      - name: clo
        type: match
        params:
          trigger: "-зак-"

# You can refer to the official documentation:
# https://espanso.org/docs/
```

FILE `default.yml`
---

```
# espanso configuration file

#### OPTIONS #### 
# https://espanso.org/docs/configuration/#options

backend: Clipboard

matches:
  # Testing
  - trigger: "  test"
    replace: "THIS IS TEST SO STFU test"

#YAML CHEATSHEET:
#                       >     |            "     '     >-     >+     |-     |+
# -------------------------|------|-----|-----|-----|------|------|------|------  
# Trailing spaces   | Kept | Kept |     |     |     | Kept | Kept | Kept | Kept
# Single newline => | _    | \n   | _   | _   | _   | _    |  _   | \n   | \n
# Double newline => | \n   | \n\n | \n  | \n  | \n  | \n   |  \n  | \n\n | \n\n
# Final newline  => | \n   | \n   |     |     |     |      |  \n  |      | \n
# Final dbl nl's => |      |      |     |     |     |      | Kept |      | Kept  
# In-line newlines  | No   | No   | No  | \n  | No  | No   | No   | No   | No
# Spaceless newlines| No   | No   | No  | \   | No  | No   | No   | No   | No 
# Single quote      | '    | '    | '   | '   | ''  | '    | '    | '    | '
# Double quote      | "    | "    | "   | \"  | "   | "    | "    | "    | "
# Backslash         | \    | \    | \   | \\  | \   | \    | \    | \    | \
# " #", ": "        | Ok   | Ok   | No  | Ok  | Ok  | Ok   | Ok   | Ok   | Ok
# Can start on same | No   | No   | Yes | Yes | Yes | No   | No   | No   | No
# line as key       |

tmp:
  filesharing: |+
    - Для данных задач вы можете использовать https://web.microsoftstream.com/ , при записи вебинара в тимс он автоматически сохраняется в MS Stream
    - В ручную можно делиться любыми файлами через https://nxcloud.softline.com/ (по умолчанию срок хранения 14 дней, продлевается по запросу или "перезаливом" файла).
    - Корпоративный OneDrive

    [
    Инструкция по работе с файлами: https://wiki.softline.com/pages/viewpage.action?pageId=693207842
    Инструкция по работе с OneDrive: https://wiki.softline.com/pages/viewpage.action?pageId=693207842
    ]
```
