### ISSUE TITLE
form field injection not orking for scripts?

### ISSUE THREAD

**Issue by chrisbeardy** [federico-terzi/espanso#767]
I am not sure if I am using it correctly but form field replacement does not seem to be working for me.

I have the following:

```
name: forms
parent: default

matches:
  - trigger: ":wcaps"
    replace: "{{capitalise}}"
    vars:
    - name: capsform
      type: form 
      params:
        layout: |
          {{text}}
        fields:
          text:
            multiline: true
    - name: capitalise
      type: script
      params:
        args:
          - py
          - "%CONFIG%/scripts/capitalise.py"
          - "$ESPANSO_CAPSFORM_TEXT"
```

However the python script is just getting `$ESPANSO_CAPSFORM_TEXT` instead of the text I have typed in the form.

I am using Windows 10 Espanso 0.7.3.
