### ISSUE TITLE
Use cmd as default value

### ISSUE THREAD

**Issue by Gadgetroch** [federico-terzi/espanso#819]
Hi,

Can i use cmd as default value ?
Example : 
```
  - trigger: ":mysqluser"
    form: "CREATE DATABASE {{user}}; CREATE USER {{user}}@localhost IDENTIFIED BY '{{password}}'; GRANT ALL PRIVILEGES ON {{user}}.* to {{user}}@localhost; FLUSH PRIVILEGES;"
    vars:
      - name: password
        type: shell
        params:
          cmd: "date +%s | sha256sum | base64 | head -c 16 ; echo"
    form_fields:
      user:
        default: "user"
      password:
        default: "{{password}}"

```
But it stay blank

Thank's

**Comment by federico-terzi** [comment]
Hey @Gadgetroch,

The next version 2.1.0-alpha will ship with the new [variable injection](https://espanso.org/docs/next/matches/variables/) mechanism that should handle your use-case, thank you for the help! :)

This is how the new match should look like (also handling the new [form control syntax](https://espanso.org/docs/next/migration/what_changed/#new-forms-control-syntax) and [verbose form](https://espanso.org/docs/next/matches/forms/#using-forms-with-script-and-shell-extensions))

```yaml
- trigger: ":mysqluser"
    replace: "CREATE DATABASE {{form.user}}; CREATE USER {{form.user}}@localhost IDENTIFIED BY '{{form.password}}'; GRANT ALL PRIVILEGES ON {{form.user}}.* to {{form.user}}@localhost; FLUSH PRIVILEGES;"
    vars:
      - name: password
        type: shell
        params:
          cmd: "date +%s | sha256sum | base64 | head -c 16 ; echo"
      - name: form
        type: form
        params:
          layout: |
            User: [[user]]
            Password: [[password]]
          fields:
            user:
              default: "user"
            password:
              default: "{{password}}"
```


Cheers :)
