### ISSUE TITLE
Make Form's choice values accept also strings 

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#855]
This is needed to support other features such as https://github.com/federico-terzi/espanso/issues/803

In practice, instead of supporting only an array, such as:

```yaml
      choices:
        type: choice
        values:
          - First choice
          - Second choice
```

we would also need to support multiline strings:

```yaml
      choices:
        type: choice
        values: |
          First choice
          Second choice
```

At that point, the form should split the string by line and convert them to an array
