### ISSUE TITLE
Implement new variable injection mechanism

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#856]
The current variable injection mechanism is limited to the Shell and Script extensions, as described here: https://espanso.org/docs/matches/#advanced-topics

Ideally, we could make variable injection available to all extensions. For example:

```yaml
- trigger: ":test"
  replace: "Hi {{fullname}}"
  vars:
    - name: firstname
      type: echo
      params:
        echo: "John"
    - name: lastname
      type: echo
      params:
        echo: "Snow"
    - name: fullname
      type: echo
      params:
        echo: "{{firstname}} {{lastname}}"
```

That would also make #803 and #478 possible.

An extension could opt-out of variable injection (which might be needed if the script/shell needs to use the `{{something}}` syntax for something else), with an option, such as:

```yaml
    - name: fullname
      type: echo
      inject_vars: false
      params:
        echo: "{{firstname}} {{lastname}}"
```

For shell and script extensions, this mechanism would work alongside the current env-variable injection mechanism, which is more robust in many cases but also less intuitive for simple ones

**Comment by federico-terzi** [comment]
To support this feature, we'll need to introduce a breaking change with the form control syntax

In particular, instead of having the following:

```yaml
  - trigger: ":greet"
    form: |
      Hey {{name}},
      Happy Birthday!
```

we'll need to use the `[[name]]` syntax for controls, as `{{name}}` is now interpreted as a variable injection

```yaml
  - trigger: ":greet"
    form: |
      Hey [[name]],
      Happy Birthday!
```
