### ISSUE TITLE
Regex example does not work

### ISSUE THREAD

**Issue by JohnAtl** [federico-terzi/espanso#862]
Trying the regex replacement example from the docs, and it's not working.

```
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # regex test
  - regex: ":greet\\((?P<person>.*)\\)"
    replace: "Hi {{person}}!"
```

Rust backtrace:
```
(base) Johns-iMac-Pro :: ~ 101 » RUST_BACKTRACE=full espanso start
thread 'main' panicked at 'Match does not have any trigger defined: AutoMatch { trigger: "", triggers: [], replace: Some("Hi {{person}}!"), image_path: None, form: None, form_fields: None, vars: [], word: false, passive_only: false, propagate_case: false, force_clipboard: false, markdown: None, paragraph: false, html: None }', src/matcher/mod.rs:88:13
stack backtrace:
   0:        0x105e9c194 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
   1:        0x105ec17c0 - core::fmt::write::haf3903118f694c48
   2:        0x105e94926 - std::io::Write::write_fmt::h7385463ac87804ed
   3:        0x105e9e5af - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
   4:        0x105e9e27d - std::panicking::default_hook::h7bd29c87df967048
   5:        0x105e9eb7b - std::panicking::rust_panic_with_hook::hae2b05f08a320721
   6:        0x105e9e6fb - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
   7:        0x105e9c608 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
   8:        0x105e9e6ba - _rust_begin_unwind
   9:        0x105edd87b - std::panicking::begin_panic_fmt::h6826a3ebe3a95a51
  10:        0x105a4da2b - <espanso::matcher::Match as serde::de::Deserialize>::deserialize::h9e4111edae4ca4e2
  11:        0x105a62b41 - <serde_yaml::de::SeqAccess as serde::de::SeqAccess>::next_element_seed::h8626be41728aba03
  12:        0x105a42459 - <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq::h8cdb3d156e919ff8
  13:        0x105a656a5 - <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_seq::h6e1c7386a913869f
  14:        0x105a51f88 - serde_yaml::de::Deserializer::visit_mapping::h1a0ac08e595be6cf
  15:        0x105a68f74 - <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_struct::h2b98db8f84877414
  16:        0x105a61512 - serde_yaml::de::from_str::h0a37c2b6f5593a89
  17:        0x1059f3411 - espanso::config::Configs::load_config::h372e21c9e9dfea16
  18:        0x1059f64b5 - espanso::config::ConfigSet::load_default::h802d3dcc914038ac
  19:        0x105a88b94 - espanso::main::hbcf7755afdb51899
  20:        0x105a07e0a - std::sys_common::backtrace::__rust_begin_short_backtrace::he96e5589e895f929
  21:        0x105a311dc - std::rt::lang_start::{{closure}}::h83941110f3b2edad
  22:        0x105e9efd4 - std::rt::lang_start_internal::hd38bb63f9540b327
  23:        0x105a936d9 - _main
```
