### ISSUE TITLE
cannot access index variable in "for" loop syntax shell

### ISSUE THREAD

**Issue by tiger360** [federico-terzi/espanso#893]
Bonjour,

How can I use the index variable **$i** in a loop without making a shell script only for that 😊.
It's always empty.

> cmd: "echo 'cd /directory & **for i in** (seq $ESPANSO_FINALE_START $ESPANSO_FINALE_END);scp -r  'google@8.8.8.8:/home/google/final/**$i**' ./; end'"

**Comment by tiger360** [comment]
I did a workaround like that with a default value **"'$i'"** to the index

```
`  - trigger: ":finale"
    replace: "{{scp_finale}}"
    vars:
    - name: finale
      type: form
      params:
        layout: "FROM {{start}} \n TO {{end}} \n {{index}}"
        fields:
          index:
            default: "'$i'"
    - name: scp_finale
      type: shell
      params:
       shell: wsl
       cmd: "echo 'cd /directory & for i in (seq $ESPANSO_FINALE_START $ESPANSO_FINALE_END);scp -r  'google@8.8.8.8:/home/final/$ESPANSO_FINALE_INDEX' ./; end'"`
```
