### ISSUE TITLE
How do I set up a date format list?

### ISSUE THREAD

**Issue by 2ipm1nd** [federico-terzi/espanso#909]
I want to set up a date list to integrate date format so that I can reduce the number of date quick key settings.

For example, the following picture

![](https://filedn.com/lwdD00PHHJOVTxTGwfbRf77/%E6%88%90%E6%9E%9C%E7%AF%84%E4%BE%8B.png)

![](https://filedn.com/lwdD00PHHJOVTxTGwfbRf77/%E7%A8%8B%E5%BC%8F%E7%A2%BC.jpg)

thanks..

**Comment by federico-terzi** [comment]
Hey @2ipm1nd,

As long as you are using a recent Espanso version (>2.1.0), you should be able to do so with:

```yaml
  - trigger: ":ttt"
    replace: "{{ddate}}"
    vars:
      - name: form1
        type: form
        params:
          layout: |
            Select date format
            [[format]]
          fields:
            format:
              type: list
              values:
                - "%Y%m%d"
                - "%Y/%m/%d"
      - name: ddate
        type: date
        params:
          format: "{{form1.format}}"
```

If you want to know more, this section of the docs is a good starting point: https://espanso.org/docs/next/matches/variables/

Cheers :)
