### ISSUE TITLE
Choice Extension: Sort options as defined

### ISSUE THREAD

**Issue by archetyped** [federico-terzi/espanso#937]
**Is your feature request related to a problem? Please describe.**
Currently, items in the search bar are sorted alphabetically.  This works well for most purposes, however, when using the Choice extension, the preferred sort order is more likely the order in which the options were defined.

**Describe the solution you'd like**
List Choice options in the order that they are defined.

Given the match:
```yml
  - trigger: ";ctest"
    label: "[Test] Choice List"
    replace: "{{selection}}"
    vars:
      - name: selection
        type: choice
        params:
          values:
              - "Xylophone"
              - "Cat"
              - "Rambutan"
              - "Alarm"
```

The options should ideally be listed in the order that they were defined in:
```
Xylophone
Cat
Rambutan
Alarm
```

However, the options are re-ordered alphabetically:
```
Alarm
Cat
Rambutan
Xylophone
```

Optionally, a `sort` parameter for the Choice extension would allow customization on a per-match basis:
```yml
sort: manual # Default: Options listed in defined order
```

```yml
sort: alpha # Options listed in alphabetical order
```
