### ISSUE TITLE
Choices + Forms: All forms displayed before options listed (execution order backwards)

### ISSUE THREAD

**Issue by archetyped** [federico-terzi/espanso#938]
**Describe the bug**
When triggering a match using the Choices extension where one or more of the options contains a form, the form(s) will be displayed before the list of options are displayed or selected.

**To Reproduce**
1. Create choice list containing a form
    <details>
    <summary>Example match</summary>
    
    ```yml
    global_vars:
    - name: test_form_1
        type: form
        params:
        layout: "Item Name (1): [[name]]"
    - name: test_form_2
        type: form
        params:
        layout: "Item Name (2): [[name]]"

    matches:
    - trigger: ";fctest"
        label: "[Test] Choice/Form"
        replace: "{{options}}"
        vars:
        - name: options
            type: choice
            params:
              values:
                - label: "One"
                  id: "Item One"
                - label: "Form-based 01"
                  id: "Item {{test_form_1.name}}"
                - label: "Three"
                  id: "Item Three"
                - label: "Form-based 02"
                  id: "Item {{test_form_2.name}}"
    ```
    
    </details>
2. Trigger match
3. All forms used in *any* option are displayed before the options list is displayed.

**Expected behavior**
* The Choice options should be displayed first.
* Only the form for the **selected** option should be displayed.
* Value output based on form input.

**Setup information**
- OS: macOS 12.1
- Version: 2.1.2-alpha
