### ISSUE TITLE
Expand dynamically-generated variables in output?

### ISSUE THREAD

**Issue by archetyped** [federico-terzi/espanso#941]
Is it possible to expand dynamically-generated variable names?  For example, using a shell command to replace placeholder text in a block of text with actual variable names, whose values would be injected in the final output?

Simple Example:
```yml
- triggers: ["testvars"]
  label: "[Test] Expand Variables"
  replace: "{{initial}}/{{processed}}/{{final}}"
  vars:
    - name: initial
      type: echo
      params:
        echo: 'Variable value'
    - name: processed
      type: shell
      params:
        cmd: echo '\{\{initial\}\}'
    - name: "final"
      inject_vars: true
      type: echo
      params:
        echo: "Final: {{processed}}"

```

Currently this outputs:
```
Variable value/{{initial}}/Final: {{initial}}
```

Ideally, the variable's value would be present in the 'final` variable's output:
```
Variable value/{{initial}}/Final: Variable Value
```

Basically:

1. `Variable1` contains text with literal variable placeholders (e.g. `{{initial}}`).
2. `Variable2` takes the value of `Variable1`, but with variable values injected in place of the variable placeholders (`{{initial}}` becomes `Variable value`).

Note that the above is just a simple example to illustrate the goal, but in actual use, the script/shell command may be doing more complex text manipulation to result in the final text containing actual variable placeholders (e.g. `[any_var_link]` to `{{any_var_link_html}}`), so directly passing variable values into the script is not applicable.
