### ISSUE TITLE
Use output of expansion as part of another trigger

### ISSUE THREAD

**Issue by sphh** [federico-terzi/espanso#946]
**Is your feature request related to a problem? Please describe.**
Let's say, I want to have triggers to expand to a loop ➰ and double loop ➿. A logical way would be (at least for me):
```yaml
  - trigger: ;loop
    replace: ➰
  - trigger: ;looploop
    replace: ➿
```
obviously that does not work without setting `word: true` in the `;loop` trigger.

So I naïvely tried
```yaml
  - trigger: ;loop
    replace: ➰
  - trigger: ➰loop
    replace: ➿
```
which also does not work, because I believe the expanded phrase cannot be part of a trigger.

**Describe the solution you'd like**
It would be nice, if the expanded phrase could become part of the trigger phrase (maybe with a configuration option to switch this behaviour on and off?), so that the second example is working. Alternatively keep the trigger available in espanso (sorry, I do not have a better wording), so that the first example works.

**Describe alternatives you've considered**
I added `word: true` to the first example, which works, but does not expand `;loop` immediately.

**Comment by sphh** [comment]
Here is another example, which does use a more common expansion phrase:
```yaml
  - trigger: "--"
    # U+2013 EN DASH
    replace: –
  - trigger: "---"
    # U+2014 EM DASH
    replace: —
```
