### ISSUE TITLE
Espanso doesn't understand .yaml files with regex instead of triggers

### ISSUE THREAD

**Issue by patrykpalej** [federico-terzi/espanso#965]
**Describe the bug**
Espanso .yaml files are not parsed when "regex" is used instead of "trigger".

**To Reproduce**
1. Create the following .yaml file in your espanso folder
```
toggle_key: RIGHT_CTRL
matches:          
  - trigger: ":test"
    replace: "hello world"
    
  - regex: "^regex"
    replace: "my expansion"
```
2. Type in terminal "espanso stop" or "espanso start"

**Expected behavior**
Espanso should stop/start and work as usual parsing my regex. Instead I get the following message:
```
thread 'main' panicked at 'Match does not have any trigger defined: AutoMatch { trigger: "", triggers: [], replace: Some("my expansion"), image_path: None, form: None, form_fields: None, vars: [], word: false, passive_only: false, propagate_case: false, force_clipboard: false, markdown: None, paragraph: false, html: None }', src/matcher/mod.rs:88:13
```

**Setup information**
I'm using Ubuntu 20.04 and `espanso 0.7.3`. Installed both from snap and using `curl`
