### ISSUE TITLE
Add option to conditionally exclude a match from being loaded based on a condition

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#968]
To support use cases like #964, it would be handy to have an option to conditionally exclude a match from being loaded based on a condition.

For example, we might want to create a match that's only enabled on Windows and Linux, but not on mac:

Pseudo-code:

```yaml
  - trigger: "example"
    replace: "Hello world"
    condition: "OS == 'windows' || OS == 'linux'"
```

The actual syntax for the condition has to be decided yet, as I'd prefer to use the same scripting engine used for #556, but I still have to decide between JS and Lua. I'd probably go with Lua though
