### ISSUE TITLE
Drag files (their filepath) into forms

### ISSUE THREAD

**Issue by couleurm** [federico-terzi/espanso#970]
**Is your feature request related to a problem? Please describe.**
FFmpeg commands are always so long and tiring to type, espanso forms seem to be the solution but it won't me drag file's (pastes the file's literal path, or multiple paths separated by a space if there is)

**Describe the solution you'd like**
Since the espanso is always on top and is pretty small, it's super easy to get Windows Explorer open and drag the path

**Describe alternatives you've considered**
A home-made shortcut to copy the file's path (CTRL+SHIFT+C)

**Comment by federico-terzi** [comment]
Hey @couleurm,

Thank you for the feedback! I'll add it to the roadmap :)
(the file picker control should support drag and drop out of the box)

Cheers :)

**Comment by vangquan** [comment]
I'm using Espanso and FFMPEG. This is one of my example.
The FFMPEG command below helps me to join the video and the audio of two video of the same content, but in different languages (video from the JW.ORG).
```
  - trigger: ffjoin
    replace: "ffmpeg -an -i {{form1.file}} -vn -i {{form2.file}} -map 0:v -map 1:a -c:v copy -c:a copy ~/Downloads/$|$.mp4"
    word: true
    vars:
      - name: files
        type: shell
        params:
          cmd: "find ~/Downloads -maxdepth 1 -name '*.mp4'"
      - name: form1
        type: form
        params:
          layout: |
            Select file that you want to keep the sign language video:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
      - name: form2
        type: form
        params:
          layout: |
            Select file that you want to keep the audio:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
```
Sometimes, it works, sometimes it does not. Maybe a real File Picker will help.
