### ISSUE TITLE
The default item of form (Text Fields) cannot use global variables or nested matches.

### ISSUE THREAD

**Issue by zzhanghub** [federico-terzi/espanso#979]
**Describe the bug**
The **default** item of the form (Text Fields) cannot use global variables or nested matches.

**To Reproduce**
Here is an example:
```
global_vars:
  - name: "clip"
    type: clipboard

matches:
  - trigger: ":obclip"
    replace: "obsidian://advanced-uri?vault=knowledgehub&filepath=markdown%2F{{form1.mddir}}%2F{{form1.mdname}}.md"
    vars:
      - name: "form1"
        type: form
        params:
          layout: "filename: {{mdname}} \nfiledir: {{mddir}}"
          fields:
            mdname:
              multiline: false
              default: "{{clip}}"
            mddir:
              type: list # 'choice' or 'list'
              values:
                - 001_plain
                - 002_avatar
```
I want the default value of the form to be the text of my clipboard, but it doesn't work.
I've also tried nested matches, which also don't work.

Is it possible to update this problem? Thank you very much! ^_^

**Setup information**
- OS: macOS 10.15.7
- Version: 0.7.3
