### ISSUE TITLE
Replacements within a regex

### ISSUE THREAD

**Issue by aimslut** [federico-terzi/espanso#981]
So I'm trying to make a simple sensitivity converter that goes from your cm/360 ➜ your desired sensitivity. My current regex is:
```yaml
# =cm(x,y,z)
- regex: "=cm\\((?P<sens>.*?),(?P<dpi>.*?),(?P<yaw>.*?)\\)"
  replace: "{{result}}"
  vars:
    - name: result
      type: shell
      params:
        cmd: "[math]::Round(((360/([decimal]$env:ESPANSO_YAW*[decimal]$env:ESPANSO_SENS))/[decimal]$env:ESPANSO_DPI*2.54),3)"
```
This all works perfectly fine. If I input `=cm(1,1600,0.022)`, I get `25.977` which is fine, however I don't particularly want to have to remember the yaw values for all the games I wish to use this on.

What I want is to add a replacement within the regex to have `=cm(1,1600,yaw_cs)`. If I make another replacement elsewhere, like this for example:
```yaml
- triggers: ["yaw_cs", "yaw_source", "yaw_apex", "yaw_quake"]
  replace: "0.022"
```
It outputs it correctly as text, `=cm(1,1600,yaw_cs)` turns into `=cm(1,1600,0.022)`, however the regex spits out `Cannot convert value "yaw_cs" to type "System.Decimal".`, so it seems like the original string is what's getting passed through the regex, not the text replacement.

One thought I had of getting around this would be adding a var to the regex, though I'm not sure how to go about adding multiple vars and only using the var the user inputs.

Any help would be appreciated ♡
