### ISSUE TITLE
Espanso forms always pop up on the primary display 

### ISSUE THREAD

**Issue by SpinningVinyl** [federico-terzi/espanso#983]
**Describe the bug**
Espanso forms always pop up on the primary display in macOS. For example, if I am typing in an email client opened on the secondary monitor and use a multiple choice match, the form will be displayed on the primary display.

**To Reproduce**
1. Insert the following into your default.yml:

```
  - trigger: "@@@"
    replace: "{{email.addresses}}"
    vars:
      - name: "email"
        type: form
        params:
          layout: "Email address \n{{addresses}}"
          fields:
            addresses:
              type: choice
              values:
                - 'address1@example.com'
                - 'address2@example.com'
                - 'address3@example.com'
```

2. Reload espanso config
3. Type @@@ in a window which is located on the secondary display.
 

**Expected behavior**
The pop-up form appears on the same screen as the currently active window.

**Setup information**
- OS: macOS 11.6.3
- Version: espanso 0.7.3
