### ISSUE TITLE
When entering values in a form, espanso matches do not work

### ISSUE THREAD

**Issue by Elaws** [federico-terzi/espanso#991]
**Describe the bug**

In a form, it is as if Espanso was disabled : impossible to use defined matches.

**To Reproduce**

1. Define a simple form as follow :

```yaml
  # Scale degree.
  - trigger: ":sd"
    form: \scaleDegree{[[value]]}
    label: "Music: Scale degree"
```

2. Trigger the form using `:sd` 

![image](https://user-images.githubusercontent.com/52013479/154845016-e93454ab-69b3-49db-936b-ac8388c56163.png)

3. In the textbox, it would be really useful if matches worked ! Let's say I have a match that will replace `\sh` into `\sharp`. Well, if you write `\sh` in the text box of the form, nothing happens.

**Expected behavior**
There should be an option to allow Espanso matches in forms, it would be so useful.

**Setup information**
- OS: Windows 10
- Version: 2.1.3
